(() => {
  "use strict";

  const DOC = {
    createIndex: "https://docs.opensearch.org/latest/api-reference/index-apis/create-index/",
    index: "https://docs.opensearch.org/latest/api-reference/document-apis/index-document/",
    documents: "https://docs.opensearch.org/latest/api-reference/document-apis/index/",
    get: "https://docs.opensearch.org/latest/api-reference/document-apis/get-documents/",
    update: "https://docs.opensearch.org/latest/api-reference/document-apis/update-document/",
    delete: "https://docs.opensearch.org/latest/api-reference/document-apis/delete-document/",
    bulk: "https://docs.opensearch.org/latest/api-reference/document-apis/bulk/",
    ingest: "https://docs.opensearch.org/latest/ingest-pipelines/create-ingest/",
    mapping: "https://docs.opensearch.org/latest/mappings/",
    analyzer: "https://docs.opensearch.org/latest/analyzers/",
    refresh: "https://docs.opensearch.org/latest/api-reference/index-apis/refresh/",
    merge: "https://docs.opensearch.org/latest/api-reference/index-apis/force-merge/",
    settings: "https://docs.opensearch.org/latest/install-and-configure/configuring-opensearch/index-settings/",
    segrep: "https://docs.opensearch.org/latest/tuning-your-cluster/availability-and-recovery/segment-replication/index/",
    search: "https://docs.opensearch.org/latest/api-reference/search-apis/search/",
    route: "https://docs.opensearch.org/latest/search-plugins/searching-data/search-shard-routing/",
    routingField: "https://docs.opensearch.org/latest/field-types/metadata-fields/routing/",
    cache: "https://docs.opensearch.org/latest/search-plugins/caching/index/",
    bm25: "https://docs.opensearch.org/latest/mappings/mapping-parameters/similarity/",
    source: "https://docs.opensearch.org/latest/mappings/metadata-fields/source/",
    docvalues: "https://docs.opensearch.org/latest/mappings/mapping-parameters/doc-values/",
    explain: "https://docs.opensearch.org/latest/api-reference/search-apis/explain/",
    searchSettings: "https://docs.opensearch.org/latest/install-and-configure/configuring-opensearch/search-settings/",
    vectorIndex: "https://docs.opensearch.org/latest/vector-search/creating-vector-index/",
    vectorTechniques: "https://docs.opensearch.org/latest/vector-search/vector-search-techniques/index/",
    vectorFilter: "https://docs.opensearch.org/latest/vector-search/filter-search-knn/index/",
    vectorStorage: "https://docs.opensearch.org/latest/vector-search/optimizing-storage/disk-based-vector-search/",
    vectorPerformance: "https://docs.opensearch.org/latest/vector-search/performance-tuning/",
    hybrid: "https://docs.opensearch.org/latest/vector-search/ai-search/hybrid-search/index/",
    voting: "https://docs.opensearch.org/latest/tuning-your-cluster/discovery-cluster-formation/voting-quorums/"
  };

  const deep = (boundary, failure, inspect, question, answer) => ({ boundary, failure, inspect, question, answer });
  const slide = (section, stage, title, question, intro, mode, nodes, facts, takeaway, config, gain, cost, pseudo, source, extra) => ({
    section, stage, title, question, intro, mode, nodes, facts, takeaway, config, gain, cost, pseudo, source, deep: extra
  });

  window.OPENSEARCH_STAGES = [
    ["request", "请求"], ["route", "路由"], ["index", "索引"], ["lucene", "Lucene"],
    ["replica", "副本"], ["vector", "向量"], ["search", "搜索"], ["rank", "排序"], ["fetch", "返回"]
  ];

  window.OPENSEARCH_COURSE = [
    slide("00 · START HERE", "request", "我是一条 Document #D2048", "先别背术语：我们只跟一条 JSON。", "#D2048 是课程追踪编号，sku-8821 是业务 _id。现在它只存在于应用内存；后面每一页只回答它跨过一个边界时发生了什么。", "cover",
      [["OBJECT", "Business object", "应用内存里的商品对象"], ["JSON", "Document source", "准备发送的字段和值"], ["JOURNEY", "One boundary per page", "请求 → Shard → 文件 → 搜索"]],
      [["现在是什么", "#D2048 只是一条商品 JSON，还不是倒排索引，也没有写入磁盘"], ["接下来追什么", "同一条数据怎样被路由、复制、Refresh、搜索、更新和删除"], ["怎么学", "每页只放大一个边界，并回答一个具体问题"]],
      "起点不是 Shard 或 Segment，而是应用准备发送的一条业务 JSON；后面的结构都是 OpenSearch 为不同访问方式生成的物理表示。",
      [["Course id", "#D2048"], ["Business _id", "sku-8821"], ["Index", "products-v3"]],
      "始终追踪同一条数据，复杂术语都有明确落点。", "同一业务值会被编码进多种索引结构，换取不同读取方式的速度。",
      "event = Product(sku=\"sku-8821\")\njson = serialize(event)\n// 下一步才调用 OpenSearch API", DOC.index,
      deep("这一页故意不讲 Shard、Segment 和向量；先确认课程追踪对象是一条业务 JSON。", ["应用对象尚未发送。", "进程此刻崩溃。", "OpenSearch 中不会凭空出现这条 Document。"], [["课程编号", "#D2048 仅用于视觉追踪"], ["业务身份", "_id = sku-8821"], ["原始内容", "写入后通常保存在 _source"]], "#D2048 与 sku-8821 是一回事吗？", "不是。#D2048 是课程里的追踪标签；sku-8821 才是发送给 OpenSearch 的业务 _id。")),

    slide("01 · FOUR LEVELS", "index", "先认清四层，不讲请求流程", "Cluster、Node、Shard、Segment 分别是什么？", "先只看数据摆在哪里：Cluster 包含多个 Nodes；Index 是逻辑名字，它的 Primary/Replica Shard copies 分散在 Nodes 上；每个 Shard 本身是一套 Lucene 索引，由多个不可变 Segments 组成。", "system-primer",
      [["CLUSTER", "All OpenSearch nodes", "共同维护一个集群"], ["NODE", "One OpenSearch process", "使用本机 CPU / RAM / Disk"], ["SHARD", "One Lucene index copy", "Primary 或 Replica"], ["SEGMENT", "Immutable Lucene files", "Shard 内部的文件批次"]],
      [["Cluster", "一组共同工作的 OpenSearch Nodes"], ["Node", "一个运行中的 OpenSearch 进程，使用所在机器资源"], ["Shard", "Index 的物理分片与复制单元；Primary 和 Replica 都是完整 copy"], ["Segment", "Shard 内部不可变的 Lucene 文件集合，Refresh 会发布新 Segment"]],
      "不要把 Index、Shard、Segment 当成三个同级目录：Index 是逻辑入口，Shard copy 才落在 Node 上，Segment 又位于 Shard 内部。",
      [["Primary shards", "3 · P0/P1/P2"], ["Replicas", "1 per primary"], ["Total copies", "6"]],
      "四层边界明确后，故障、扩容、路由和搜索扇出都能找到正确尺度。", "增加 Shards/Replicas 会增加并行度与容错，也增加文件、网络和协调成本。",
      "cluster.nodes = [node0, node1, node2]\nindex(products-v3).primaries = [P0, P1, P2]\nreplicate_each_primary_once()\nP2.luceneSegments = [_0, _1, ...]", DOC.search,
      deep("这里把 Index 画成跨 Nodes 的逻辑名字，而不是一块连续磁盘。一个 Node 可以同时持有多个不同 Index 的 Shard copies。", ["Data Node 2 失联。", "P2 Primary 暂时不可用。", "若 R2 健康，集群可提升 Replica 并恢复缺失副本。"], [["节点", "GET _cat/nodes?v"], ["分片", "GET _cat/shards/products-v3?v"], ["文件视图", "GET _cat/segments/products-v3?v"]], "Replica 是备份文件，还是能处理请求的完整 Shard copy？", "它是完整 Shard copy，可用于容错，也可以承担 GET/Search 读取；写入仍先由 Primary 建立操作顺序。")),

    slide("02 · REQUEST ANATOMY", "route", "先把这一行 API 读明白", "routing=tenant-17 为什么会出现在这里？", "默认情况下 OpenSearch 用 `_id` 作为 routing value。本课程额外传 tenant-17，是为了演示多租户定向路由；这是可选设计，不是默认必填参数。", "request-anatomy",
      [["REQUEST", "PUT products-v3/_create/sku-8821", "Index + create semantics + _id"], ["DEFAULT", "No routing → use _id", "_routing = sku-8821"], ["COURSE CHOICE", "routing=tenant-17", "同租户定向同一路由空间"]],
      [["默认 routing", "不传时使用 `_id`；本例即 sku-8821"], ["自定义 routing", "tenant-17 是课程为多租户场景主动选择的值，不是 OpenSearch 默认值"], ["一致性契约", "写入一旦使用自定义 routing，GET / UPDATE / DELETE 必须继续传同一个值"]],
      "Routing 只负责决定目标 Primary Shard：默认值是 `_id`；tenant-17 是为了定向同租户数据而显式覆盖的可选值。",
      [["default _routing", "_id = sku-8821"], ["course _routing", "tenant-17"], ["mapping required", "false unless configured"]],
      "带 routing 的租户查询可以减少要访问的 Shards。", "租户倾斜会造成 hot shard；漏传或传错 routing 会表现为文档找不到。",
      "routingValue = request.routing ?? request._id\n// default: sku-8821\n// course:  tenant-17\ntargetPrimary = hash(routingValue)  // course demo → P2", DOC.routingField,
      deep("课程没有声称 tenant-17 是最佳实践；它只是一个有明确收益与风险的多租户示例。若没有定向查询/共置需求，默认 `_id` routing 通常更简单。", ["Create 使用 routing=tenant-17。", "GET 忘记 routing，于是默认改用 sku-8821 计算 Shard。", "请求落到另一 Shard，返回 found:false；原 Document 其实仍在 P2。"], [["默认写入", "PUT products-v3/_create/sku-8821"], ["自定义写入", "PUT products-v3/_create/sku-8821?routing=tenant-17"], ["一致读取", "GET products-v3/_doc/sku-8821?routing=tenant-17"]], "为什么自定义 routing 不能随便选一个常量？", "如果所有文档都用同一个 routing，它们会集中到同一路由空间，形成严重 hot shard，失去分片并行能力。")),

    slide("02Z · INDEX SETUP", "index", "第一条 Document 到来前，Index 已准备好什么？", "products-v3 是一块磁盘，还是一份分布式契约？", "写入 #D2048 之前，OpenSearch 已根据 settings 与 mappings 创建 3 个 Primary Shard、各 1 个 Replica，并把 6 个 Shard copies 分散到 3 个 Nodes；Alias 再把业务名指向版本化 Index。", "index-contract",
      [["API", "PUT products-v3", "settings + mappings"], ["LOGICAL", "products-write alias", "业务稳定入口"], ["LAYOUT", "P0 / P1 / P2", "3 Primary Shards"], ["REDUNDANCY", "R0 / R1 / R2", "1 Replica each"]],
      [["创建时确定", "number_of_shards 决定路由模数，不能像普通动态参数随意修改"], ["可动态调整", "number_of_replicas 可按容量与可用性需求改变"], ["Mapping 契约", "字段类型决定倒排、BKD、Doc Values 与向量结构；错误类型常需新索引 + reindex"]],
      "Index 是逻辑契约；真正分布到 Nodes 磁盘上的，是 Primary/Replica Shard copies 与它们内部的 Lucene Segments。",
      [["number_of_shards", "3"], ["number_of_replicas", "1"], ["alias", "products-write → products-v3"]],
      "先定义物理边界与字段契约，后续每条请求都有可预测落点。", "Shard 数、Replica 数与 Mapping 选错，会把容量、迁移和查询成本长期固化。",
      "PUT products-v3\n{ settings: { shards: 3, replicas: 1 },\n  mappings: { sku: keyword, name: text, price: double } }\nPOST _aliases  // products-write → products-v3", DOC.createIndex,
      deep("Alias 让应用不必把 products-v3 写死；重建 products-v4 后可以原子切换读写入口。它不改变 Shard 物理布局，只改变名称解析。", ["动态 Mapping 把任意业务 key 都变成字段。", "字段数持续膨胀并推高 cluster state 与 heap。", "最终不仅单个请求慢，集群元数据更新也变慢。"], [["设置", "GET products-v3/_settings"], ["映射", "GET products-v3/_mapping"], ["分片", "GET _cat/shards/products-v3?v"], ["别名", "GET _alias/products-write"]], "为什么业务通常写 Alias，而不是永久写死 products-v3？", "字段契约升级常需要创建新索引并 reindex；Alias 可把切换从修改所有客户端，变成一次受控的元数据操作。")),

    slide("02A · CREATE", "index", "第 1 步：Create 一条 Document", "发送 PUT 之后，#D2048 依次经过哪里？", "本页按默认 Document Replication 展开：先检查活跃 Shard copies，再由 P2 Primary 完成本地写入；Primary 主动把同一操作推给 R2，等待复制阶段收敛后组装 `_shards` 并返回。", "physical-write",
      [["CODE", "PUT /_create/sku-8821", "JSON + id + routing"], ["PREFLIGHT", "active copies ≥ required", "写前门槛"], ["P2 PRIMARY", "seq_no + local write", "建立操作顺序"], ["PUSH", "Primary → ReplicaRequest", "不是 Replica 拉取"], ["RESULT", "HTTP + result + _shards", "分层判断成功"]],
      [["谁主动复制", "默认 DOCUMENT：Primary PUSH 操作；Replica 在自己的 Buffer 与 Translog 上执行后回 ACK"], ["写前门槛", "wait_for_active_shards 默认 1，只检查 Primary 已 active；它不是写 ACK quorum"], ["怎样算成功", "Create 看 HTTP 201 + result=created；还要检查 _shards.successful / failed，确认实际复制结果"]],
      "写入成功至少意味着 Primary 已成功；是否已经写满所有副本，要看响应 `_shards`，不能从 HTTP 201 或 wait_for_active_shards 猜。",
      [["index.replication.type", "DOCUMENT（默认）"], ["wait_for_active_shards", "1（写前检查）"], ["index.translog.durability", "request（默认）"], ["refresh", "false（默认）"]],
      "Primary 统一分配顺序，Replica 独立执行同一操作，既保持历史一致又保留完整可接管副本。", "活跃 Replica 位于写入关键路径；要求 all 会降低副本不足时的写可用性，异步 durability 又会扩大断电丢失窗口。",
      "assert activeCopies >= required             // 写前 gate\nprimaryOp = primary.index(source)              // seq_no + Buffer + Translog\nfor replica in replicationTargets:\n  push(replica, primaryOp)                     // Primary 主动发送\n  await replica.indexLocallyAndAck()\nreturn created + shardInfo(total, successful, failures)", DOC.index,
      deep("默认 Document Replication 的职责边界是：Primary 决定并执行一次操作，然后向当前 replication targets PUSH ReplicaRequest；Replica 不从 Primary 主动拉文档，也不是由 Primary 远程代写 Replica 磁盘。Replica 自己写本地 Buffer/Translog，并回传 local/global checkpoint。若索引改用 Segment Replication，则是 Primary 在 Refresh 后发布 checkpoint，由 Replica 拉取变化的 Segment 文件；第 18 页单独对比。", ["wait_for_active_shards=all，但 R2 未 active：在写入 Primary 前等待，直到 timeout。", "默认 wait_for_active_shards=1：只有 P2 active 也可以开始写；最终是否复制到 R2 看 `_shards`。", "R2 在写前检查后、复制途中失败：Primary 可能仍已 created，响应通过 `_shards.failed` / failures 暴露副本失败。"], [["完整成功", "HTTP 201 · result=created · _shards={total:2,successful:2,failed:0}"], ["只成功 Primary", "result=created 仍可能成立；不要忽略 _shards 与 failures"], ["副本状态", "GET _cat/shards/products-v3?v"], ["持久性", "GET products-v3/_settings?include_defaults=true"]], "wait_for_active_shards=all 是否等价于‘本次写必须收到所有 Replica ACK 才算成功’？", "不等价。它只在写入开始前检查这些 copies 是否 active；复制开始后仍可能失败。最终实际写成功了几份，要读取响应 `_shards.successful`、`failed` 和 failures。")),

    slide("02A1 · CREATE VS INDEX", "index", "Create 与 Index 只差一个 API 吗？", "同一个 `_id` 已存在时，一个拒绝，一个写出完整新版本。", "`/_create/{id}` 或 `op_type=create` 只允许首次创建，已存在返回 409；普通 `/_doc/{id}` 是完整 Index/Replace：旧 Lucene 文档被 soft-delete，新 JSON 作为完整新文档写入，省略字段不会自动保留。", "index-replace",
      [["CREATE ONLY", "PUT /_create/sku-8821", "exists → 409"], ["INDEX", "PUT /_doc/sku-8821", "missing → create · exists → replace"], ["OLD v7", "完整旧 Lucene Document", "soft-deleted, still occupies bytes"], ["NEW v8", "完整新 Lucene Document", "only live business version"], ["MERGE", "copy retained live docs", "old bytes reclaimed later"]],
      [["逻辑份数", "Refresh 后业务 Search 只看新版本"], ["物理份数", "Merge 前新旧版本可同时占据 Segment 字节"], ["字段语义", "Index 是整文档替换；部分字段修改要用 Update 或应用先合并"]],
      "Replace 后逻辑上只有一个 live Document，物理上会暂存旧版本与新版本；旧版本先标记删除，满足 retention 后再由 Merge 排除。",
      [["op_type", "create / index"], ["refresh", "决定新版本何时可搜索"], ["soft delete", "旧版本隐藏标记"], ["merge", "最终回收旧字节"]],
      "不可变 Lucene Document 让并发读取稳定，替换无需原地改复杂索引结构。", "每次替换都会重建完整索引表示，并带来旧版本、Merge 与磁盘峰值。",
      "if op_type == create && exists(id): return 409\nnewDoc = parse_entire_request_source()\nsoftUpdateDocument(uid, newDoc, __soft_deletes=1)\n// old stays physical until retention-aware merge", DOC.index,
      deep("普通 Index API 不会先把缺失字段从旧 `_source` 补回来；请求体本身就是新完整文档。Update API 才会在目标 Shard 内读取当前 `_source`、应用局部 doc/script，再产出完整新版本。", ["旧文档有 name、price、stock。", "普通 PUT /_doc 只发送 `{price:229}`。", "新 live 文档只剩 price；这不是 OpenSearch 丢字段，而是 Replace 语义。"], [["首次创建", "PUT products-v3/_create/sku-8821"], ["完整替换", "PUT products-v3/_doc/sku-8821"], ["部分更新", "POST products-v3/_update/sku-8821"], ["删除占比", "GET products-v3/_stats/docs,segments"]], "Replace 后磁盘里是不是永远有两份？", "不是永远。新旧版本先共存；Refresh 让新视图过滤旧版本，Retention-aware Merge 在历史不再需要时只把 live 文档写入新 Segment，旧文件引用归零后才释放磁盘。")),

    slide("02B · GET", "fetch", "第 2 步：按 ID 读取 Document", "调用 GET 时，为什么不用扫描整个索引？", "这一页只讲 GET：_id 与 routing 直接算出 P2，OpenSearch 在 P2 Primary 或 Replica 中选择一个可用副本，然后默认以 realtime=true 读取最新版本。", "physical-get",
      [["CODE", "GET /_doc/sku-8821", "必须带相同 routing"], ["ROUTE", "hash(tenant-17) → P2", "不会访问 P0 / P1"], ["COPY", "choose P2 or R2", "一个可用 shard copy"], ["ENGINE GET", "read latest version", "realtime=true"], ["RESULT", "200 · found=true", "_source + version tokens"]],
      [["只查一个 Shard", "GET 是身份读取，不需要向所有 Shards 广播"], ["默认实时", "即使还没 Refresh，也能读取刚写入的最新版本"], ["routing 必须一致", "写入用了 tenant-17，读取也必须传 tenant-17"]],
      "知道 `_id + routing` 时用 GET：它定位一个 Shard group，默认读取最新版本，然后直接返回 `_source`。",
      [["realtime", "true"], ["preference", "random / _local / custom"], ["_source_includes", "裁剪字段"]],
      "点读路径短、无需分布式评分，Replica 还能分摊读取。", "GET 不能按任意字段筛选，也没有相关性排序和聚合。",
      "shard = route(_id, routing)\ncopy = choose_one(primary_or_replica, preference)\ndoc = copy.engine_get(_id, realtime=true)\nreturn doc._source + version_tokens", DOC.get,
      deep("realtime=false 会让 GET 退回最近 Refresh 的索引视图；这不是默认行为。", ["写入使用 routing=tenant-17。", "GET 忘记传 routing。", "请求被路由到另一个 Shard，看起来像文档丢失。"], [["实时", "GET products-v3/_doc/sku-8821?routing=tenant-17"], ["非实时", "GET products-v3/_doc/sku-8821?realtime=false&routing=tenant-17"], ["身份", "查看 _seq_no 与 _primary_term"]], "GET 为什么可以由 Replica 处理？", "Primary 与 Replica 都保存该 Shard 的数据副本；读取可选一个可用 copy，从而分摊点读压力。")),

    slide("02C · SEARCH VISIBILITY", "search", "第 3 步：用 Search 找到 Document", "为什么刚 Create 成功，Search 可能还是 0 hits？", "这一页只看可见性窗口：写入已经进入 Buffer 与 Translog，但当前 searcher 仍只认识旧 Segments。Refresh 发布新 Segment 并打开新 searcher 后，Search 才能命中 #D2048。", "search-window",
      [["CODE", "POST /products-v3/_search", "#D2048 此刻只在 Buffer"], ["SEARCHER v41", "query old Segment view", "尚不包含 #D2048"], ["RESULT", "0 hits", "不是丢数据"], ["REFRESH", "Buffer → Segment v42", "open new Searcher"], ["RETRY", "POST /_search", "1 hit · #D2048"]],
      [["Searcher", "一次已经打开、可供查询读取的搜索快照"], ["Segment", "Refresh 从 Buffer 发布的一批不可变索引文件"], ["需要写后搜", "优先考虑 refresh=wait_for，而不是每次强制 refresh=true"]],
      "Search 查询的是最近发布的搜索视图；从写入 ACK 到下一次 Refresh 之间，暂时搜不到是正常的近实时窗口。",
      [["index.refresh_interval", "自动刷新节奏"], ["refresh", "false / wait_for / true"], ["GET 对照", "默认仍可 realtime 读取"]],
      "批量发布 Segment 保住写入吞吐，并让并发查询读取稳定视图。", "更短刷新间隔会制造更多小 Segment、Searcher reopen 与 Merge 成本。",
      "index(doc)                 // Buffer + Translog\nsearch(searcher_v41)       // 0 hits\nrefresh()                  // publish Segment + v42\nsearch(searcher_v42)       // 1 hit", DOC.refresh,
      deep("这里的 Search 可能访问多个 Shard groups；每个 Shard 选择 Primary 或 Replica 的一个 copy，在各自最近打开的 searcher 上执行查询。", ["Create 返回 result=created。", "应用立刻 Search，得到 0 hits。", "约一个 Refresh 周期后再次 Search，命中 #D2048。"], [["检索", "GET products-v3/_search?q=name:wireless"], ["对照", "GET products-v3/_doc/sku-8821?routing=tenant-17"], ["验证", "POST products-v3/_refresh 后再次 Search"]], "为什么不能让 Search 直接扫描 Translog？", "Translog 面向故障恢复，不具备倒排索引、评分和聚合所需的搜索结构；Search 需要已发布的 Lucene Segment。")),

    slide("02D · UPDATE", "index", "第 4 步：更新 Document", "只改 price，为什么底层仍重写整条 Document？", "这一页只讲 Update：目标 Primary 先取当前 `_source`，合并 `doc` 或运行 script，检测 no-op，再把结果重新索引为新 Lucene 文档；Lucene 同时给旧版本写入隐藏的 soft-delete DocValues 标记。", "document-rewrite",
      [["CODE", "POST /_update/sku-8821", "doc: { price: 229 }"], ["FETCH", "current _source", "price=249"], ["APPLY", "doc / script", "price=229"], ["REINDEX", "new Lucene doc", "new seq_no/version"], ["OLD", "__soft_deletes=1", "retained until safe to merge away"]],
      [["_source", "Update API 需要它来构造新版本"], ["soft delete", "隐藏 Numeric DocValues 字段，不是改 `_source`"], ["CAS", "if_seq_no + if_primary_term 防止基于旧版本覆盖"]],
      "Partial Update 节省的是客户端往返与冲突窗口，不是 Lucene 的物理重写成本。",
      [["detect_noop", "true"], ["retry_on_conflict", "只适合可安全重放的逻辑"], ["script", "必须受控、轻量、确定"]],
      "在目标 Shard 内完成取值、修改和重索引，减少客户端 GET→PUT 竞态。", "高频更新会制造 deleted docs、Merge 压力和向量/索引重建成本。",
      "current = shard.get(_id)._source\nnext = apply_doc_or_script(current)\nif detect_noop && next == current: return noop\nsoftUpdateDocument(uid, next, __soft_deletes=1)\n// atomically mark old + add new Lucene doc", DOC.update,
      deep("retry_on_conflict 会重新读取并再次执行 Update；脚本若包含不可重复副作用、随机值或错误的绝对赋值，盲重试可能改变业务结果。", ["两个请求同时将 stock 减 1。", "一个发生 version conflict 后自动重试。", "增量脚本可得到 8；基于旧绝对值赋值可能覆盖另一次修改。"], [["冲突", "监控 409 version_conflict_engine_exception"], ["脚本", "ctx._source.stock -= params.count"], ["结果", "检查 result=updated / noop / not_found"]], "Update API 传 `{price:229}`，为什么倒排索引里的 name 也可能被重新写？", "Lucene 文档是整体不可变单元；OpenSearch 从完整 `_source` 构造新文档，所有需索引字段都进入新版本。")),

    slide("02D1 · UPDATE TRANSLATION", "replica", "Update Script 会在每个 Replica 再跑一次吗？", "不会：Primary 先把意图翻译成确定的 Index、Delete 或 Noop。", "Primary 在目标 Shard 上实时读取 `_source` 并执行 doc/script；`UpdateHelper` 把结果翻译成具体操作。Replica 收到的是完整新 JSON 的 IndexRequest、确定的 DeleteRequest，或根本没有写入的 Noop，而不是再次执行原脚本。", "update-translation",
      [["INPUT", "stock -= 1", "UpdateRequest · stock was 10"], ["PRIMARY", "read + execute script", "decides stock=9"], ["TRANSLATE", "Index / Delete / Noop", "one deterministic result"], ["REPLICA", "apply concrete operation", "does not rerun script"], ["ACK", "same seq_no + primary_term", "copies converge"]],
      [["UPDATED", "发送完整 IndexRequest，例如 stock=9"], ["DELETED", "脚本设 ctx.op=delete，发送 DeleteRequest"], ["NOOP", "脚本无变化或 ctx.op=none，不产生副本写入"]],
      "Primary 决定业务更新结果，Replica 只执行已经确定的底层操作；这样时间、随机值、重试和副本当前状态都不会让脚本结果分叉。",
      [["script", "只在 Primary prepare/translate"], ["retry_on_conflict", "冲突后 Primary 重新读取并重跑"], ["replica op", "INDEX / DELETE"], ["noop", "no shard write"]],
      "所有副本获得相同最终 source、seq_no 与 primary_term，避免非确定脚本造成数据分叉。", "Primary 承担实时 GET 与脚本 CPU；重试会重新执行脚本，所以脚本必须可安全重放。",
      "current = primary.realtime_get(id)._source\nresult = run_script(current)\ntranslated = result.delete ? DeleteRequest :\n             result.noop ? Noop : IndexRequest(fullSource)\nreplicate(translated, seqNo, primaryTerm)", DOC.update,
      deep("源码边界不是“把 UpdateRequest 广播给副本”。`UpdateHelper.prepare()` 先把它翻译为 IndexRequest、DeleteRequest 或 NOOP；复制阶段的 Replica switch 只处理 CREATE/INDEX/DELETE。", ["脚本使用当前时间或随机数。", "若每个 Replica 独立运行，就可能得到不同字段值。", "Primary 翻译后只复制确定结果，使各副本一致。"], [["源码类", "TransportUpdateAction / UpdateHelper"], ["复制类", "TransportShardBulkAction"], ["业务脚本", "ctx._source.stock -= params.count"], ["结果", "检查 updated / deleted / noop"]], "为什么 retry_on_conflict 仍可能多次执行脚本？", "冲突发生在 Primary 上；它会重新读取最新 `_source` 并重新翻译 Update。因此增量逻辑要可重放，外部副作用不能偷偷放进脚本。")),

    slide("02E · DELETE", "index", "第 5 步：删除 Document", "Delete 成功后，#D2048 是立刻从磁盘消失吗？", "这一页只讲 Delete：请求按 _id/routing 找到 Primary，分配新的 seq_no/version；Engine 用 softUpdateDocument 标记旧版本，并写一条 soft-deleted tombstone 保存删除操作历史。Search 在 Refresh 后隐藏它，旧字节仍要等 Merge 与引用释放。", "delete-timeline",
      [["CODE", "DELETE /_doc/sku-8821", "id + same routing"], ["ROUTE", "_id + routing → P2", "one shard"], ["PRIMARY", "soft delete + tombstone", "new seq_no/version"], ["REFRESH", "new Searcher filters marker", "Search no longer sees"], ["MERGE", "retention allows → omit", "then reclaim files"]],
      [["CAS delete", "if_seq_no + if_primary_term 防止删除已被更新的新版本"], ["tombstone", "保存删除操作历史，不是业务 `_source`"], ["three clocks", "ACK、Search 隐藏、磁盘回收不是同一时刻"]],
      "Delete ACK 只说明写操作已按复制策略完成；Search 隐藏由 Refresh 推进，磁盘回收还要等待 retention、Merge 与旧 Reader/PIT 引用释放。",
      [["refresh", "false / wait_for / true"], ["soft_deletes.retention", "operations + retention leases"], ["conflicts", "delete_by_query 的冲突策略"]],
      "删除操作同样有顺序、复制与乐观并发保护。", "逐文档删除会制造 tombstones 和 Merge 写放大；海量时序数据更适合按索引生命周期删除。",
      "if current.seqNo != expected: return 409\ntombstone = deleteHistory(seqNo, primaryTerm)\nsoftUpdateDocument(uid, tombstone, __soft_deletes=1)\ntranslog.append(deleteOp); replicate(deleteOp)\n// Refresh hides; Merge + ref release reclaims", DOC.delete,
      deep("Delete by Query 先建立搜索快照，再分批删除；过程中后续批次失败不会回滚已经成功的删除，因此必须检查 conflicts、failures 和实际 deleted 数。这里的 tombstone 是 Engine 为恢复/历史保留的内部文档，同样带 `__soft_deletes`，不要把它理解成会被普通 Search 命中的业务文档。", ["清理脚本匹配 100 万文档。", "执行中部分 Bulk 被拒绝。", "前 40 万已删除，后续失败；应用把任务当全有或全无。"], [["单删", "DELETE products-v3/_doc/sku-8821?routing=tenant-17"], ["批删", "POST products-v3/_delete_by_query?conflicts=proceed"], ["物理", "GET products-v3/_stats/docs,segments,merge"]], "Delete 返回成功，为什么磁盘可能反而短暂上升？", "后台 Merge 先写新 Segment；soft-deleted 历史若仍受 retention lease 保护还会被保留，旧 Segment 又可能被 Searcher/PIT 引用，因此新旧文件会短时共存。")),

    slide("02E1 · THREE DELETE RECORDS", "lucene", "一次 Delete 为什么要留下三种记录？", "VersionMap、Translog 和 Lucene Tombstone 分别保护三个时间尺度。", "删除不是写一个布尔字段就结束：Heap 中的 DeleteVersionValue 负责立刻判断最新状态；Translog Delete Operation 负责最近操作的崩溃恢复；Lucene 内部 soft-deleted Tombstone 负责复制、Peer Recovery 与历史保留。旧业务 Document 另外被 `__soft_deletes` 隐藏。", "delete-records",
      [["HEAP", "LiveVersionMap", "uid → deleted/version/seq/term/time"], ["RECOVERY LOG", "Translog DELETE", "id + routing + seq_no + term"], ["LUCENE HISTORY", "soft-deleted tombstone", "internal metadata, no business _source"], ["OLD BUSINESS DOC", "__soft_deletes=1", "filtered after Refresh"], ["CLEANUP", "different lifecycles", "prune / flush / retention merge"]],
      [["VersionMap deleted", "实时 GET 立即 found=false，并拒绝迟到旧操作"], ["Translog delete", "最近 Lucene commit 之后崩溃时可重放"], ["Lucene tombstone", "保留删除这个操作本身的 seq_no 历史，普通 Search 看不到"]],
      "三种记录不是三份业务文档：它们分别回答“现在状态是什么、崩溃怎样恢复、复制历史怎样证明发生过删除”。",
      [["DeleteVersionValue", "JVM heap · volatile"], ["Translog", "local recovery until commit"], ["_tombstone", "internal Lucene doc"], ["__soft_deletes", "hidden Numeric DocValues"]],
      "即时状态、短期恢复和较长期复制历史各有独立载体，避免为了实时判断强制 Refresh。", "高删除率会增加 Heap tombstones、Translog、soft-deleted docs 与 Merge 工作。",
      "versionMap[id] = DeleteVersionValue(v, seq, term, now)\ntranslog.append(Delete(id, routing, seq, term))\ntombstone = internalDoc(id, seq, term, _tombstone)\nsoftUpdateDocument(uid, tombstone, __soft_deletes=1)", DOC.delete,
      deep("VersionMap 的 delete tombstone 与 Lucene Tombstone Document 名字相似但不是同一个对象。前者是 `LiveVersionMap` 中的 Heap entry；后者是 Engine 构造并写入 Lucene 的内部文档，自身带 `__soft_deletes`，由 retention policy 决定历史保留。", ["只看 Search 已经 0 hit，就认为所有删除状态都已清理。", "Replica 落后，需要请求 Primary 的操作历史。", "若 Tombstone 历史过早消失，迟到操作可能难以正确判定。"], [["实时状态", "GET /_doc/sku-8821 → found:false"], ["Translog", "GET products-v3/_stats/translog"], ["删除统计", "GET products-v3/_stats/docs,segments"], ["恢复", "GET _cat/recovery/products-v3?v"]], "VersionMap delete entry 被清掉，是否代表磁盘旧文档也删了？", "不代表。Heap entry、Translog generation、Lucene Tombstone 和旧 Segment 文件拥有不同清理条件；物理空间仍要等 retention-aware Merge 与旧 Reader 引用归零。")),

    slide("03 · INDEX OR BULK", "request", "单条 Index 与 Bulk 到底差在哪？", "Bulk 是协议批处理，不是全有或全无的事务。", "Bulk 使用 NDJSON 把多个操作装入一次 HTTP 请求，减少网络和解析开销；每一项仍独立路由、独立成功或失败。", "compare",
      [["INDEX", "1 operation", "简单 · 延迟直观"], ["BULK", "N operations", "共享 HTTP · 分散到多个 shards"], ["RESULT", "per item status", "必须逐项检查"]],
      [["格式", "action line + optional source line，最后必须换行"], ["失败", "HTTP 200 也可能 errors=true"], ["并发", "批次过大或并发过高会压垮 write queue 与 heap"]],
      "Bulk 的正确单位不是“请求成功”，而是“每个 item 都被检查并分类重试”。",
      [["bulk size", "按字节与 P99 调优"], ["concurrency", "由压测决定"], ["refresh", "不要逐批 true"]],
      "更少的 HTTP 往返与更好的吞吐。", "局部失败、内存峰值与重试去重更复杂。",
      "for item in bulkResponse.items:\n  if item.ok: mark_done(item.id)\n  elif retryable(item.status): retry_with_backoff(item)\n  else: dead_letter(item)", DOC.bulk,
      deep("Bulk 不跨 shard 提供原子性，也不保证列表顺序就是物理写入顺序。", ["1000 项 Bulk 返回 200。", "其中 17 项 429、3 项 mapping error。", "应用只看 HTTP 状态，永久丢掉 20 项。"], [["响应", "检查 errors 与 items[].status/error"], ["线程池", "GET _cat/thread_pool/write?v"], ["压力", "GET _nodes/stats/jvm,thread_pool"]], "Bulk 越大吞吐一定越高吗？", "不是。超过收益拐点后会增加 heap、排队、超时和重试放大，应该用实际文档大小与 P99 压测确定。")),

    slide("04 · COORDINATING NODE", "request", "第 3 步：接收节点怎样找到 P2 Primary？", "任意节点能协调，是因为每个节点都持有可路由请求的 Cluster State 副本。", "#D2048 先到 Node-0。Node-0 不写这条 Document：它在本机内存中解析 Alias/Pipeline/Routing，用本地 Cluster State v928 查出 P2 Primary 当前位于 Node-2，再通过节点间 Transport 转发；Node-2 完成写入后，响应仍沿 Node-0 的原 HTTP 连接返回。", "coordinator-routing",
      [["CLIENT", "PUT products-write/_create/sku-8821", "只认识稳定入口"], ["NODE-0", "temporary coordinator", "HTTP parse + authorization"], ["LOCAL STATE", "cluster state v928", "index metadata + routing table"], ["ROUTE", "hash(tenant-17) % 3 = P2", "决定 shard number"], ["LOOKUP", "P2 primary → Node-2", "决定 physical node"], ["TRANSPORT", "Node-0 → Node-2", "internal request · response returns"]],
      [["为什么任意节点都行", "Cluster Manager 把最新 Cluster State 发布给所有节点；接收节点本地查表，不必每次询问 Manager"], ["谁真正写数据", "只有目标 P2 Primary 改变索引状态；Node-0 只是暂存请求、路由和转发"], ["客户端会被重定向吗", "不会；Node-0 通过内部 Transport 调 Node-2，再用原 HTTP 连接把结果返回客户端"]],
      "协调节点解决的是“我该把请求送到哪里”；Primary 解决的是“这条写入怎样排序、持久化和复制”。两种职责不能画成同一个框。",
      [["cluster state", "index metadata + routing table"], ["routing", "tenant-17 → P2"], ["primary", "P2 → Node-2"], ["network", "HTTP 9200 / Transport 9300"]],
      "客户端不需要追踪 Primary 搬迁；新 Cluster State 发布后，任意接收节点都能把后续请求送到新位置。", "每次请求都会消耗接收节点的解析、队列、网络与协调资源；搜索扇出和 Reduce 尤其可能放大 CPU/Heap。",
      "request = receiveHttp()\nindex = localState.resolveAlias(products-write)\nsource = runPipelineIfNeeded(request.source)\nshard = hash(routing ?? id) % index.primaryShards\nnode = localState.routingTable.primaryNode(shard)\nresult = transport.send(node, concreteRequest)\nreturn sameHttpConnection(result)", DOC.index,
      deep("Cluster Manager 维护并发布权威 Cluster State；普通节点持有已发布状态的本地副本，用它解析索引、Alias 和 Shard allocation。数据请求不需要同步询问 Cluster Manager，因此 Manager 不在每条 CRUD 的数据路径里。", ["Node-0 的本地路由表仍指向旧 Primary。", "转发遇到 shard_not_found / stale primary term。", "节点刷新 Cluster State，并由上层按请求语义决定是否安全重试。"], [["节点角色", "GET _cat/nodes?v&h=name,node.role"], ["Shard 位置", "GET _cat/shards/products-v3?v"], ["Cluster State", "GET _cluster/state/routing_table,metadata/products-v3"], ["协调压力", "GET _nodes/stats/http,transport,thread_pool,breaker"]], "为什么不让客户端直接缓存 P2 Primary 的 IP？", "Primary 会因故障、恢复和重新分配而搬迁。把位置解析留在集群内，客户端只需要稳定入口；接收节点依据最新 Cluster State 完成寻址。")),

    slide("04A · CLIENT ENTRY", "request", "业务客户端到底应该配置几个 OpenSearch 地址？", "应用通常只认识一个稳定入口，入口后面必须有多个可用节点。", "生产最常见的是一个稳定 DNS/LB Endpoint，后接 2～3 个跨故障域的 Coordinating/Data Nodes；没有 LB 时，客户端配置 2～3 个 Initial HTTP Hosts 并做连接池和失败切换。这里不是集群组网用的 `discovery.seed_hosts`。", "client-entry",
      [["RECOMMENDED", "1 stable endpoint", "DNS/LB → 2–3 coordinator targets"], ["ALTERNATIVE", "2–3 initial HTTP hosts", "client node pool / failover"], ["AVOID", "1 data-node IP", "restart or relocation = outage"], ["COORDINATE", "any receiving node", "resolve, route, fan-out, reduce"], ["SCALE", "dedicated coordinators", "when parsing/reduce pressure is material"]],
      [["业务配置", "通常 1 个稳定域名，而不是几十个 Shard/Node 地址"], ["LB 后端", "至少 2～3 个健康目标，跨 AZ/故障域"], ["无 LB", "配置少量 Initial HTTP Hosts；是否 sniff/discover 取决于客户端与网络边界"]],
      "“连接任意节点”描述的是服务端能力；“业务只配一个稳定 Endpoint”描述的是生产接入方式，两者并不矛盾。",
      [["endpoint", "https://search.example.com"], ["targets", "coord-1 / coord-2 / coord-3"], ["health", "LB probe + client retry"], ["timeout", "connect / socket / request"]],
      "业务不需要追踪 Primary 搬迁，入口节点根据 Cluster State 转发到当前正确位置。", "单入口背后的 LB、DNS、证书与 Coordinator 仍需多活；重试不当会放大故障流量。",
      "client → search.example.com\nLB → healthy(coord-1 | coord-2 | coord-3)\ncoordinator.resolve(clusterState)\ncoordinator.forward(targetShardPrimary)", DOC.documents,
      deep("较小集群可让 Data Node 同时协调；搜索与大聚合规模上来后，再评估 coordinating-only nodes。不要让业务只连接 Cluster Manager Node，也不要为了‘高可用’把所有 Data Nodes 永久写死进配置。注意应用客户端的 Initial HTTP Hosts 与节点发现配置 discovery.seed_hosts 是两套概念。", ["客户端只配 node-1 的固定 IP。", "node-1 滚动升级或网络隔离。", "其余集群健康，但业务连接入口已经中断。"], [["入口", "检查 DNS/LB target health"], ["节点", "GET _cat/nodes?v&h=name,ip,node.role"], ["客户端", "连接池、重试与 dead-node 指标"], ["协调压力", "GET _nodes/stats/jvm,breaker,thread_pool"]], "为什么客户端重试也可能让故障更严重？", "若大量请求在节点变慢时立即无退避重试，会把一次超时放大成多倍流量；需要幂等判断、指数退避、抖动和总超时预算。")),

    slide("05 · INGEST PIPELINE", "request", "一条原始 JSON 经过 Pipeline 后具体变成什么？", "把前后 Document 并排看，Pipeline 才不会只是一个名词。", "本例依次 rename `userId`、把字符串 price 转成 double、补 `ingested_at` 与来源、删除 password/cardNumber；处理后的 JSON 才进入 Mapping 与 Shard 写入。每个 Processor 顺序执行，失败可进入 `on_failure`。", "ingest-pipeline",
      [["RAW JSON", "userId + price:string", "contains password/cardNumber"], ["PROCESSORS", "rename → convert → set → remove", "sequential"], ["CLEAN JSON", "user_id + price:double", "ingested_at + source_system"], ["FAILURE", "on_failure", "attach ingest_error or reject"], ["VERIFY", "_simulate?verbose=true", "see each processor result"]],
      [["Pipeline 改什么", "直接改变或补充 `_source` JSON"], ["Analyzer 改什么", "把 text 字段生成 terms，通常不改 `_source`"], ["Update 注意", "不要依赖现有文档的部分 Update 自动重跑整套 Pipeline"]],
      "Ingest Pipeline 是写入前可测试的数据变换程序：看输入、按顺序看每个 Processor、再确认进入 Mapping 的最终 JSON。",
      [["pipeline", "order-normalize-v1"], ["invoke", "?pipeline=order-normalize-v1"], ["simulate", "verbose=true"], ["on_failure", "ingest_error"]],
      "统一清洗、类型规范和敏感字段移除，降低每个生产者重复实现。", "Processor 占用 ingest CPU/queue；慢脚本和复杂 enrich 会直接增加写入延迟与故障面。",
      "rename(userId → user_id)\nconvert(price → double)\nset(ingested_at = _ingest.timestamp)\nset(source_system = order-service)\nremove(password); remove(cardNumber)", DOC.ingest,
      deep("真实请求使用 `PUT /orders-v3/_doc/A1024?pipeline=order-normalize-v1`。上线前用 `_simulate?verbose=true` 查看每个 Processor 的中间结果，并覆盖缺字段、错误类型与 on_failure 分支。", ["price 收到无法转换的字符串。", "convert processor 抛错并进入 on_failure。", "如果 on_failure 只吞错不标记，脏数据可能悄悄进入索引。"], [["定义", "PUT _ingest/pipeline/order-normalize-v1"], ["模拟", "POST _ingest/pipeline/order-normalize-v1/_simulate?verbose=true"], ["调用", "PUT orders-v3/_doc/A1024?pipeline=order-normalize-v1"], ["统计", "GET _nodes/stats/ingest"]], "为什么删除 password 不能只靠 `_source` filtering？", "返回时 filtering 只是隐藏响应字段，原数据仍可能已经写入；在数据不应落库时，应在应用或 Ingest Pipeline 写入前真正移除，并配合权限与日志治理。")),

    slide("06 · MAPPING", "index", "同一个 name，为什么要写成两套索引？", "一份 `_source`，通过 `fields.raw` 生成 text 与 keyword 两种物理表示。", "本例在 Mapping 中显式把 keyword 子字段命名为 `name.raw`。当前默认 Dynamic Mapping 遇到普通字符串时，通常会创建 text + `name.keyword`（并带 `ignore_above:256`），不是自动叫 raw。无论来源如何，原 JSON 仍只有一个 name；text 路径生成 tokens/postings，keyword 路径保留一个完整 term并默认生成 Doc Values。", "structure",
      [["INPUT", "_source.name", "Wireless Headphones · stored once"], ["TEXT", "name", "Analyzer → tokens → postings"], ["KEYWORD", "name.raw", "one term → postings + doc values"], ["NUMBER", "price:double", "BKD range index + doc values"]],
      [["子字段来自 Mapping", "本例显式 `name.raw`；默认 dynamic string 通常生成 `name.keyword`"], ["不是 `_source` 复制", "raw/keyword 子字段是索引表示，原 JSON 仍只有 name"], ["text 读法", "match/full-text；默认无 doc_values，不直接排序聚合"], ["keyword 读法", "term/filter + sort/aggregation；可配置 normalizer"], ["成本", "每多一种索引表示，都增加磁盘、Refresh、Merge 与 Reindex 工作"]],
      "Mapping 是写入时的物理编译计划：它决定同一个 JSON 值被转换成哪些可查询结构，而不是给字段贴一张说明标签。",
      [["name.type", "text"], ["name.fields.raw.type", "keyword · 本例显式"], ["dynamic string", "默认 text + .keyword"], ["text.doc_values", "不支持 / 默认无"], ["keyword.doc_values", "true · default"]],
      "一份业务值同时满足全文匹配与精确排序聚合。", "多字段会写多套结构；类型或 Analyzer 演进通常需要新索引 + reindex。",
      "value = source.name\nfor term in analyzer(value): postings[name][term].add(docID)\nexact = normalize(value) ?? value\npostings[name.raw][exact].add(docID)\ndocValues[name.raw][docID] = exact\nstoreSourceOnce(source)", DOC.mapping,
      deep("`fields` 定义同一输入字段的多种索引方式。`name.raw` 不出现在 `_source`；它存在于 Mapping 与 Lucene 索引结构中。Dynamic Mapping 默认开启，当前默认字符串规则通常创建 `text` + `.keyword` 子字段，并为 keyword 设置 `ignore_above:256`；生产中仍推荐显式 Mapping/模板来固定名字、类型和成本。", ["JSON 只提交 name。", "本例 Mapping 显式声明 fields.raw；若完全依赖默认 Dynamic Mapping，常见名字会是 name.keyword。", "写入同时生成 name 的 tokens 和所配置 keyword 子字段的完整 term/Doc Values。"], [["映射", "GET products-v3/_mapping/field/name*"], ["分析", "POST products-v3/_analyze"], ["字段能力", "GET products-v3/_field_caps?fields=name,name.raw,name.keyword"], ["限制", "检查 index.mapping.total_fields.limit"]], "为什么不能对 name:text 直接做大量排序或聚合？", "text 被拆成多个 token，且默认没有 Doc Values；开启 fielddata 会把 uninverted terms 放入 JVM heap，代价高。通常应对 keyword 子字段做 sort/aggregation。")),

    slide("07 · SHARD ROUTING", "route", "#D2048 为什么只去 P2？", "Routing 用确定性哈希把一次 Document CRUD 定向到一个 Primary shard。", "默认 routing value 是 `_id`；本例显式传 `routing=tenant-17`，并假设默认 `routing_partition_size=1`，因此可用 `hash(routing) % 3` 理解为落到 P2（课程示意）。若配置 partitioned routing，同一 routing 会对应一个 Shard 子集，再结合 `_id` 选定其中一个。", "formula",
      [["INPUT", "tenant-17", "routing key"], ["HASH", "hash(routing)", "deterministic"], ["MOD", "% primaryShards", "3"], ["TARGET", "P2 Primary", "示意结果"]],
      [["写", "只发目标 Primary，而不是广播所有 shards"], ["读", "GET/UPDATE/DELETE 必须使用同一 routing"], ["热点", "大租户可能把 P2 变成单 shard 瓶颈"]],
      "Shard Routing 用确定性换取定向读写；错误 routing 会表现得像文档消失。",
      [["routing", "tenant-17"], ["number_of_shards", "3 · static"], ["routing_partition_size", "1 · 本例默认"], ["partitioned routing", "公式还会结合 _id"]],
      "单文档操作 O(1) 定位目标 shard。", "热点与租户倾斜不能靠加 Replica 解决写瓶颈。",
      "routing = request.routing ?? request._id\nif routingPartitionSize == 1:\n  shard = floorMod(hash(routing), primaryShards)\nelse:\n  shard = chooseWithinRoutingSubset(hash(routing), hash(_id))\n// course example → P2", DOC.routingField,
      deep("修改 Primary shard 数通常需要重建索引，因为路由函数的模数属于数据布局。Split/Shrink 有约束，也不是随意在线改模数。", ["tenant-17 占全站 40% 写入。", "P2 write queue 和 merge 压力异常。", "其他 shards 空闲，扩节点仍无法均摊该 routing key。"], [["分布", "GET _cat/shards/products-v3?v"], ["stats", "GET products-v3/_stats/indexing,store,segments"], ["routing", "按租户对比请求量与 shard 归属"]], "Replica 能解决热点 Primary 的写入瓶颈吗？", "不能。每次写仍先由唯一 Primary 执行，并复制更多副本；需要重设 routing/key 或索引布局。")),

    slide("08 · ANALYZER", "index", "一句话怎样变成可搜索的 Terms？", "Char Filter → Tokenizer → Token Filters。", "name 使用 index analyzer：先规范字符，再切词，最后 lowercase、同义词或停用词处理。输出 token 包含 term、position 和 offsets。", "flow",
      [["TEXT", "Wireless Noise-Cancelling", "original field"], ["CHAR", "normalize punctuation", "wireless noise cancelling"], ["TOKENIZE", "standard tokenizer", "3 tokens"], ["FILTER", "lowercase", "wireless · noise · cancelling"]],
      [["index analyzer", "写入时生成持久 terms"], ["search analyzer", "查询时处理用户输入"], ["兼容", "两者不必相同，但必须语义兼容"]],
      "Analyzer 决定“什么可以被匹配”；改 Analyzer 通常意味着重建已有文档的索引。",
      [["analyzer", "products_en_v2"], ["search_analyzer", "products_query_v2"], ["position_increment_gap", "数组短语语义"]],
      "语言、大小写、词形与同义词可控。", "分析链越复杂，相关性调试与升级成本越高。",
      "tokens = char_filters(text)\ntokens = tokenizer(tokens)      // exactly one\ntokens = token_filters(tokens)\nfor token in tokens: postings[token].add(docID, pos)", DOC.analyzer,
      deep("同义词放在索引端会扩大索引且升级需 reindex；放在查询端更灵活，但可能扩大 query 和评分复杂度。", ["分析器升级后只影响新文档。", "同一 index 中旧/新文档生成不同 terms。", "搜索结果出现难以解释的版本断层。"], [["分析", "POST products-v3/_analyze"], ["词项", "POST products-v3/_termvectors/sku-8821"], ["映射", "确认 analyzer/search_analyzer 名称"]], "为什么只修改 analyzer 配置不会自动改变已有文档？", "已有 Segment 中的 terms 已写死；必须让文档重新经过分析并生成新 Segment，通常通过 reindex。")),

    slide("09 · INVERTED INDEX", "lucene", "倒排索引究竟倒了什么？", "从 Document → words，反转成 term → documents。", "每个 text/keyword 字段拥有 term dictionary 和 postings。搜索 noise 不需要扫描全部 JSON，而是直接找到包含它的内部 docID、词频与位置。", "structure",
      [["TERM DICT", "cancelling · noise · wireless", "sorted terms / FST-like lookup"], ["POSTINGS", "noise → [7, 18, 31]", "docIDs + freq + positions"], ["DOC #7", "#D2048", "Lucene-local docID"]],
      [["docID", "Segment 内部编号，merge 后可能改变"], ["positions", "phrase/proximity query 的基础"], ["norms", "字段长度等评分信号"]],
      "倒排索引优化的是“给我这个词的文档”，不是“给我这个文档的原 JSON”。",
      [["index_options", "docs/freqs/positions/offsets"], ["norms", "text 常启用"], ["term vectors", "默认不存"]],
      "全文检索从 O(N 文档扫描) 变成按 term/postings 工作。", "更多 positions、offsets、norms 会增加存储。",
      "term = lookup_dictionary(\"noise\")\nfor docID in postings(term):\n  score += bm25(term, docID)", DOC.analyzer,
      deep("Lucene docID 是内部实现细节，不是业务主键。Segment merge 会把活文档复制到新 Segment 并重新编号。", ["应用把内部 docID 当稳定 ID 缓存。", "后台 merge 完成。", "缓存指向错误文档或失效。"], [["解释", "GET products-v3/_explain/sku-8821"], ["termvector", "POST products-v3/_termvectors/sku-8821"], ["segments", "GET _cat/segments/products-v3?v"]], "为什么 phrase query 比简单 term filter 更需要位置数据？", "短语查询要验证多个 term 在同一文档中的相对 position，而普通包含判断只需 docID 集合。")),

    slide("10 · FOUR INDEX VIEWS", "lucene", "一条 Document 同时变成哪几种结构？", "搜索、聚合与返回需要不同的数据方向。", "#D2048 不只存在一次：倒排索引服务 term→docs；Doc Values 服务 doc→field value；_source 保存原 JSON；stored fields 可单独存字段。", "structure",
      [["INVERTED", "term → docIDs", "full-text / filter"], ["DOC VALUES", "docID → value", "sort / agg / script"], ["_SOURCE", "stored original JSON", "fetch / update / reindex"], ["STORED", "selected fields", "optional"]],
      [["方向", "倒排与列式访问方向相反"], ["磁盘", "Doc Values 通常是磁盘列式结构，由 OS cache 加速"], ["代价", "同一业务值可能为不同用途重复编码"]],
      "检索快不是靠一种万能结构，而是用空间换取不同访问模式的速度。",
      [["doc_values", "keyword/numeric 默认常为 true"], ["_source.enabled", "true"], ["store", "默认 false"]],
      "查询、排序、聚合和返回各走合适结构。", "索引体积、写放大和 Page Cache 需求增加。",
      "index(text)      → inverted_index\ncolumn(keyword) → doc_values\nstore(document)  → _source\nstore(field)     → stored_fields", DOC.docvalues,
      deep("从 _source 排序会非常昂贵；排序/聚合通常应依赖 Doc Values。text 默认也不适合直接聚合。", ["业务在高基数字段上启用 fielddata。", "大量 term 被加载进 JVM heap。", "节点出现 fielddata breaker 或长 GC。"], [["字段", "GET products-v3/_mapping/field/name"], ["breaker", "GET _nodes/stats/breaker,indices/fielddata"], ["结构", "优先 name.raw keyword + doc_values"]], "为什么 _source 已经保存 price，还需要 Doc Values？", "_source 面向整文档还原；Doc Values 按字段列式组织，可高效遍历许多文档做排序和聚合。")),

    slide("10A · LIVE VERSION MAP", "lucene", "VersionMap 到底保存什么，为什么 GET 能实时？", "它是每个 Shard Engine 的 Heap 状态表，不是完整文档缓存。", "`LiveVersionMap` 将 uid 映射到最近版本元数据：version、seq_no、primary_term，以及可选 Translog location；删除则使用带时间戳的 DeleteVersionValue。它让未 Refresh 的 GET、Create 冲突检查和并发控制不必强制打开新 Searcher。", "version-map",
      [["KEY", "uid / _id", "sku-8821"], ["INDEX VALUE", "version + seq_no + term", "optional translog location"], ["DELETE VALUE", "deleted + timestamp", "recent tombstone state"], ["REFRESH", "current → old → clear", "normal entries can age out"], ["NOT HERE", "no full _source/postings", "not persisted cluster metadata"]],
      [["实时 GET", "先查 VersionMap；有 Translog location 时可直接构造最新结果"], ["Create/OCC", "检查未 Refresh 的同 ID 写入与 if_seq_no/if_primary_term"], ["删除保护", "DeleteVersionValue 让实时 GET 立即 found=false，并阻止迟到旧操作"]],
      "VersionMap 是 Shard 内“最新身份状态的内存索引”：只保存足够定位和比较版本的元数据，不保存整份业务文档。",
      [["scope", "one Shard Engine"], ["memory", "JVM heap"], ["maps", "current + old during refresh"], ["delete", "separate tombstones"]],
      "避免为每次 GET/Update/Create 检查强制 Refresh，显著缩短实时身份读路径。", "更新热点和删除 tombstones 会消耗 Heap；它是易失状态，真实恢复仍依赖 Lucene 与 Translog。",
      "state = versionMap.get(uid)\nif state.deleted: return not_found\nif realtime && state.translogLocation:\n  return read_translog(state.translogLocation)\nelse: return internal_searcher.get(uid)", DOC.get,
      deep("Refresh 过程中 `LiveVersionMap` 使用 current/old 两张 lookup 保证切换不漏掉并发写；Refresh 后普通索引项可由 Lucene Reader 接管，而 delete tombstones 会按独立安全窗口保留。", ["#D2048 刚写完还没 Refresh。", "Search Reader 看不到新版本。", "VersionMap 给出 Translog location，realtime GET 仍返回最新 `_source`。"], [["源码类", "LiveVersionMap / VersionValue / DeleteVersionValue"], ["实时读取", "GET /_doc/sku-8821?realtime=true"], ["版本令牌", "观察 _seq_no / _primary_term"], ["Heap", "GET _nodes/stats/jvm,indices"]], "VersionMap 重启后还在吗？", "不在。它是 JVM Heap 结构；Shard 启动时依靠安全 Lucene commit、Translog 重放和恢复流程重新建立当前状态，因此不能把它当持久数据库。")),

    slide("11 · BUFFER + TRANSLOG", "lucene", "源码里到底先写 IndexWriter，还是先写 Translog？", "方法调用顺序与耐久性边界必须分开看。", "当前 `InternalEngine.index()` 先调用 `indexIntoLucene()` 更新 IndexWriter，再 `translogManager.add()`，随后更新 VersionMap；但默认 durability=request 下，请求必须等 Translog fsync 达到持久化边界才可 ACK。", "engine-write-order",
      [["1 · INDEXWRITER", "indexIntoLucene", "build query structures in RAM"], ["2 · TRANSLOG", "append operation", "recovery record"], ["3 · VERSIONMAP", "uid → latest metadata", "realtime state"], ["4 · FSYNC", "durability=request", "before shard ACK"], ["5 · LATER", "refresh / flush", "search visibility / commit boundary"]],
      [["调用顺序", "IndexWriter → Translog append → VersionMap"], ["耐久边界", "默认 request：Translog fsync 完成后才允许本 Shard ACK"], ["为什么两份", "IndexWriter 负责搜索表示；Translog 负责未 Commit 操作恢复"]],
      "不要把“Translog 是恢复日志”误解成 Java 必须先调用它；真正正确性边界是：在 ACK 前，操作已经进入可搜索构建路径并满足 Translog durability。",
      [["index.translog.durability", "request / async"], ["sync_interval", "async 时相关"], ["indexing_buffer", "节点级共享预算"]],
      "顺序追加降低每条写入成本，同时保留恢复能力。", "更强 durability 增加 fsync 延迟；async 扩大节点级故障丢失窗口。",
      "result = indexIntoLucene(index, plan)\nlocation = translogManager.add(Index(index, result))\nversionMap.put(uid, VersionValue(location, seq, term))\nif durability == request: syncTranslog(location)\n// only then shard copy may ACK", DOC.settings,
      deep("为什么不每条写都 Lucene Commit？Commit 需要同步多类 Segment 文件与 commit point，成本远高于顺序追加 Translog。OpenSearch 先在 IndexWriter 中构建搜索结构，再用 Translog 作为较轻的恢复日志；之后 Refresh 发布可搜索 Segment，Flush 建立 Lucene commit 并滚动/清理旧 Translog。", ["操作已进入 IndexWriter，但进程在 Translog durability 前崩溃。", "客户端没有拿到 ACK，可以按幂等策略重试。", "默认 request 模式不会把未 fsync 的操作当成已完成响应。"], [["源码顺序", "InternalEngine.index → indexIntoLucene → translogManager.add"], ["统计", "GET products-v3/_stats/translog,refresh,flush,indexing"], ["配置", "GET products-v3/_settings?include_defaults=true"], ["延迟", "关联 fsync、I/O 与 indexing latency"]], "Document 已能被 Search 命中，是否等于 Translog 已被 Flush 清空？", "不等于。Refresh、Translog fsync、Flush 分别解决搜索可见、操作日志耐久、Lucene commit/Translog 生命周期；它们是三个独立事件。")),

    slide("12 · DOCUMENT REPLICATION", "replica", "默认复制时，Primary 做了什么？", "OpenSearch 默认是 Document replication。", "Primary P2 建立操作顺序并执行本地写入，再把确定的 Index/Delete 操作转发到所有适用 Replica。副本在自己的 IndexWriter 与 Translog 中应用该操作；Update script 已在 Primary 翻译完成，不会在 Replica 重跑。", "flow",
      [["P2 PRIMARY", "perform #D2048", "assign seq_no + decide result"], ["R2 / NODE-1", "apply concrete operation", "INDEX or DELETE, not Update script"], ["RESPONSE", "acknowledge", "successful / failed copies"]],
      [["顺序", "Primary 建立 seq_no、primary_term 与最终操作"], ["副本", "自己写本地 IndexWriter/Translog，不是拷 Primary 内存"], ["active shards", "wait_for_active_shards 是开始前检查，不是最终全副本成功保证"]],
      "Replica 是可恢复的数据副本和搜索容量，不是简单的备份按钮。",
      [["index.number_of_replicas", "1"], ["wait_for_active_shards", "all / 1 / N"], ["replication.type", "DOCUMENT default"]],
      "自动容错，并能分摊搜索。", "增加写网络、CPU、存储与确认成本。",
      "primaryResult = primary.applyAndTranslate(request)\nconcreteOp = primaryResult.indexOrDelete\nfor replica in replicationTargets:\n  send(replica, concreteOp, primaryTerm, seqNo)\n  await replica.applyLocally()", DOC.index,
      deep("wait_for_active_shards 只在执行前等待足够 shard copies active；执行过程中副本仍可能失败，响应中的 shard 结果必须被理解。", ["请求开始时 P2/R2 都 active。", "Primary 成功后 Replica 节点断开。", "响应可能报告 failed shard copy，集群随后恢复副本。"], [["响应", "检查 _shards.total/successful/failed"], ["分片", "GET _cat/shards/products-v3?v"], ["恢复", "GET _cat/recovery/products-v3?v"]], "wait_for_active_shards=all 能否证明请求结束时每份副本都写成功？", "不能把它当最终保证；它是执行前 active copies 门槛，仍需看实际执行结果和后续集群状态。")),

    slide("13 · REFRESH", "lucene", "深入一步：Refresh 内部做了什么？", "#D2048 怎样从 Buffer 进入 Searcher？", "前面只记住了“Search 要等 Refresh”。现在只放大一个 Shard：Refresh 将当前 Buffer 写成新的可搜索 Segment，再打开包含它的新 Searcher。", "flow",
      [["BUFFER", "#D2048 in memory", "尚未进入搜索视图"], ["WRITE SEGMENT", "create immutable files", "terms · postings · stored data"], ["OPEN SEARCHER", "publish view v42", "old queries can finish on v41"], ["SEARCH", "new query uses v42", "#D2048 becomes visible"]],
      [["refresh=false", "本次写入不主动刷新，交给自动节奏"], ["refresh=wait_for", "等待下一次刷新后再返回，通常更适合写后搜"], ["refresh=true", "立即刷新，容易制造许多小 Segment"]],
      "Refresh 的唯一主线是：Buffer → 新 Segment → 新 Searcher；它推进 Search 可见性，但不是 Flush。",
      [["index.refresh_interval", "自动刷新节奏"], ["refresh", "false / wait_for / true"], ["observe", "refresh + segments stats"]],
      "Searcher 读取不可变 Segment，查询视图稳定，写入可以分批发布。", "刷新过频会增加小 Segment、Searcher reopen 与后续 Merge 成本。",
      "refresh(shard):\n  segment = write_buffer_as_segment()\n  newView = oldSegments + segment\n  open_searcher(newView)\n  // not a full Lucene flush", DOC.refresh,
      deep("Refresh、Translog fsync 与 Flush 是三个不同动作：分别解决搜索可见、操作日志耐久、Lucene commit 与 Translog 生命周期。", ["团队把 refresh=true 配到每条写请求。", "Segment 数量快速上升。", "Searcher reopen 与 Merge 压力推高写入和搜索 P99。"], [["验证", "POST products-v3/_refresh"], ["统计", "GET products-v3/_stats/refresh,segments"], ["配置", "GET products-v3/_settings?include_defaults=true"]], "为什么 refresh=true 不适合作为所有写请求的默认值？", "它会打断批处理，为极少文档频繁创建小 Segment；通常用自动刷新，必须写后搜时优先考虑 wait_for。")),

    slide("14 · LUCENE SEGMENT", "lucene", "Segment 在磁盘上到底是什么？", "一个 Shard 是一个 Lucene Index，由多个不可变 Segment 组成。", "Refresh 产生的 Segment 含字段信息、term dictionary、postings、Doc Values、stored fields 等文件。Segment 发布后不原地修改。", "structure",
      [["SHARD P2", "Lucene index", "segment set"], ["_0", "older segment", ".tim .tip .doc .pos .dvd ..."], ["_1", "contains #D2048", "new searchable segment"], ["segments_N", "commit metadata", "which segments belong"]],
      [["不可变", "并发搜索可复用稳定文件与 OS Page Cache"], ["软删除", "OpenSearch 用隐藏 `__soft_deletes` Numeric DocValues 标记旧版本"], ["硬删除", ".liv 是 Lucene 的另一套 hard-delete liveDocs 结构；不要与 soft delete 混用"]],
      "Shard 是恢复与路由单元；Segment 是 Lucene 的读优化、不可变物理单元。",
      [["segment count", "持续观测趋势"], ["compound file", "Lucene 策略决定"], ["codec", "版本相关"]],
      "不可变性简化并发读、缓存与 crash safety。", "更新与删除产生旧版本，后台 merge 带来写放大。",
      "P2/\n ├─ _0.{tim,tip,doc,pos,fdt,...}\n ├─ _1.{dvd,dvm,...}        // DocValues\n ├─ _1_1.{dvd,dvm,fnm}      // DV update generation（示意）\n ├─ _1.liv                  // 仅 hard-delete liveDocs\n └─ segments_N", DOC.merge,
      deep("具体扩展名与 generation 取决于 Lucene codec 和版本；OpenSearch 的 `__soft_deletes` 是 Numeric DocValues 字段，物理上属于 DocValues 更新结构，不能简单画成 `.liv`。`.liv` 仍可能存在，但代表 Lucene hard delete。学习重点是职责边界，不要把某个版本的完整文件清单当稳定 API。", ["小 Segment 数量持续上涨。", "每次查询要跨更多 Segment。", "merge backlog 与磁盘 I/O 增大，搜索 P99 也上升。"], [["segments", "GET _cat/segments/products-v3?v"], ["stats", "GET products-v3/_stats/segments,merge,store"], ["磁盘", "同时观察 IOPS、throughput、await"]], "为什么不可变 Segment 反而有利于高并发搜索？", "搜索器可安全共享稳定文件和缓存，无需给每次更新加读写锁；代价被移到新 Segment、DocValues 更新与后台 merge。")),

    slide("15 · UPDATE / DELETE / MERGE", "lucene", "标记在哪里，何时真回收？", "标记删除到底写在哪里，什么时候才真的释放磁盘？", "OpenSearch 的现代 Engine 用 Lucene softUpdateDocument：旧版本被写入隐藏的 `__soft_deletes` Numeric DocValues 标记；DELETE 还会写 soft-deleted tombstone。Refresh 先改变 Searcher 视图，Merge 再按 retention 规则决定是否丢弃旧版本，最后等旧 Reader/PIT 引用释放才回收文件。", "merge-lifecycle",
      [["ENGINE", "softUpdateDocument", "mark old + add new/tombstone"], ["MARKER", "__soft_deletes=1", "hidden Numeric DocValues"], ["REFRESH", "new Searcher view", "business search filters old"], ["MERGE", "retention-aware copy", "may keep recovery history"], ["RECLAIM", "old refs → 0", "delete old segment files"]],
      [["标记在哪里", "逻辑上是隐藏 Numeric DocValues；先可在 IndexWriter update packet，应用后成为新的 DV generation"], ["Merge 丢什么", "只丢不再需要的旧版本；retention lease / safe commit 需要的历史会继续保留"], ["何时真释放", "新 Segment 完成且发布，旧 Searcher/PIT 引用归零，旧文件才可删除"]],
      "删除有三只时钟：API ACK、Refresh 后不可搜索、Merge + 引用释放后的磁盘回收；前两者绝不等于物理字节已经消失。",
      [["__soft_deletes", "hidden Numeric DocValues"], ["retention", "min retained seq_no / leases"], ["deletes_pct_allowed", "background merge threshold"], ["only_expunge_deletes", "force merge option"]],
      "不可变 Segment 让 Searcher 持有稳定快照，软删除又能保留 peer recovery 所需操作历史。", "高更新率会产生 DocValues 更新、tombstone、Merge 写放大与新旧 Segment 暂时并存的磁盘峰值。",
      "softUpdateDocument(uid, newOrTombstone, __soft_deletes=1)\nrefresh()  // new Searcher filters old version\nif old.seqNo < minRetainedSeqNo:\n  mergeOutput.omit(old)\npublish(newSegment)\nwhen oldReaders.refCount == 0: delete(oldFiles)", DOC.merge,
      deep("源码边界是：InternalEngine 为更新调用 softUpdateDocument；删除会构造 delete tombstone、给 tombstone 自身加入 `__soft_deletes`，再用 softUpdateDocument 标记匹配 uid 的旧版本。这个字段是 Numeric DocValues：操作可先存在 IndexWriter 的 buffered DocValues updates；应用到已有 Segment 后，通常生成新的 DocValues/FieldInfos generation，而不是修改 `_source` 或原 postings。SoftDeletesRetentionMergePolicy 在 merge 时把仍满足恢复/历史保留查询的 soft-deleted 文档当作需要携带的历史；只有越过保留边界的旧版本才从 merge 输出中消失。", ["高更新率让 deleted docs 与 DocValues update generations 持续增长。", "后台 Merge 先写 `_6.*`，此时 `_1/_2/_3` 仍存在，磁盘可能上升。", "长时间 PIT/scroll 或旧 Searcher 继续持有旧视图，旧 Segment 文件回收进一步延迟。"], [["删除统计", "GET products-v3/_stats/docs,segments,merge"], ["Segment", "GET _cat/segments/products-v3?v"], ["PIT/任务", "检查长 keep_alive 上下文与 force merge tasks"], ["Force merge", "只读/rollover 后再评估 only_expunge_deletes"]], "怎样判断一个旧版本已经‘真的删除’？", "业务上：新 Searcher 已过滤它；恢复历史上：它已越过 soft-delete retention 边界；物理上：Merge 新 Segment 已发布，而且引用旧 Segment 的 Searcher/PIT 已关闭，旧文件被删除。")),

    slide("16 · FLUSH + RECOVERY", "replica", "Flush 到底保存了什么，重启又重放什么？", "Flush 建立 Lucene commit 基线并滚动 Translog generation。", "默认 durability=request 的写先靠 Translog fsync 获得耐久性，不必每条写都做昂贵的 Lucene commit。自动 Flush 创建新 commit point，后续操作进入下一代 Translog；崩溃后先打开最后有效 commit，再重放它之后仍需恢复的操作。", "flow",
      [["BEFORE", "commit gen 5", "Segments + newer Translog ops"], ["FLUSH", "IndexWriter commit", "fsync metadata + roll generation"], ["RESTART", "open last valid commit", "replay newer operations"], ["CLEANUP", "old Translog generations", "when retention/recovery no longer needs them"]],
      [["Refresh ≠ Flush", "Refresh 打开新 Searcher；Flush 建立 commit point"], ["ACK 边界", "耐久性主要看 Translog durability/fsync，不等每次 Flush"], ["恢复长度", "commit 越旧，需要重放的日志尾巴通常越长"], ["手工 API", "系统自动 Flush；只在明确运维场景谨慎调用"]],
      "Translog 负责两次 commit 之间的耐久操作尾巴，Lucene commit 负责稳定重启基线；二者避免每次写都全量提交 Segment。",
      [["index.translog.durability", "request"], ["index.translog.flush_threshold_size", "512mb · 当前默认"], ["Flush API", "不要当成每次写后的 sync"]],
      "把昂贵 commit 批处理，同时让已 ACK 写可恢复。", "阈值过大可能拉长恢复；过小会增加 commit、I/O 与 generation 周转。",
      "flush():\n  indexWriter.commit()\n  fsyncCommitMetadata()\n  rollTranslogGeneration()\nrecover():\n  openLastValidCommit()\n  replay(translogOpsAfterCommit)", DOC.settings,
      deep("恢复来源取决于 shard 状态：本地 store 恢复、peer recovery、snapshot restore 的成本与网络路径不同。", ["节点重启后 P2 分片 initializing 很久。", "磁盘吞吐高且网络有大量传输。", "搜索容量下降，剩余副本负载上升。"], [["恢复", "GET _cat/recovery/products-v3?v&active_only=true"], ["分片", "GET _cluster/allocation/explain"], ["store", "GET products-v3/_stats/store,translog"]], "为什么频繁手动 flush 可能得不偿失？", "它增加 commit/fsync 与文件生命周期成本；系统已有自动策略，应根据恢复时间与 Translog 体量而不是焦虑式调用。")),

    slide("17 · REPLICATION TYPES", "replica", "Document Replication 与 Segment Replication 怎么选？", "一个复制操作，另一个复制已生成的 Segment。", "Document replication 让每个副本重复索引工作；Segment replication 由 Primary 生成 Segment，刷新时向 Replica 发布 checkpoint，Replica 拉取变化文件。", "compare",
      [["DOCUMENT", "send operations", "replicas analyze + index"], ["SEGMENT", "send segment changes", "primary owns indexing work"], ["REMOTE STORE", "another architecture", "版本与部署支持需单独验证"]],
      [["默认", "DOCUMENT"], ["Segment Replication", "降低 Replica CPU，但增加 refresh 时网络/文件复制特征"], ["约束", "replication.type 为静态 index setting"]],
      "复制模式改变 CPU、网络、刷新与故障恢复的成本分布，没有对所有 workload 都更好的答案。",
      [["index.replication.type", "DOCUMENT / SEGMENT"], ["refresh=true / wait_for", "Segment replication 只等待 Primary 可搜索"], ["network", "必须评估 segment copy 峰值"]],
      "Segment replication 可减少副本重复索引 CPU。", "Primary 压力、网络突发、refresh 可见性与运维模型改变。",
      "DOCUMENT: primary(op) → replicas(op)\nSEGMENT:  primary builds segment\n          publish checkpoint\n          replicas fetch changed files", DOC.segrep,
      deep("不要只看到“副本少做 CPU”就切换。Segment Replication 下，refresh=true/wait_for 只保证 Primary 搜索可见；Replica 仍按 checkpoint 推进。默认实时 GET 的强读取也会路由 Primary，realtime=false 才可分摊到 Replica。", ["大 refresh 产生新 Segment。", "多个 Replica 同时拉文件。", "网络突发影响恢复和其他流量。"], [["配置", "GET products-v3/_settings/index.replication.type"], ["段复制", "检查 segment replication stats/API（按版本）"], ["压测", "分别观察 indexing CPU、network、refresh lag"]], "Segment replication 为什么不等于‘零复制成本’？", "它只是把复制单位从文档操作换成 Segment 文件；仍有 checkpoint、文件传输、网络和可见性同步成本。")),

    slide("17A · VECTOR MAP", "vector", "向量搜索给 Document 增加了什么身体？", "同一商品同时拥有词项结构和语义坐标。", "文本字段继续生成倒排索引；描述文本还会经过 Embedding Model 变成固定维度向量，再为每个 Lucene Segment 构建 ANN 结构。Fetch 仍返回同一条 #D2048。", "atlas",
      [["TEXT", "product description", "human language"], ["EMBED", "[0.12, -0.07, ...]", "semantic coordinates"], ["ANN INDEX", "HNSW / IVF", "near-neighbor structure"], ["HYBRID", "BM25 + vector", "combine candidate rankings"]],
      [["Lexical", "匹配明确词项、型号、实体和稀有词"], ["Vector", "匹配语义接近，即使字面词不同"], ["共同点", "都按 Shard/Segment 执行，Coordinator 汇总 Top K 后 Fetch"]],
      "向量不是替代倒排索引的另一种 JSON；它是同一 Document 的第二套检索坐标系。",
      [["field", "description_vector"], ["dimension", "必须与模型输出一致"], ["search", "ANN / exact / hybrid"]],
      "补足同义表达、语义相似与跨语言召回。", "增加模型依赖、索引构建、内存/磁盘和相关性评估成本。",
      "#D2048._source.description\n  ├─ analyzer → terms → postings\n  └─ embedding model → vector[768] → ANN graph\nquery → lexical candidates + vector candidates → combine → fetch", DOC.vectorIndex,
      deep("稠密向量解决的是相似度候选召回，不自动保证事实正确、商品可售、权限允许或业务排序合理；这些仍需过滤、规则和重排。", ["语义上相似的停售商品被召回。", "ANN 分数很高。", "若没有 in_stock/tenant 过滤，结果业务上仍错误。"], [["Mapping", "GET products-v3/_mapping/field/description_vector"], ["样本", "保存 query、候选与人工 judgment"], ["结果", "同时记录 lexical/vector/hybrid rank"]], "为什么向量相似度高不等于业务相关性一定高？", "Embedding 只编码模型学习到的语义距离；库存、权限、价格、时效、偏好等业务约束并不自动包含其中。")),

    slide("17B · EMBEDDING", "vector", "文字怎样变成 768 个浮点数？", "不只是调用模型：输入模板、截断、模型版本与归一化共同定义坐标系。", "先把 name/description 按固定模板拼接和规范化，再由模型 Tokenizer、神经网络与 pooling 生成固定维度向量。向量可由应用/离线任务预生成，或由 OpenSearch ML/ingest 生成；写入前必须校验长度，查询端必须复用兼容的完整预处理契约。", "flow",
      [["SOURCE", "noise cancelling headphones", "normalized text"], ["MODEL", "embedding-v3", "tokenize + inference"], ["VECTOR", "float[768]", "fixed dimension"], ["WRITE", "description_vector", "alongside _source"]],
      [["外部生成", "模型平台独立、批量/缓存/重试与回填可控"], ["Ingest 生成", "接入统一，但模型延迟、限流和可用性进入写路径"], ["坐标系", "模型权重 + tokenizer + 输入拼接 + 截断 + pooling/normalize"], ["失败", "超长文本、模型超时、维度不匹配都要有明确处理"]],
      "索引向量和查询向量必须来自兼容坐标系；只要模型语义改变，就需要重新生成与回填。",
      [["model_id", "显式版本化"], ["dimension", "768（示例）"], ["input fields", "name + description"]],
      "把非结构化文本转成可计算的语义距离。", "推理延迟、成本、限流和模型升级成为新的系统边界。",
      "text = renderTemplate(name, description)\nmodelInput = normalizeAndTruncate(text, modelV3.contract)\nvector = embeddingModelV3.encode(modelInput)\nassert vector.length == mapping.dimension\nindex({ ...source, description_vector: vector })", DOC.vectorIndex,
      deep("模型升级不能只改查询端：新 query vector 与旧 document vectors 不在同一坐标系时，距离没有可靠含义。常见做法是新字段/新索引双写与离线回填。", ["查询服务升级到 embedding-v4。", "索引仍保存 v3 文档向量。", "服务无报错，但召回质量静默下降。"], [["版本", "在 index alias/field 名中体现 embedding 版本"], ["质量", "用固定 judgment set 比较 Recall@K/NDCG"], ["回填", "监控缺失向量与新旧版本占比"]], "为什么只比较向量维度相同还不够？", "两个模型即使都输出 768 维，也可能使用完全不同的坐标语义；必须是相同或明确兼容的模型与预处理。")),

    slide("17C · VECTOR MAPPING", "vector", "knn_vector Mapping 决定了哪些物理取舍？", "它决定距离语义、每个 Segment 的 ANN 文件和运行时内存形状。", "本例显式使用 dimension=768、cosine、Lucene HNSW 与 in_memory。每个向量字段在每个 Lucene Segment 建立相应向量值与 ANN 结构；on_disk、compression、method/engine 的组合和默认值随 OpenSearch 版本与引擎支持矩阵变化，不能混成一套通用默认。", "structure",
      [["FIELD", "knn_vector", "description_vector"], ["SPACE", "cosinesimil", "distance semantics"], ["METHOD", "HNSW", "graph ANN"], ["MODE", "in_memory / on_disk", "latency vs footprint"]],
      [["dimension", "必须与每条向量长度一致，越大存储与距离计算越贵"], ["space_type", "定义什么叫近，要匹配模型训练/归一化假设"], ["method + engine", "决定 HNSW/IVF 实现、过滤与压缩能力"], ["m / ef_construction", "增大通常换召回，但增加图大小、建图 CPU 与写延迟"], ["mode/compression", "in_memory 偏延迟；on_disk 偏内存，通常伴随压缩与 rescore"]],
      "Vector Mapping 不是类型声明而已，它把相关性、索引时间、内存、磁盘和召回率锁进同一个契约。",
      [["index.knn", "true"], ["dimension", "768"], ["space_type", "cosinesimil"], ["method", "lucene / hnsw"], ["mode", "in_memory（本例）"]],
      "可针对数据规模与硬件选择 ANN 实现。", "错误 dimension/space 一旦写入生产，修复通常要重建索引。",
      "description_vector: {\n  type: \"knn_vector\", dimension: 768,\n  space_type: \"cosinesimil\", mode: \"in_memory\",\n  method: { name: \"hnsw\", engine: \"lucene\",\n            parameters: { m: 16, ef_construction: 100 } }\n}", DOC.vectorIndex,
      deep("不要机械复制 m/ef_construction。更大的图连接和构建搜索深度通常提高召回，却增加构建 CPU、内存/磁盘与写入延迟，必须按数据分布压测。", ["将 ef_construction 大幅调高。", "离线 Recall 改善很小。", "Bulk 吞吐下降、refresh/merge 时间上升。"], [["Mapping", "GET products-v3/_mapping"], ["基线", "记录 Recall@K、QPS、P95/P99、build time"], ["容量", "按 vectors × dimension × data type + graph 估算"]], "为什么 space_type 不能在数据写完后随便改？", "已有向量结构按原距离语义构建和搜索；更改距离相当于改变邻近关系，通常需要重建结构。")),

    slide("17D · HNSW PHYSICAL", "vector", "HNSW 在 Segment 里长什么样？", "它是一张分层近邻图，不是按词排序的 Dictionary。", "每个 `knn_vector` 字段与 Lucene Segment 都有自己的向量索引。高层节点稀疏、负责大步跳转；底层连接密、负责在局部邻域逼近最近邻。", "structure",
      [["L2", "entry node", "sparse long jumps"], ["L1", "regional neighbors", "narrow the area"], ["L0", "dense neighborhood", "#D2048 ↔ nearby products"], ["SEGMENTS", "graph per field / segment", "query each then reduce"]],
      [["m", "每个节点的连接规模，影响图大小与召回"], ["ef_construction", "建图时保留的候选搜索宽度"], ["Segment", "Refresh/Merge 会创建新的向量结构，索引成本显著"]],
      "HNSW 用预先构建的近邻连边换取查询时少算大量无关向量。",
      [["m", "16（示例）"], ["ef_construction", "100（示例）"], ["unit", "per vector field × segment"]],
      "查询不必与每个向量做全量距离计算。", "图构建慢、结构占空间，近似路径可能漏掉真正最近邻。",
      "enter at top layer\nfor level from top to 0:\n  while exists closer neighbor:\n    move_to(closer_neighbor)\n  keep best candidates up to ef\nreturn nearest k candidates", DOC.vectorPerformance,
      deep("小 Segment 过多不仅伤害普通搜索，也会生成许多独立向量索引；一次 k-NN 查询需逐 Segment 搜索，再在 Shard 与 Coordinator 归并。", ["refresh_interval 很短且持续小批写。", "Segment/HNSW 数量快速增加。", "向量查询固定开销与 Merge 构建压力同时上升。"], [["Segments", "GET _cat/segments/products-v3?v"], ["Stats", "观察 refresh/merge 与 k-NN 指标"], ["实验", "对比不同 refresh/bulk 下 segment count 与 ANN P99"]], "为什么 HNSW 仍然是近似搜索？", "遍历只探索有限候选与邻接路径，不计算全集距离；图参数和搜索宽度决定速度与漏召回概率。")),

    slide("17E · ANN QUERY", "vector", "一次向量查询怎样找到 #D2048？", "Query 向量要跨过模型、Segment 图、Shard Top K 和全局 Reduce 四个边界。", "应用先用与索引兼容的模型生成 query vector。一次 Search 选择每个 Shard group 的一个 copy；该 Shard 搜索当前 Searcher 中每个 Segment 的 ANN 结构并合并 local candidates。Coordinator 汇总各 Shard 候选，保留全局 size 个 winner，最后 Fetch `_source`。", "flow",
      [["QUERY", "best headphones for flights", "natural language"], ["EMBED", "query_vector[768]", "same model space"], ["ANN", "graph traversal", "candidate neighbors"], ["REDUCE", "global Top K", "#D2048 → Fetch"]],
      [["k", "k-NN clause 的近邻候选目标；影响每 Shard 送出的候选规模"], ["size", "Coordinator 最终返回的全局 hits 数"], ["method_parameters", "ef_search/nprobes 是否可用及具体语义依 engine/version"], ["Lucene HNSW", "不要把 ef_search 当通用独立旋钮；当前实现会根据 k 处理搜索宽度"]],
      "向量 Search 仍遵循 Shard Query → Global Reduce → Fetch，只是 Shard 内的候选生成器从 postings 变成 ANN。",
      [["k", "100 shard candidates（课程示例）"], ["size", "10 global hits"], ["space", "cosine similarity"], ["engine", "lucene · 参数语义按版本核对"]],
      "语义相近文本无需共享完全相同词项。", "ANN 牺牲部分 Recall 换延迟；查询推理也占端到端预算。",
      "q = modelV3.encode(preprocess(userText))\nfor shardCopy in oneCopyPerShardGroup:\n  for segment in shardCopy.currentSearcher:\n    segmentCandidates += ANN.search(segment, q, k, methodParams)\n  shardTopK = topK(segmentCandidates, k)\nglobal = coordinator.topK(allShardTopK, size)\nfetch(global.docIDs)", DOC.vectorTechniques,
      deep("向量端到端延迟要拆成 query embedding、协调/排队、各 Segment ANN traversal、Shard reduce、global reduce 和 fetch。只看 OpenSearch took 会漏掉模型推理与客户端网络。查询宽度参数还依赖 engine/version：例如 Lucene HNSW 与 Faiss HNSW 对 ef_search 的处理并不应混讲。", ["OpenSearch took=70ms。", "Embedding 服务 P99=900ms。", "用户仍感到整次搜索接近 1 秒。"], [["模型", "记录 embedding latency / timeout / cache"], ["搜索", "记录 OpenSearch took、wall time、_shards"], ["结构", "记录 segments 与 engine/method"], ["质量", "同时观察 Recall@K，不只压低 latency"]], "把候选搜索宽度调低后 P99 下降，为什么不能立刻上线？", "它可能同时降低 Recall；且不同 engine 的参数含义不同。向量性能优化必须把质量指标与延迟、吞吐一起评估。")),

    slide("17F · VECTOR FILTERING", "vector", "向量相似之后，租户和库存过滤放在哪里？", "过滤时机决定是否还能稳定返回 k 个结果。", "Efficient k-NN filtering 在 ANN 遍历期间考虑过滤；Post-filter 先取近邻再删不合格项，限制严格时可能远少于 k；小候选集也可先过滤后精确计算。", "compare",
      [["EFFICIENT", "during ANN traversal", "aim to preserve k"], ["POST FILTER", "ANN first, filter later", "may return < k"], ["EXACT", "filter IDs, brute-force distance", "good for small subset"]],
      [["权限", "tenant/ACL 过滤必须保证不能越权，不能只靠 UI"], ["选择性", "过滤后剩余比例决定 exact/ANN 的成本"], ["引擎", "高效过滤支持范围随 Lucene/Faiss/HNSW/IVF 与版本变化"]],
      "向量过滤不是普通 DSL 位置问题，而是候选生成、召回率、k 完整性与安全边界。",
      [["filter", "放入 k-NN clause（高效过滤）"], ["post_filter", "只在可接受少于 k 时"], ["exact threshold", "按过滤后集合大小"]],
      "高效过滤可在满足结构化约束时保持 ANN 性能。", "极严格过滤、引擎差异与 exact fallback 会让延迟形状复杂。",
      "allowed = filter(tenant=17 && in_stock=true)\nif allowed.size is small: exact_distance(q, allowed)\nelse: ANN.search(q, filter=allowed)\n// post-filter may discard most of initial k", DOC.vectorFilter,
      deep("权限过滤应在 OpenSearch 查询边界强制执行，并验证所有查询形态都注入同一约束。ANN 后再在应用层过滤，可能先把越权文档取回。", ["ANN 先返回跨租户候选。", "应用收到 `_source` 后才过滤 tenant。", "敏感文档已经越过安全边界并可能进入日志/缓存。"], [["DSL", "确认 tenant/ACL filter 在 k-NN query 内"], ["测试", "为越权样本建立负向集成测试"], ["结果", "检查过滤严格时实际 hits 是否小于 k"]], "为什么 Post-filter 可能只返回 2 条，尽管 k=10？", "ANN 先选出的 10 个近邻中可能只有 2 个通过后置过滤；它不会自动回图中继续补足。")),

    slide("17G · HYBRID SEARCH", "vector", "BM25 与向量分数怎样合并？", "两个分数不在同一量纲，不能直接裸相加。", "Hybrid query 同时产生 lexical 与 semantic 候选。Search Pipeline 在 Query 和 Fetch 之间进行分数归一化组合，或使用 rank fusion/score ranker 按排名合并。", "flow",
      [["LEXICAL", "BM25 candidates", "exact terms · rare words"], ["SEMANTIC", "ANN candidates", "meaning similarity"], ["PIPELINE", "normalize or rank fusion", "combine evidence"], ["FETCH", "global winners", "#D2048"]],
      [["Normalization", "把不同 score scale 转为可组合尺度，再加权"], ["Rank fusion", "按排名位置融合，减少对绝对分数尺度依赖"], ["Evaluation", "权重没有通用最优值，必须用 query judgments 调优"]],
      "Hybrid Search 的价值不是“两个查询一起跑”，而是让精确词项与语义召回在可评估的规则下互补。",
      [["search_pipeline", "products-hybrid-v3"], ["combination", "weighted mean / rank fusion"], ["weights", "lexical 0.4 · semantic 0.6（示例）"]],
      "同时保留型号/品牌精确度与自然语言语义召回。", "两套候选、归一化和调参增加 CPU、延迟与解释复杂度。",
      "lex = BM25(queryText)\nsem  = ANN(embed(queryText))\n// Query phase results processor\ncombined = normalize_and_combine(lex, sem, weights)\n// or rank_fusion(lex.rank, sem.rank)\nfetch(topK(combined))", DOC.hybrid,
      deep("BM25 `_score=8` 与 cosine-derived `_score=.83` 的数值尺度没有直接可比性。权重应通过人工 judgment、点击数据和离线/在线实验确定。", ["团队直接执行 0.5*BM25 + 0.5*cosine。", "BM25 数值范围远大于向量分数。", "所谓 50/50 实际几乎全由 BM25 决定。"], [["Explain", "启用 hybrid score explanation（按版本能力）"], ["评估", "Recall@K、NDCG、MRR + 业务转化"], ["分群", "按 query 类型检查品牌词/长问句/无结果词"]], "Hybrid 的 0.5 / 0.5 为什么未必代表两种信号各占一半？", "若未先归一化，两种 score 的分布和尺度不同；即使归一化，真实贡献也取决于候选重叠和 query 分布。")),

    slide("17H · VECTOR LIFECYCLE", "vector", "更新一条向量，为什么会同时留下旧图和新图？", "向量随整个 Lucene Document 一起版本化，不在旧 Segment 里原地改数组。", "描述变化后需要重新生成 embedding，并索引完整新 Lucene Document。旧 Document（连同它的旧 vector）被 soft-delete 隐藏，但旧 Segment 与图节点字节仍在；Refresh 让新版本可见，Merge 按保留规则复制 live docs 并重建输出 Segment 的 ANN 结构，旧文件还要等 Reader/PIT 引用释放后才能删。", "blueprint",
      [["UPDATE", "new text → new vector", "old whole Document soft-deleted"], ["REFRESH", "publish new Segment/searcher", "new version becomes searchable"], ["MERGE", "copy retained live docs + rebuild ANN", "old vector bytes can eventually disappear"], ["READER RELEASE", "old Searcher/PIT closes", "old Segment files finally unlinked"], ["CAPACITY", "old + new + merge output × replicas", "needs headroom"]],
      [["float", "每维通常 4 bytes，尚未包含图连接与结构开销"], ["quantization", "显著减小内存/存储，但可能损失 Recall"], ["derived source", "新版本能力可避免向量重复进入 `_source`，需按部署版本验证"]],
      "Vector CRUD 延续普通 Document 的版本与 Segment 模型，但 embedding、图构建和重打分让写放大与容量成本更高。",
      [["mode", "in_memory / on_disk"], ["compression_level", "1x…32x（按支持范围）"], ["rescore", "oversample then full-precision"], ["dimension", "容量核心乘数"]],
      "量化与磁盘模式让更大向量库在有限内存下可运行。", "压缩提高近似误差，on-disk/rescore 增加 I/O 和尾延迟。",
      "update(doc):\n  newVector = modelV3.encode(doc.text)\n  markOldLuceneDocSoftDeleted()\n  indexFullNewLuceneDoc(doc, newVector)\nrefresh(): publishNewSegmentAndSearcher()\nmerge(): copyRetainedLiveDocs + rebuildANN()\nafterReadersRelease(): unlinkOldSegmentFiles()", DOC.vectorStorage,
      deep("容量不能只算 vectors × dimension × 4：还要加 HNSW links、Segment 重复、deleted vectors、Merge 临时空间、副本与 `_source`/Doc Values。", ["1 亿条 × 768 维按裸向量估算。", "忽略图、Replica 和 Merge 临时空间。", "上线后内存 breaker 与磁盘 watermark 同时出现。"], [["估算", "raw vector + graph + segment + replica + merge headroom"], ["指标", "k-NN memory/circuit breaker、segment/merge、disk"], ["冷启动", "观察 relocation/restart 后首次查询 P99"]], "为什么高频更新的向量索引尤其昂贵？", "每次更新都可能重新推理、写新向量、留下 deleted vector，并在 Merge 时重建 ANN 结构，CPU、I/O 和模型成本叠加。")),

    slide("18 · SEARCH REQUEST", "search", "现在发起一次 Search，会发生什么？", "搜索同样从协调节点开始，但会扇出到每个相关 shard group。", "查询 wireless noise cancelling，使用默认 query_then_fetch。Coordinator 解析请求、重写查询，选择每个 shard group 的一个副本并并行发出 Query phase。", "distributed-search",
      [["CLIENT", "_search", "query + filters + sort"], ["COORDINATOR", "rewrite + fan-out", "global request state"], ["P0/P1/P2", "one copy each", "parallel shard search"]],
      [["不是广播所有副本", "每个 shard group 通常选 Primary 或一个 Replica"], ["跨索引", "先解析 index/alias/data stream 与 routing"], ["返回", "Query phase 后还有 Fetch phase"]],
      "搜索是一场分布式 Top K：Shard 各找候选，Coordinator 做全局归并，再定向取文档。",
      [["search_type", "query_then_fetch"], ["pre_filter_shard_size", "可能触发 can_match"], ["preference", "可控制路由/一致性偏好"]],
      "Shard 并行带来横向扩展。", "Shard 数越多，扇出、队列和 reduce 开销越大。",
      "targets = resolve_shards(index, routing)\nfor shardGroup in targets:\n  copy = choose_primary_or_replica(shardGroup)\n  futures += query_phase(copy, rewrittenQuery)\nreduce(futures)", DOC.search,
      deep("Shard 数量是搜索放大器。大量很小 shards 会让每次请求承担更多网络、队列和固定开销。", ["一次 dashboard 查询命中 4000 shards。", "每 shard 工作很少，但协调/排队巨大。", "返回 shard limit 或 P99 飙升。"], [["请求", "响应 _shards.total"], ["shards", "GET _cat/shards?v&s=store:asc"], ["任务", "GET _tasks?actions=*search&detailed=true"]], "3 Primary + 1 Replica 的索引，一次普通 Search 会执行 6 个 shard 查询吗？", "通常是 3 个：每个 Primary shard group 选择一个可用 copy，而不是 Primary 与 Replica 都查。")),

    slide("19 · QUERY ANALYSIS", "search", "查询文本也要被 Analyzer 处理吗？", "Match query 先把用户输入变成 terms，再构造 Lucene query tree。", "Search Analyzer 将 wireless noise cancelling 处理成 tokens；Bool/filter、range 与 term 查询走不同语义。Query rewrite 会展开别名、前缀或多词结构。", "flow",
      [["INPUT", "Wireless noise cancelling", "user text"], ["ANALYZE", "search_analyzer", "wireless · noise · cancelling"], ["BUILD", "BooleanQuery", "MUST/SHOULD/FILTER"], ["REWRITE", "executable tree", "per shard context"]],
      [["match", "分析文本后匹配"], ["term", "不分析，要求精确 term"], ["filter", "不贡献 score，适合结构化约束"]],
      "先明确字段、Analyzer 与查询类型，再讨论相关性；DSL 长得像不代表执行语义相同。",
      [["operator", "OR / AND"], ["minimum_should_match", "业务召回控制"], ["lenient", "谨慎使用"]],
      "查询语义能贴近自然语言。", "Analyzer 不对称、通配符和多字段展开会造成意外召回或高 CPU。",
      "terms = searchAnalyzer.analyze(userText)\nquery = bool(should = terms.map(t => termQuery(\"name\", t)),\n             filter = [termQuery(\"in_stock\", true)])\nquery = rewrite(query)", DOC.search,
      deep("Wildcard、regexp、prefix 可能枚举大量 terms；leading wildcard 尤其危险。先确认是否能用 edge_ngram、keyword 子字段或业务前缀设计。", ["用户输入 *phone*。", "查询展开大量 term 并占满 search 线程。", "其他正常查询也排队超时。"], [["profile", "POST products-v3/_search { \"profile\": true, ... }"], ["analyze", "POST products-v3/_analyze"], ["慢日志", "检查 search slow log 与 query shape"]], "term 查询 name:text 为什么可能搜不到原始大小写字符串？", "term 不经过 Analyzer；索引中保存的可能是 lowercase 后的 terms，输入必须与实际 term 精确一致。")),

    slide("20 · SEARCH SHARD ROUTING", "search", "Primary 还是 Replica 来执行 Query？", "Adaptive Replica Selection 在可用 copies 中做选择。", "默认可参考历史响应时间、网络延迟和 search queue 等信号选择 shard copy。preference 可提高同类查询的路由稳定性。", "flow",
      [["P2", "queue 18 · slow", "candidate"], ["R2", "queue 1 · warm", "selected"], ["ARS", "latency + queue", "adaptive choice"]],
      [["副本", "既是容错，也是搜索并行容量"], ["cache locality", "完全随机可能降低 cache 命中"], ["preference", "可用 session/user key 获得稳定路由"]],
      "Replica Selection 是一个延迟、负载与缓存局部性的动态权衡。",
      [["cluster.routing.use_adaptive_replica_selection", "true"], ["preference", "_local / custom string 等"], ["routing", "限制目标 shards"]],
      "避开拥塞副本，改善尾延迟。", "历史信号有滞后；稳定 preference 可能形成热点。",
      "candidates = activeCopies(shardGroup)\ncopy = min_by(candidates,\n  predicted_latency + network + queue_penalty)\nquery(copy)", DOC.route,
      deep("Preference 与 routing 不是一个概念：routing 限制访问哪些 shard groups；preference 决定同一 shard group 更偏向哪个 copy/顺序。", ["同一 dashboard 每次随机打不同副本。", "request cache/query cache 命中下降。", "延迟抖动但 CPU 总量看似正常。"], [["节点", "GET _nodes/stats/indices/search,thread_pool"], ["请求", "对比固定 preference 与默认 ARS"], ["cache", "GET products-v3/_stats/request_cache,query_cache"]], "固定 preference 为什么可能既提升缓存又制造热点？", "相同 key 更常命中同一 copy，局部性变好；若 key 流量倾斜，也会长期压向少数 copies。")),

    slide("21 · CAN MATCH", "search", "所有 Shards 都值得执行完整 Query 吗？", "Can-match 预过滤可跳过确定不可能命中的 shards。", "当 shard 数或条件达到阈值时，Coordinator 可先发轻量 can_match。按日期范围/字段统计能证明无命中的 shard 不进入完整 Query phase。", "flow",
      [["P0", "range outside", "SKIP"], ["P1", "may match", "QUERY"], ["P2", "may match #D2048", "QUERY"]],
      [["收益", "减少昂贵 Query 扇出"], ["代价", "多一轮轻量请求与协调"], ["适用", "时间分片、强范围过滤、大量 shards"]],
      "最快的 shard query 是被安全证明“不可能命中”而跳过的那一个。",
      [["pre_filter_shard_size", "按请求/版本调整"], ["rewrite", "决定是否能快速证明 no-match"], ["routing", "更早减少 shard 范围"]],
      "对时间序列与跨很多索引的查询非常有效。", "目标 shard 本来很少时，预过滤可能只是额外往返。",
      "for shard in candidateShards:\n  if can_match(shard, rewrittenQuery):\n    queryTargets.add(shard)\n  else:\n    skip(shard)", DOC.search,
      deep("Can-match 不是缓存命中，也不保证精确算出 hit count；它只做安全的可能性判断。", ["跨 180 个日索引查最近 15 分钟。", "没有预过滤时对所有 shards 建立完整 query context。", "协调和 search queue 被固定开销拖慢。"], [["响应", "查看 _shards 与 profile"], ["设计", "时间字段和 index lifecycle 是否匹配查询窗口"], ["压测", "对比 pre_filter_shard_size 与 latency"]], "Can-match 返回 true 是否说明该 shard 一定有结果？", "不说明。true 只表示不能安全排除；完整 Query phase 后仍可能 0 hits。")),

    slide("22 · QUERY PHASE", "rank", "每个 Shard 在 Query phase 返回什么？", "先返回候选元数据，不返回完整 _source。", "每个 shard 在所有 Segment 上执行查询，用 collector 维护本地 Top K。返回内部 docID、score、sort values 与 shard identity，供 Coordinator 全局 reduce。", "structure",
      [["SEGMENTS", "_0 + _1 + _4", "searcher view"], ["COLLECT", "local priority queue", "size = from + size"], ["RETURN", "ScoreDoc[]", "docID · score · sort values"]],
      [["Top K", "每 shard 至少要提供全局归并所需候选"], ["from", "深分页会把每 shard 队列放大到 from+size"], ["total hits", "精确计数可能额外昂贵"]],
      "Query phase 回答“哪些候选最值得取回”；Fetch phase 才回答“它们的文档内容是什么”。",
      [["size", "10"], ["track_total_hits", "按业务精度需求"], ["terminate_after", "Shard 级早停语义需谨慎"]],
      "先传小型候选集合，减少跨节点数据量。", "大 K、精确总数、脚本评分会放大每 shard CPU/heap。",
      "heap = TopK(from + size)\nfor segment in searcher.segments:\n  for docID in execute(query, segment):\n    heap.collect(docID, score, sortValues)\nreturn heap.scoreDocs", DOC.search,
      deep("Profile API 有诊断开销，不应无界用于生产每个请求；它适合重现样本和解释 query tree 的时间分布。", ["size 从 20 改为 10000。", "每个 shard 的候选队列和网络响应放大。", "Coordinator reduce heap 突然升高。"], [["profile", "POST products-v3/_search { \"profile\": true, ... }"], ["task", "GET _tasks?actions=*search"], ["breaker", "GET _nodes/stats/breaker"]], "为什么 Query phase 不直接把每个命中的完整 JSON 都发回 Coordinator？", "绝大多数候选会在全局 reduce 被淘汰；提前取全文会浪费磁盘读取、反序列化和网络。")),

    slide("23 · BM25", "rank", "noise 重复 7 次，为什么还可能输给 #D2048？", "BM25 不只数词：它平衡命中词、稀有度、饱和词频与字段长度。", "本页用两个文档做方向性对比：#D2048 命中三个 query terms 且字段短；另一个长字段只重复 noise。TF 增益会饱和，缺少 wireless/cancelling 且字段更长，因此重复次数不会无限刷高分。默认 query_then_fetch 使用 Shard 本地统计；真实数值应使用 `_explain` 查看。", "formula",
      [["TF", "term frequency", "more, with saturation"], ["IDF", "inverse document frequency", "rare term weighs more"], ["NORM", "field length", "long fields discounted"], ["SCORE", "sum term contributions", "plus boosts"]],
      [["k1", "控制 term frequency 饱和速度，默认 1.2"], ["b", "控制长度归一化，默认 0.75"], ["query_then_fetch", "默认使用各 Shard 本地 term/doc stats"], ["dfs_query_then_fetch", "先收集全局统计，更一致但增加一次分布式阶段"]],
      "_score 是排序信号，不是稳定概率；先保证查询与字段正确，再调权重和 BM25 参数。",
      [["similarity", "BM25"], ["k1", "1.2"], ["b", "0.75"], ["debug", "GET /index/_explain/{id}"]],
      "通用、快速且对大多数文本检索是强基线。", "相关性与业务目标不完全一致，需要字段 boosts、函数或学习排序。",
      "score(t,d) ≈ IDF(t) ×\n  TF(t,d) × (k1+1) /\n  (TF(t,d) + k1×(1-b+b×len/avgLen))", DOC.bm25,
      deep("OpenSearch 3.0 的 BM25 实现变更为 Lucene native 后，绝对分数可能与旧版本不同。不要对 _score 写死跨版本阈值。", ["升级后排序大体相同，但 score 数字改变。", "业务使用 score > 2.5 作为硬规则。", "召回突然发生业务级断层。"], [["解释", "GET products-v3/_explain/sku-8821"], ["验证", "保留离线 judged query set"], ["升级", "比较 NDCG/Recall，不只比较绝对 score"]], "为什么同一文档在索引内容变化后 _score 也可能变化？", "BM25 使用文档频率、平均字段长度等集合统计；其他文档变化会改变这些统计量。")),

    slide("24 · CACHES", "rank", "三种常见缓存分别缓存什么？", "Page Cache、Query Cache、Request Cache 不在同一层。", "OS Page Cache 缓存 Segment 文件页；Query Cache 常缓存 filter 结果；Shard Request Cache 缓存符合条件的完整 shard-level response，refresh 后相应条目失效。", "compare",
      [["PAGE CACHE", "file pages", "OS · postings/doc values/_source"], ["QUERY CACHE", "filter bitsets/results", "segment/query eligibility"], ["REQUEST CACHE", "shard response", "often size=0 aggregations"]],
      [["热身", "重启/迁移后 Page Cache 冷会影响 P99"], ["资格", "缓存是否使用由查询形状和策略决定"], ["失效", "新 searcher/refresh 会改变可见 Segment"]],
      "不要说“缓存命中率”而不指明是哪一层、缓存的对象和失效边界。",
      [["index.requests.cache.enable", "true by default in many cases"], ["request_cache", "per-request override"], ["indices.queries.cache.size", "节点级"]],
      "重复过滤和聚合可显著降低 CPU/I/O。", "缓存占内存、会抖动，且高基数/一次性查询收益低。",
      "search():\n  if requestCache.eligible && hit: return response\n  postings = pageCache.read(segmentFiles)\n  filter = queryCache.getOrCompute(filterQuery)", DOC.cache,
      deep("缓存调优必须同时看命中、eviction、查询重复度和 refresh 频率。命中率低不一定是问题，一次性查询本来就不值得缓存。", ["Dashboard 每秒重复同一聚合。", "refresh_interval=1s 持续创建新 searcher。", "Request cache 频繁失效，CPU 周期性升高。"], [["cache", "GET products-v3/_stats/request_cache,query_cache"], ["segments", "GET products-v3/_stats/refresh,segments"], ["OS", "观察 page cache 与 major faults"]], "为什么把 refresh_interval 调得更短可能伤害缓存？", "可见 Segment 集合更频繁变化，依赖 searcher/segment 的缓存更常失效或需要重建。")),

    slide("25 · GLOBAL REDUCE", "rank", "三个 Shards 的 Top K 怎么变成全局 Top K？", "Coordinator 做归并排序与 Aggregation Reduce。", "P0/P1/P2 各返回本地候选。Coordinator 按 score 或 sort values 合并为全局前 10，并保留每个结果的 shard identity 与内部 docID。", "flow",
      [["P0", "local Top 10", "scores"], ["P1", "local Top 10", "scores"], ["P2", "#D2048 + local Top 10", "scores"], ["REDUCE", "global Top 10", "winner references"]],
      [["正确性", "全局前 K 可能来自任意 shard"], ["内存", "shardCount × (from+size) 候选在 Coordinator 汇总"], ["聚合", "bucket partials 也需要多阶段 reduce"]],
      "横向扩展把计算分散到 shards，却把全局排序与聚合压力集中到 Coordinator。",
      [["batched_reduce_size", "控制分批 reduce"], ["max_buckets", "聚合安全边界"], ["size", "越小越容易控制"]],
      "只汇总候选与 partial results，避免搬运全部命中。", "高 shard count、大 size 和高基数 buckets 仍可压垮协调节点。",
      "global = TopK(size)\nfor shardTopK in shardResponses:\n  global.merge(shardTopK)\nwinners = global.sorted()", DOC.search,
      deep("Coordinator 不一定是专用协调节点；客户端打到哪个节点，哪个节点就可能承担 reduce。因此入口负载均衡策略会影响热点。", ["大 terms aggregation 产生海量 partial buckets。", "Data shards 都快速返回。", "接入 Node 在 reduce 时触发 breaker。"], [["breaker", "GET _nodes/stats/breaker,jvm"], ["tasks", "GET _tasks?actions=*search&detailed=true"], ["query", "限制 size/shard_size 与 max_buckets"]], "为什么增加 Shard 数可能让单次搜索更慢？", "并行度增加的同时，扇出、固定开销、候选数量和 Coordinator reduce 都增加；超过合适粒度后放大成本占优。")),

    slide("26 · FETCH PHASE", "fetch", "Coordinator 什么时候拿到 _source？", "全局胜者确定后，只向持有胜者的 shards 发 Multi-Get 式 Fetch。", "P2 收到内部 docID 42，读取 stored _source 或 selected fields，执行 source filtering/highlight/script fields，再把文档片段送回 Coordinator 组装最终 hits。", "flow",
      [["WINNER", "P2 / docID 42", "#D2048"], ["FETCH", "read stored fields", "_source + highlight"], ["ASSEMBLE", "hit JSON", "_id · _score · fields"]],
      [["_source", "通常是压缩存储的原 JSON"], ["docvalue_fields", "可直接取列式值，避免解析整份 _source 的部分场景"], ["highlight", "可能重新分析并增加 CPU"]],
      "Query phase 找候选，Fetch phase 还原结果；这就是 query_then_fetch 的名字。",
      [["_source", "includes/excludes"], ["stored_fields", "按 mapping"], ["docvalue_fields", "结构化字段"]],
      "只为最终胜者做全文读取，节省 I/O 与网络。", "巨大 _source、脚本字段和高亮会让 Fetch 成为瓶颈。",
      "byShard = group(winners, winner.shard)\nfor shard, docIDs in byShard:\n  docs = fetch_stored_fields(shard, docIDs)\nreturn assemble_hits(winners, docs)", DOC.source,
      deep("即使 Query 很快，巨大 _source 也可能造成 Fetch P99 和网络响应体膨胀。列表页应只返回真正需要的字段。", ["每个商品 _source 包含 2MB 富文本。", "size=100 的列表查询全部取回。", "Fetch、网络和客户端 JSON 解析成为主耗时。"], [["profile", "对比 query 与 fetch/客户端总耗时"], ["响应", "测量 response bytes"], ["裁剪", "使用 _source includes 或 docvalue_fields"]], "为什么搜索列表只要 5 个字段，却仍可能读完整 _source？", "_source filtering 常在读取并解析压缩 _source 后筛选返回字段；若只需结构化值，可评估 docvalue_fields/stored fields。")),

    slide("27 · AGGREGATIONS", "fetch", "聚合为什么比普通 Top 10 更容易吃内存？", "每个 Shard 先产生 partial buckets，Coordinator 再合并。", "Terms、date_histogram 等聚合需要维护 bucket 状态。高基数字段、过大的 size/shard_size 与多层嵌套会让 partial results 爆炸。", "structure",
      [["P0", "brand buckets", "partial counts"], ["P1", "brand buckets", "partial counts"], ["P2", "brand buckets", "partial counts"], ["REDUCE", "global buckets", "merge + order"]],
      [["Doc Values", "聚合的常用列式来源"], ["shard_size", "为全局准确性多取局部候选 buckets"], ["composite", "适合分页遍历大量 buckets"]],
      "Aggregation 的规模由“文档数 × 基数 × 嵌套层级 × Shard 数”共同决定。",
      [["search.max_buckets", "安全上限"], ["size/shard_size", "精度与资源取舍"], ["execution_hint", "只在理解后调整"]],
      "分布式 partial reduce 支持大规模分析。", "精确 Top terms 与高基数多层聚合会消耗大量 heap/CPU。",
      "for shard in shards:\n  partial[shard] = aggregate(doc_values)\nresult = reduce_partials(partial)\nif buckets > max_buckets: fail_fast()", DOC.search,
      deep("Terms aggregation 的 doc_count_error 反映分布式截断带来的近似边界。盲目把 shard_size 调巨大可提高精度，却显著增加网络与 reduce。", ["在 user_id 上做 size=1,000,000 terms。", "每个 shard 建大量 buckets。", "Coordinator breaker 触发，整页 dashboard 失败。"], [["映射", "确认聚合字段为 keyword/numeric + doc_values"], ["响应", "查看 sum_other_doc_count / error"], ["替代", "需要全量遍历时考虑 composite pagination"]], "为什么每个 shard 只返回本地 Top 10，未必能得到准确全局 Top 10？", "某个全局热门 term 可能在每个 shard 都排第 11，却汇总后进入全局 Top；因此常需要更大的 shard_size 或接受误差。")),

    slide("28 · DEEP PAGINATION", "fetch", "为什么 from=1,000,000 很危险？", "每个 Shard 都要维护并返回 from + size 个候选。", "深分页会在所有 shards 上浪费前面结果。稳定遍历应使用 PIT 固定搜索视图，再用 search_after 携带上一页排序值。", "compare",
      [["FROM/SIZE", "skip N", "each shard keeps N+size"], ["SEARCH_AFTER", "resume after sort values", "stateless cursor-like"], ["PIT", "stable segment view", "consistent pagination window"]],
      [["排序", "必须稳定且有唯一 tie-breaker"], ["PIT", "占用旧 Segment 视图，必须设置合理 keep_alive"], ["scroll", "批处理场景可用，但不是交互式分页首选"]],
      "深分页不是 UI 小问题，它会在每个 Shard 和 Coordinator 上成倍放大状态。",
      [["index.max_result_window", "默认常为 10000"], ["pit.keep_alive", "按用户翻页时间"], ["sort", "price, _id-like tiebreaker"]],
      "PIT + search_after 能近似常量成本前进。", "需要管理 PIT 生命周期与稳定排序，不支持随意跳第 N 页。",
      "pit = open_point_in_time(index)\npage = search(pit, sort=[price, tieBreaker])\nnext = page.last.sort\npage2 = search(pit, search_after=next)", DOC.search,
      deep("PIT 保持旧 Segment 可被引用，长 keep_alive 与大量并发 PIT 会延迟 Segment 删除和磁盘回收。", ["导出任务创建大量 PIT，keep_alive=24h。", "后台 merge 产生新 Segment。", "旧 Segment 因 PIT 仍被引用，磁盘使用持续上升。"], [["任务", "清理不再使用的 PIT/scroll contexts"], ["segments", "观察旧 Segment 与磁盘增长"], ["分页", "记录 sort values 而不是页码 offset"]], "search_after 为什么通常要配 PIT？", "没有固定视图时，页间 refresh/update 会改变排序集合，可能导致重复或漏项；PIT 固定一个一致的 Segment 视图。")),

    slide("29 · PARTIAL RESULTS", "fetch", "Search 返回 200 就是完整正确吗？", "必须检查 timed_out 与 _shards。", "部分 shards 超时或失败时，行为受 search.default_allow_partial_results 等设置影响。允许 partial 时可能返回部分 hits；禁止则整个请求失败。", "compare",
      [["COMPLETE", "3/3 shards", "full result"], ["PARTIAL", "2/3 shards", "HTTP may still be 200"], ["STRICT", "fail request", "no silent partial"]],
      [["用户体验", "部分结果可能比错误页更可用"], ["正确性", "风控、报表与对账通常不能静默接受"], ["客户端", "检查 timed_out、_shards.failed 与 failures"]],
      "“可用”与“完整”是两种 SLA；客户端必须显式知道自己接受哪一种。",
      [["search.default_allow_partial_results", "true/false"], ["allow_partial_search_results", "request override"], ["timeout", "并不总能中断所有底层工作"]],
      "面向探索的搜索可在局部故障时降级。", "静默 partial 会产生看似可信但不完整的业务答案。",
      "response = search()\nif response.timed_out || response._shards.failed > 0:\n  if correctness_required: reject(response)\n  else: show_degraded_badge(response)", DOC.searchSettings,
      deep("HTTP status 只表达请求层结果，分布式执行细节在响应体。监控也必须统计 shard failures，而不是只统计 5xx。", ["P2 query phase 因 breaker 失败。", "P0/P1 正常返回 200 + partial hits。", "应用把少 1/3 的销量报表当完整数据。"], [["响应", "检查 timed_out、_shards.failed、failures[]"], ["日志", "按 shard/node 关联异常"], ["产品", "为 partial 结果显示明确降级状态"]], "哪些业务通常不应默认接受 partial results？", "对账、计费、风控、合规报表等需要完整集合或明确失败的场景；探索式搜索可以按产品策略降级。")),

    slide("30 · HIGH AVAILABILITY", "replica", "一个节点宕机，#D2048 怎么活下来？", "Shard copy、Primary term 与恢复流程共同工作。", "若 P2 Primary 所在 Node-2 宕机，合格 Replica 可被提升为新 Primary。Cluster state 发布新路由，客户端/协调节点改发新 Primary，缺失副本随后恢复。", "blueprint",
      [["FAIL", "Node-2 / P2 Primary", "unavailable"], ["PROMOTE", "Node-1 / R2 → P2", "new primary term"], ["REROUTE", "cluster state update", "requests retry"], ["RECOVER", "allocate new R2", "peer recovery"]],
      [["Replica", "必须已经 active 且数据历史合格"], ["Primary term", "隔离旧 Primary，防止过期写重新混入"], ["恢复", "先恢复可用性，再恢复冗余度"]],
      "高可用不是“有副本”四个字，而是检测、提升、隔离旧主、更新路由和补齐副本的完整状态机。",
      [["number_of_replicas", "至少 1 才有节点级冗余"], ["allocation awareness", "跨 AZ 放置"], ["disk watermarks", "影响重新分配"]],
      "自动故障转移减少停机。", "更多副本与跨域流量提高成本；错误放置会让副本同时失效。",
      "on_primary_failure(P2):\n  candidate = choose_in_sync_replica(P2)\n  promote(candidate, newPrimaryTerm)\n  publish_cluster_state()\n  reject_stale_primary_writes()\n  recover_missing_replica()", DOC.settings,
      deep("有 Replica 但与 Primary 在同一故障域，无法抵御机架/AZ 级故障。Allocation awareness/forced awareness 决定可用性与冗余的取舍。", ["P2 与 R2 都落在 AZ-a。", "AZ-a 网络隔离。", "RF=2 仍同时失去全部 copies。"], [["分布", "GET _cat/shards/products-v3?v&h=index,shard,prirep,state,node"], ["意识", "GET _cluster/settings?include_defaults=true"], ["解释", "GET _cluster/allocation/explain"]], "为什么旧 Primary 恢复后不能直接继续接受写入？", "它可能持有过期历史；Primary term/集群状态用于 fencing，必须先按当前 Primary 恢复成合格副本。")),

    slide("30A · CONTROL PLANE", "replica", "谁有权把 R2 提升为新 Primary？", "数据副本解决保存问题，多数派解决决策问题。", "Cluster Manager eligible nodes 维护投票配置。只有获得多数派的一侧才能选出 Cluster Manager，并提交新的 cluster state；数据节点收到新路由后，才把后续写入发给被提升的 P2。", "flow",
      [["DETECT", "Node-2 unavailable", "P2 Primary lost"], ["QUORUM", "2 of 3 eligible nodes", "one authoritative side"], ["DECIDE", "promote in-sync R2", "new primary term"], ["PUBLISH", "new cluster state", "all nodes reroute"]],
      [["控制面", "决定节点、索引、Shard 路由与 Primary 身份；不代替 Data Node 执行每条搜索"], ["多数派", "3 个 eligible nodes 可容忍 1 个失联；只剩 1 个不能继续形成新决策"], ["防脑裂", "网络分区时只允许多数派侧推进 cluster state，避免两边都自认有效"]],
      "Replica 让数据有第二份；多数派让整个集群只有一个被承认的拓扑真相。两者共同构成高可用。",
      [["eligible nodes", "3"], ["voting quorum", "2 / 3"], ["data path", "Client → Data Node，非每次都经过 Cluster Manager"]],
      "多数派与 term 把故障后的新主身份变成可证明的单一决策。", "失去多数派时宁可暂停元数据决策，也不冒双主与错误路由风险。",
      "if votes >= majority:\n  manager = elect_one()\n  state = promote(in_sync_R2, new_primary_term)\n  commit_and_publish(state)\nelse:\n  refuse_cluster_state_change()", DOC.voting,
      deep("Cluster Manager 负责控制面元数据，不在每条 CRUD/Search 的数据路径上。把它与协调节点混为一谈，会误判容量和故障影响。", ["三个 eligible nodes 被网络切成 2 + 1。", "2 节点一侧能形成多数派并继续管理路由。", "孤立的 1 节点一侧不能自行发布冲突状态。"], [["健康", "GET _cluster/health"], ["状态", "GET _cluster/state/master_node,routing_table"], ["节点角色", "GET _cat/nodes?v&h=name,node.role,master"], ["故障演练", "验证 3→2 与 3→1 时的行为"]], "为什么有 R2 Replica，集群仍可能因控制面失去多数派而受限？", "数据副本只说明字节仍在；谁是 Primary、Shard 放哪里、哪些节点属于当前集群，仍需要唯一且多数派认可的 cluster state。")),

    slide("31 · CONSISTENCY", "replica", "OpenSearch 的一致性该怎么描述？", "不要只说‘最终一致’；要分身份、并发、复制与搜索可见性。", "Primary 串行化同一 shard 的写操作，seq_no + primary_term 可做乐观并发；Replica 提供冗余；Search 通过 refresh 获得近实时视图。", "structure",
      [["IDENTITY", "_id + routing", "which shard/document"], ["CONCURRENCY", "seq_no + primary_term", "reject stale update"], ["REPLICATION", "Primary → replicas", "ack/failure semantics"], ["VISIBILITY", "refresh / searcher", "NRT Search"]],
      [["GET", "可实时读取最新版本"], ["Search", "读已 refresh 的 snapshot"], ["CAS", "if_seq_no + if_primary_term 防止丢失更新"]],
      "正确回答一致性问题，必须先问：对哪种读、哪个 shard、什么故障和哪个时间边界？",
      [["if_seq_no", "expected sequence"], ["if_primary_term", "expected term"], ["refresh", "wait_for for write-then-search"]],
      "通过明确 token 实现乐观并发，避免全局锁。", "跨文档/跨 shard 不自动获得数据库式事务。",
      "current = GET doc\nPUT doc?if_seq_no=current.seqNo\n       &if_primary_term=current.primaryTerm\nif conflict: read_latest_and_reconcile()", DOC.index,
      deep("version conflict 不是需要无脑重试的基础设施错误；它表示业务基于旧版本修改，必须重新读取并决定合并策略。", ["库存服务 A/B 同时读取 stock=10。", "A 写 9 成功，B 仍写 8。", "没有 CAS 时 A 的变化被覆盖；有 CAS 时 B 得到 409。"], [["响应", "记录 409 version_conflict_engine_exception"], ["文档", "查看 _seq_no 与 _primary_term"], ["策略", "区分可交换增量与覆盖更新"]], "refresh=wait_for 能提供跨多文档事务一致性吗？", "不能。它只等待相关 refresh 可见性，不把多个文档或 shards 的操作变成原子事务。")),

    slide("32 · PERFORMANCE", "rank", "OpenSearch 为什么快，又为什么会突然慢？", "读写性能来自一组互相牵制的设计。", "倒排索引和 HNSW 降低候选搜索范围；不可变 Segment 与 OS Page Cache 支持并发读；Batch/refresh/merge 摊薄写入；Shards 并行扩展；Doc Values 加速列式操作。", "blueprint",
      [["LEXICAL", "inverted + BKD + doc values", "purpose-built structures"], ["VECTOR", "HNSW / IVF + quantization", "ANN candidates"], ["I/O", "immutable files + page cache", "hot reads"], ["BATCH", "refresh + segment merge", "amortized writes"], ["PARALLEL", "shards + replicas", "horizontal work"]],
      [["写入", "更长 refresh / 更大 batch 提升吞吐但延迟可见；向量还要支付 embedding 与建图"], ["搜索", "更多 shards 提升并行，也放大 lexical/vector 候选与 reduce"], ["缓存", "热 Segment/ANN 很快，迁移或重启后的冷启动会抖动"]],
      "OpenSearch 的高性能不是一个 secret switch，而是数据结构、批处理、缓存与并行共同构成的成本模型。",
      [["refresh_interval", "可见性 vs segment/ANN churn"], ["shards", "并行 vs fan-out"], ["vector mode", "recall/latency vs memory/I/O"], ["bulk", "throughput vs queue/heap"]],
      "可针对全文、向量、过滤、范围、排序与聚合分别优化。", "空间换时间、写放大、模型推理、缓存冷启动和协调成本都要偿还。",
      "latency ≈ embed + queue + lexical/ANN + reduce + fetch\nwrite_cost ≈ analyze + embed + graph + replicas + refresh + merge\ncapacity = min(CPU, heap, native/vector memory, disk, network, hottest_shard)", DOC.search,
      deep("先用 workload 分解瓶颈，再调参数。只盯 JVM CPU 会漏掉模型推理、Page Cache、native/vector memory、merge I/O、hot shard、协调节点 heap 和客户端响应体。", ["扩容后 shards 迁移。", "新节点 Page Cache/ANN 冷且 recovery 占带宽。", "集群 CPU 不高，但混合搜索 P99 暂时变差。"], [["写", "indexing/refresh/merge/translog + embedding stats"], ["读", "query/fetch/cache + ANN latency/Recall"], ["系统", "CPU、heap/GC、vector memory、page cache、disk、network"], ["拓扑", "hottest shard 与 coordinator 分布"]], "为什么单纯增加 Nodes 不一定让热点索引更快？", "如果 Primary 数、routing 热点、向量图分布或协调入口不变，工作仍集中在少数 shard/node；扩容只增加潜在容量。")),

    slide("33 · PRODUCTION DIAGNOSIS", "fetch", "线上慢了，怎样沿这条链定位？", "先分阶段，再找最窄的物理边界。", "从客户端与协调层开始，看写还是搜；再拆 queue、shard、Lucene、磁盘/缓存与网络。把 P50/P99、吞吐和错误率放在同一时间轴。", "blueprint",
      [["CLIENT/MODEL", "429 / embedding / payload", "request shape"], ["COORDINATOR", "queue / breaker / hybrid reduce", "entry hotspot"], ["SHARD", "hot routing / recovery", "one slow copy"], ["LUCENE/VECTOR", "segments / ANN / merge / refresh", "engine work"], ["SYSTEM", "heap / vector memory / disk / net", "physical limit"]],
      [["第一问", "所有请求慢，还是某 index/shard/query shape 慢？"], ["第二问", "时间花在 queue、query、fetch、merge 还是 recovery？"], ["第三问", "配置变化、部署、迁移、流量与数据分布谁先发生？"]],
      "不要从参数列表开始排障；从请求的当前边界和可证伪假设开始。",
      [["slow logs", "只记录超过阈值的 shard query/fetch"], ["profile", "样本诊断，不全量开启"], ["tasks", "长任务与取消"], ["stats", "趋势优于单点"]],
      "因果链让性能、高可用和一致性问题共享同一张地图。", "指标很多，必须以阶段假设控制搜索空间。",
      "if 429: inspect queues + pressure\nif semantic_slow: embedding + ANN + cold graph\nif hybrid_bad: inspect lexical/vector candidates + normalization\nif fetch_slow: _source bytes + storage\nif write_slow: bulk + translog + embedding + graph + merge", DOC.search,
      deep("Slow log 是 shard 级耗时，不等于客户端端到端耗时；它看不到协调排队、全局 reduce、网络与客户端解析的全部成本。", ["客户端 P99=4s。", "Shard slow log 都只有 200ms。", "真正耗时在协调节点排队和大响应体网络传输。"], [["客户端", "记录 took、wall time、response bytes、_shards"], ["节点", "GET _nodes/hot_threads"], ["任务", "GET _tasks?detailed=true"], ["关联", "用 opaque id / trace id 串联"]], "为什么单次 hot_threads 截图不足以证明根因？", "它只是采样瞬间；需要与请求、指标、GC、I/O、部署和重复采样在同一时间轴验证。")),

    slide("34 · FINAL CHECK", "fetch", "现在，你能解释 #D2048 的一生了吗？", "用十二个因果问题验收，而不是背 API。", "从 CRUD 的身份与版本语义，到倒排索引和 HNSW 两套候选结构，再到 Replica、Hybrid Reduce 与 Fetch；每一步都能落回 Shard、Segment 和资源成本。", "final",
      [["1", "Create 会覆盖吗？", "op_type / CAS"], ["2", "GET 与 Search 差在哪？", "realtime / NRT"], ["3", "Update 为何重写？", "immutable Lucene doc"], ["4", "Delete 后空间去哪？", "tombstone / merge"], ["5", "为什么只去 P2？", "routing"], ["6", "JSON 怎样变成 Terms？", "analyzer"], ["7", "文字怎样变成向量？", "embedding model"], ["8", "HNSW 为什么近似？", "bounded graph traversal"], ["9", "Replica 何时接管？", "primary term"], ["10", "BM25 与 ANN 怎么合？", "normalization / rank fusion"], ["11", "为什么先 Query 后 Fetch？", "only fetch winners"], ["12", "如何定位 P99？", "stage + boundary"]],
      [["CRUD 心智模型", "identity → one Shard → versioned operation → refresh/merge"], ["检索心智模型", "Terms/Postings + Vector/ANN → Shard candidates → Hybrid Reduce → Fetch"], ["设计心智模型", "每种结构都在质量、延迟、吞吐、成本、可用性和一致性之间交换"]],
      "真正掌握 OpenSearch，是能从一条请求推导出它占用的 CPU、heap、网络、文件、缓存与故障边界。",
      [["Document", "#D2048"], ["Primary", "P2（示意）"], ["Search", "query_then_fetch"], ["Result", "explainable hit"]],
      "形成可迁移的检索系统心智模型。", "生产配置仍必须用真实数据、查询分布与故障演练验证。",
      "CRUD → route(P2) → versioned op → translog/replicas\nlexical → analyze → postings/BM25\nvector → embed → HNSW/ANN\nrefresh(segment) → shard candidates → hybrid reduce\n→ fetch #D2048._source → client", DOC.index,
      deep("掌握后的下一步不是再背参数，而是建立一套包含 lexical、vector 与业务规则的相关性评估集，并做节点、Shard、模型和查询管线的联合故障演练。", ["只记住 REST DSL。", "遇到语义搜索慢就盲调 heap 或 ef。", "忽略 embedding、Shard、Segment 和 request shape，优化无法复现。"], [["练习", "自己画出 CRUD、关键词和向量三条时序"], ["实验", "改变 refresh_interval 观察 Segment/HNSW 数量"], ["故障", "停节点并更换模型版本，分别观察恢复与质量"], ["相关性", "用 _analyze、_explain 和 judgment set 解释结果"]], "如果只能记住一句话，应该是什么？", "OpenSearch 为同一 Document 预构建身份、词项、列式和向量结构，再让 Shard 并行产候选、全局组合并只取回胜者；性能与正确性都来自这些边界。"))
  ];

  // 学习顺序刻意按“一条流程讲完，再进入下一条”组织。内容定义仍按主题维护，
  // 这里集中声明课程叙事，避免 Create、Search、Vector 互相穿插。
  const COURSE_SEQUENCE = [
    ["00 · START HERE", "START · JSON"],
    ["01 · FOUR LEVELS", "START · PHYSICAL LEVELS"],
    ["02 · REQUEST ANATOMY", "START · REQUEST + ROUTING"],
    ["02Z · INDEX SETUP", "START · INDEX CONTRACT"],

    ["02A · CREATE", "CREATE 01 · OVERVIEW"],
    ["02A1 · CREATE VS INDEX", "CREATE 02 · CREATE VS REPLACE"],
    ["04 · COORDINATING NODE", "CREATE 03 · COORDINATOR"],
    ["04A · CLIENT ENTRY", "CREATE 04 · CLIENT ENDPOINTS"],
    ["05 · INGEST PIPELINE", "CREATE 05 · INGEST EXAMPLE"],
    ["07 · SHARD ROUTING", "CREATE 06 · ROUTING"],
    ["06 · MAPPING", "CREATE 07 · MAPPING"],
    ["08 · ANALYZER", "CREATE 08 · ANALYZER"],
    ["09 · INVERTED INDEX", "CREATE 09 · INVERTED INDEX"],
    ["10 · FOUR INDEX VIEWS", "CREATE 10 · INDEX STRUCTURES"],
    ["10A · LIVE VERSION MAP", "CREATE 11 · VERSION MAP"],
    ["11 · BUFFER + TRANSLOG", "CREATE 12 · WRITE ORDER"],
    ["12 · DOCUMENT REPLICATION", "CREATE 13 · REPLICA"],
    ["13 · REFRESH", "CREATE 14 · REFRESH"],
    ["14 · LUCENE SEGMENT", "CREATE 15 · SEGMENT FILES"],
    ["16 · FLUSH + RECOVERY", "CREATE 16 · FLUSH + RECOVERY"],
    ["17 · REPLICATION TYPES", "CREATE 17 · REPLICATION OPTIONS"],
    ["03 · INDEX OR BULK", "CREATE 18 · BULK"],

    ["02B · GET", "READ 01 · REALTIME GET"],
    ["02C · SEARCH VISIBILITY", "READ 02 · NRT SEARCH"],
    ["02D · UPDATE", "UPDATE 01 · NEW VERSION"],
    ["02D1 · UPDATE TRANSLATION", "UPDATE 02 · PRIMARY DECIDES"],
    ["02E · DELETE", "DELETE 01 · LIFECYCLE"],
    ["02E1 · THREE DELETE RECORDS", "DELETE 02 · THREE RECORDS"],

    ["18 · SEARCH REQUEST", "SEARCH 01 · SCATTER / GATHER"],
    ["19 · QUERY ANALYSIS", "SEARCH 02 · QUERY ANALYSIS"],
    ["20 · SEARCH SHARD ROUTING", "SEARCH 03 · COPY SELECTION"],
    ["21 · CAN MATCH", "SEARCH 04 · CAN MATCH"],
    ["22 · QUERY PHASE", "SEARCH 05 · LOCAL TOP K"],
    ["23 · BM25", "SEARCH 06 · BM25"],
    ["24 · CACHES", "SEARCH 07 · CACHES"],
    ["25 · GLOBAL REDUCE", "SEARCH 08 · GLOBAL REDUCE"],
    ["26 · FETCH PHASE", "SEARCH 09 · FETCH"],
    ["27 · AGGREGATIONS", "SEARCH 10 · AGGREGATIONS"],
    ["28 · DEEP PAGINATION", "SEARCH 11 · PAGINATION"],
    ["29 · PARTIAL RESULTS", "SEARCH 12 · PARTIAL RESULTS"],

    ["17A · VECTOR MAP", "VECTOR 01 · MAP"],
    ["17B · EMBEDDING", "VECTOR 02 · EMBEDDING"],
    ["17C · VECTOR MAPPING", "VECTOR 03 · MAPPING"],
    ["17D · HNSW PHYSICAL", "VECTOR 04 · HNSW"],
    ["17E · ANN QUERY", "VECTOR 05 · ANN QUERY"],
    ["17F · VECTOR FILTERING", "VECTOR 06 · FILTERING"],
    ["17G · HYBRID SEARCH", "VECTOR 07 · HYBRID"],
    ["17H · VECTOR LIFECYCLE", "VECTOR 08 · LIFECYCLE"],

    ["15 · UPDATE / DELETE / MERGE", "PRINCIPLE 01 · MERGE"],
    ["30 · HIGH AVAILABILITY", "PRINCIPLE 02 · HIGH AVAILABILITY"],
    ["30A · CONTROL PLANE", "PRINCIPLE 03 · CONTROL PLANE"],
    ["31 · CONSISTENCY", "PRINCIPLE 04 · CONSISTENCY"],
    ["32 · PERFORMANCE", "PRINCIPLE 05 · PERFORMANCE"],
    ["33 · PRODUCTION DIAGNOSIS", "PRINCIPLE 06 · DIAGNOSIS"],
    ["34 · FINAL CHECK", "FINAL · CHECK"]
  ];

  const courseBySection = new Map(window.OPENSEARCH_COURSE.map(item => [item.section, item]));
  window.OPENSEARCH_COURSE = COURSE_SEQUENCE.map(([originalSection, displaySection]) => {
    const item = courseBySection.get(originalSection);
    if (!item) throw new Error(`Missing course section: ${originalSection}`);
    return { ...item, section: displaySection };
  });
})();
