(() => {
  "use strict";
  const DOC={
    home:"https://www.postgresql.org/docs/18/",arch:"https://www.postgresql.org/docs/18/tutorial-arch.html",protocol:"https://www.postgresql.org/docs/18/protocol.html",flow:"https://www.postgresql.org/docs/18/protocol-flow.html",query:"https://www.postgresql.org/docs/18/query-path.html",explain:"https://www.postgresql.org/docs/18/using-explain.html",indexes:"https://www.postgresql.org/docs/18/indexes-types.html",mvcc:"https://www.postgresql.org/docs/18/mvcc.html",isolation:"https://www.postgresql.org/docs/18/transaction-iso.html",locks:"https://www.postgresql.org/docs/18/explicit-locking.html",page:"https://www.postgresql.org/docs/18/storage-page-layout.html",hot:"https://www.postgresql.org/docs/18/storage-hot.html",files:"https://www.postgresql.org/docs/18/storage-file-layout.html",fsm:"https://www.postgresql.org/docs/18/storage-fsm.html",vm:"https://www.postgresql.org/docs/18/storage-vm.html",toast:"https://www.postgresql.org/docs/18/storage-toast.html",wal:"https://www.postgresql.org/docs/18/wal-intro.html",walcfg:"https://www.postgresql.org/docs/18/wal-configuration.html",vacuum:"https://www.postgresql.org/docs/18/routine-vacuuming.html",repl:"https://www.postgresql.org/docs/18/runtime-config-replication.html",standby:"https://www.postgresql.org/docs/18/hot-standby.html",logical:"https://www.postgresql.org/docs/18/logical-replication-architecture.html",partition:"https://www.postgresql.org/docs/18/ddl-partitioning.html",monitor:"https://www.postgresql.org/docs/18/monitoring-stats.html"
  };
  const STAGE={start:"先建立整张地图",connection:"连接与 Backend",query:"SQL 如何变成执行计划",insert:"INSERT 写入主线",read:"SELECT 读取主线",mvcc:"UPDATE、DELETE 与并发",maintenance:"VACUUM 与物理存储",durability:"WAL、Checkpoint 与恢复",replication:"复制与高可用",ops:"扩展与生产诊断"};
  const INSPECT={
    start:[["版本","SELECT version()"],["目录","SHOW data_directory"],["主角","SELECT * FROM orders WHERE id='A1024'"]],
    connection:[["连接","pg_stat_activity"],["上限","SHOW max_connections"],["认证","pg_hba_file_rules"]],
    query:[["计划","EXPLAIN (ANALYZE, BUFFERS, WAL)"],["统计","pg_stats"],["Prepared","pg_prepared_statements"]],
    insert:[["事务","pg_stat_activity.xact_start"],["缓冲","pg_buffercache / pg_stat_io"],["WAL","pg_current_wal_lsn()"]],
    read:[["计划","EXPLAIN (ANALYZE, BUFFERS)"],["命中","pg_statio_user_tables"],["索引","pg_stat_user_indexes"]],
    mvcc:[["锁","pg_locks + pg_blocking_pids()"],["事务龄","backend_xmin / xact_start"],["死锁","log_lock_waits / deadlock_timeout"]],
    maintenance:[["死元组","pg_stat_user_tables.n_dead_tup"],["VACUUM","pg_stat_progress_vacuum"],["膨胀","pgstattuple / relation_size"]],
    durability:[["WAL","pg_stat_wal"],["Checkpoint","pg_stat_checkpointer"],["恢复","pg_control_checkpoint()"]],
    replication:[["发送","pg_stat_replication"],["接收","pg_stat_wal_receiver"],["Slot","pg_replication_slots"]],
    ops:[["会话","pg_stat_activity"],["等待","wait_event_type / wait_event"],["I/O","pg_stat_io"]]
  };
  function slide(section,stage,question,lede,mode,story,takeaway,facts,tradeoff,pseudo,source,extra={}){
    return {section,stage,stageName:STAGE[stage],layer:extra.layer||`${stage.toUpperCase()} LAYER`,question,lede,mode,story,takeaway,facts,tradeoff,pseudo,source,visual:extra.visual||{},shortTitle:extra.shortTitle||question.replace(/[？。]/g,"").replaceAll("`",""),deep:{boundary:extra.boundary||`本页只解释“${question.replace(/[？。`]/g,"")}”这一层；完成后才进入下一物理边界。`,failures:extra.failures||["把等待时间全归因于 SQL 本身，会漏掉连接、锁、WAL 与 I/O。","无边界重试可能延长锁持有时间并放大连接池拥塞。"],inspect:extra.inspect||INSPECT[stage],question:extra.quiz||"如果这一层停住，前后两个物理边界分别是什么？",answer:extra.answer||`${takeaway} 生产排障时先用等待事件和实际执行计划证明卡点。`}};
  }

  window.PG_COURSE=[
    slide("00 · OPENING","start","我是 Row `orders.id=A1024`，请跟紧我。","从业务对象、PostgreSQL 协议与 Backend，一路走到 Heap Page、B-Tree、MVCC、WAL、VACUUM、复制与恢复。","cover",
      ["业务代码先构造订单并开始事务；数据库接收的是带类型的 SQL 参数，不是 Java 对象。","INSERT 会同时改变 Heap、索引和 WAL，但这些变化抵达磁盘的时刻不同。","后续 UPDATE/DELETE 不会原地抹掉历史版本，MVCC 与 VACUUM 会接手。"],
      "PostgreSQL 的一行数据不是一条孤立 JSON，而是事务可见性、Heap Tuple、索引指针和 WAL 记录共同定义的状态。",
      [["ROW","orders/A1024"],["TX","T501"],["HEAP TID","(42,7)"],["BASELINE","PostgreSQL 18.6"]],["用一行贯穿 SQL、内存、磁盘与高可用。","真实语义受事务隔离、同步提交和复制配置共同影响。"],
      "BEGIN\nINSERT orders(A1024, 9527, 99.80, NEW)\nCOMMIT\n→ backend → buffers → heap/index → WAL",DOC.home,{layer:"POSTGRESQL · END TO END",quiz:"为什么说数据库里并不存在一个 Java Order 对象？",answer:"驱动把参数编码成 PostgreSQL 类型值；服务端把它们按表结构写成 Heap Tuple，并用系统列维护 MVCC。"}),

    slide("01 · WHOLE MAP","start","一次 INSERT，要穿过哪些物理边界？","先看整机剖面，后面每页只放大一个真实部件。","atlas",
      ["Client/Pool 选择连接，经 TCP/TLS 和 PostgreSQL wire protocol 进入一个 Backend Process。","Parser、Planner、Executor 生成并执行计划，借助共享内存修改 Heap Page 与 B-Tree Page。","WAL 先满足提交耐久性；脏数据页随后由 Checkpointer、Background Writer 或 Backend 写回关系文件。"],
      "主路径是 Client → Backend → Executor → Shared Buffers；WAL、数据文件、Replica 是三条不同的可靠性时间线。",
      [["PORT","5432"],["BACKEND","one process/session"],["PAGE","usually 8 kB"],["WAL","pg_wal"]],["进程隔离与共享缓冲兼顾可靠性和缓存。","连接多会带来进程、内存和调度成本。"],
      "accept → backend\nparse → plan → execute\nmodify shared page + WAL\nflush WAL → CommandComplete",DOC.arch,{layer:"PHYSICAL ATLAS"}),

    slide("02 · BUSINESS TRANSACTION","start","业务代码里的事务，真正包住了什么？","以“创建订单并扣减库存”为例，把 JDBC API 对应到数据库边界。","flow",
      ["连接关闭 auto-commit，发送 BEGIN；从这一刻起 Backend 持有会话与事务状态。","INSERT orders 与 UPDATE inventory 在同一事务中执行；任一语句失败都会让事务进入 aborted 状态。","COMMIT 写入提交 WAL 并按 synchronous_commit 等待；成功后其他事务按快照规则看见结果。"],
      "事务边界必须由业务不变量决定；连接池只能复用连接，不能替业务猜事务范围。",
      [["BEGIN","start xact"],["STATEMENTS","2"],["COMMIT","durability point"],["ROLLBACK","discard visibility"]],["原子维护跨表不变量。","事务过长会持锁、保留旧版本并阻碍 VACUUM。"],
      "conn.begin()\ninsertOrder(A1024)\nreserveInventory()\nconn.commit()",DOC.mvcc,{layer:"APPLICATION CONTRACT",visual:{nodes:[["OrderService","BEGIN"],["INSERT orders","A1024"],["UPDATE inventory","reserve 1"],["COMMIT","T501"]],arrows:["SQL","same TX","durable"]}}),

    slide("03 · DEPLOYMENT","start","Primary、Standby、连接池分别解决什么？","先区分数据执行面、连接复用和故障切换，不把它们画成一个盒子。","replication",
      ["Primary 执行读写并产生 WAL；Standby 接收和重放 WAL，可按配置提供只读查询。","PgBouncer/应用池限制数据库并发连接，减少反复认证与进程建立成本。","VIP、DNS、Proxy 或 HA 管理器负责把新连接导向当前 Primary；PostgreSQL Core 不自动完成全套故障编排。"],
      "连接池不是高可用，Standby 也不是自动主节点；连接、复制、选主是三个独立问题。",
      [["WRITER","Primary"],["READER","Hot Standby"],["POOL","PgBouncer/app"],["FAILOVER","external orchestration"]],["职责分离后每层可独立扩缩。","错误把只读流量发往旧 Primary 会出现脑裂或写失败风险。"],
      "client → pool → writer endpoint\nprimary WAL → standby\nHA controller fences old primary then promotes",DOC.repl,{layer:"DEPLOYMENT TOPOLOGY",visual:{link:"STREAM WAL"}}),

    slide("04 · CLIENT ENDPOINTS","connection","业务客户端一般配置几个 PostgreSQL 地址？","通常连接一个稳定服务入口，而不是把所有数据库节点写进业务代码。","flow",
      ["直连单机可配置一个 host；生产 HA 常配置一个 writer endpoint，由 DNS/VIP/Proxy 指向当前 Primary。","libpq 也支持多个 host 和 target_session_attrs=read-write，按顺序尝试可写节点。","连接池要设置 connect/statement/transaction timeout，并限制最大并发而不是无限重试。"],
      "业务需要的是稳定角色入口；节点 IP 是基础设施细节，故障切换后必须让新连接重新发现 Primary。",
      [["WRITER","stable endpoint"],["MULTI HOST","supported"],["POOL","bounded"],["TIMEOUT","connect + statement"]],["隐藏节点漂移，发布更简单。","DNS 缓存、旧连接和过大池仍可能拖慢切换。"],
      "jdbc:postgresql://db-a,db-b/app\n?targetServerType=primary\npool.max = workload budget",DOC.protocol,{visual:{nodes:[["Application","JDBC/pgx"],["Writer Endpoint","DNS/VIP/Proxy"],["Primary","read-write"]],arrows:["connect","role check"]}}),

    slide("05 · STARTUP & AUTH","connection","TCP 建立后，为什么还不能马上执行 SQL？","PostgreSQL 协议有独立 Startup 阶段：TLS、StartupMessage、认证与参数同步。","protocol",
      ["客户端先建立 TCP，可协商 SSL/TLS；随后发送 user、database、application_name 等 StartupMessage。","服务端按 pg_hba.conf 选择认证方法，例如 SCRAM-SHA-256，并完成挑战应答。","认证成功后返回 ParameterStatus、BackendKeyData 和 ReadyForQuery，才进入普通命令阶段。"],
      "“连接成功”至少包含网络、TLS、身份认证、数据库选择和会话参数五层，不只是 5432 可达。",
      [["AUTH","SCRAM example"],["HBA","first matching rule"],["READY","ReadyForQuery"],["CANCEL","BackendKeyData"]],["强认证与 TLS 保护会话。","频繁新建连接会重复握手和派生进程。"],
      "TCP → SSLRequest? → StartupMessage\n→ AuthenticationSASL\n→ ParameterStatus → ReadyForQuery",DOC.protocol,{layer:"WIRE STARTUP",visual:{nodes:[["SSLRequest","TLS?"],["StartupMessage","user/db/options"],["SCRAM","challenge-response"],["ReadyForQuery","idle"]]}}),

    slide("06 · PROCESS PER CONNECTION","connection","一个连接，为什么对应一个 Backend Process？","Postmaster 监听端口，为每个会话建立独立服务进程。","processes",
      ["Postmaster 接受连接并派生 Backend；Postmaster 本身不解析这条 INSERT。","Backend 有私有 memory contexts、会话参数和事务状态，同时访问 Shared Buffers、WAL Buffers 与锁表。","进程隔离让单个 Backend 崩溃不直接破坏其他会话内存，但大量连接会消耗 RAM 与调度资源。"],
      "PostgreSQL 的并发单位主要是进程；连接数不是免费线程数，连接池是生产系统的常规组成。",
      [["POSTMASTER","listener"],["BACKEND","one/session"],["PRIVATE","work_mem etc."],["SHARED","buffers/locks/WAL"]],["隔离清晰，扩展和故障边界成熟。","数千活跃连接会放大内存、上下文切换和锁竞争。"],
      "postmaster.accept(socket)\nbackend = fork_or_spawn()\nbackend.attachSharedMemory()\nbackend.serveSession()",DOC.arch,{visual:{nodes:[["PID 18399","idle session"],["PID 18420","T501 · INSERT"],["PID 18455","report query"]]}}),

    slide("07 · CONNECTION POOLING","connection","Session Pool 与 Transaction Pool，语义差在哪？","池化模式决定一个客户端逻辑会话能否长期绑定同一 Backend。","flow",
      ["Session pooling 从借出到归还一直绑定 Backend，临时表、LISTEN、会话 SET 和 prepared statement 都较自然。","Transaction pooling 只在一个事务内绑定 Backend；事务结束后下一次可能落到另一进程。","Statement pooling 更激进，不能承载多语句事务；应先检查驱动与应用对 session state 的依赖。"],
      "PgBouncer 不只是减少连接：pool_mode 会改变会话级特性的可用边界。",
      [["SESSION","bind per session"],["TRANSACTION","bind per tx"],["STATEMENT","one statement"],["RISK","session state"]],["Transaction pooling 用较少 Backend 承载更多客户端。","会话级 prepared statement、临时表和 advisory lock 可能失效或串扰。"],
      "client begins → assign backend\nexecute statements\ncommit/rollback → release backend",DOC.protocol,{visual:{nodes:[["1000 Clients","logical sessions"],["PgBouncer","transaction pool"],["80 Backends","bounded"],["PostgreSQL","shared resources"]]}}),

    slide("08 · CANCEL & TIMEOUT","connection","请求超时后，数据库里的 SQL 会自动停吗？","客户端 socket 超时、服务端 statement_timeout 与 CancelRequest 是不同机制。","flow",
      ["客户端读超时只说明它不再等回复；若未发送取消或断开，Backend 可能仍在执行并持锁。","CancelRequest 使用 Backend PID 与 secret key 请求取消当前查询；它不是普通 SQL 消息。","statement_timeout、lock_timeout、idle_in_transaction_session_timeout 分别控制执行、等锁和空闲事务。"],
      "生产超时必须覆盖客户端等待与数据库执行；只切断上游等待可能留下幽灵查询。",
      [["CLIENT","socket timeout"],["SERVER","statement_timeout"],["LOCK","lock_timeout"],["IDLE TX","idle_in_transaction…"]],["多层预算防止资源长期占用。","设置过短会让合法长任务反复失败并重试。"],
      "deadline = requestBudget\nSET LOCAL statement_timeout = deadline\non timeout: send CancelRequest(pid, secret)",DOC.protocol,{visual:{nodes:[["HTTP Deadline","2 s"],["JDBC Timeout","1.8 s"],["statement_timeout","1.5 s"],["Backend Cancel","interrupt"]]}}),

    slide("09 · SIMPLE / EXTENDED","query","驱动发送的是一整段 SQL，还是 Parse/Bind/Execute？","PostgreSQL 支持 Simple Query 和 Extended Query 两套常用消息流。","protocol",
      ["Simple Query 用一个 Query 消息发送 SQL 文本，可包含多条语句。","Extended Query 拆成 Parse、Bind、Describe、Execute、Sync；参数值不需要拼进 SQL 字符串。","Prepared statement 与 portal 可复用，pipeline 可减少往返，但错误处理边界更复杂。"],
      "业务常见的参数化 SQL 走 Extended Protocol；它把 SQL 结构和参数值分开，也为计划复用提供基础。",
      [["SIMPLE","Query"],["EXTENDED","Parse/Bind/Execute"],["PARAM","typed values"],["SYNC","error boundary"]],["防注入、少解析、可 pipeline。","Prepared plan 可能不适合所有参数分布。"],
      "Parse(sql,$1 types)\nBind(params → portal)\nExecute(portal)\nSync",DOC.flow,{visual:{nodes:[["Parse","SQL + type OIDs"],["Bind","A1024 + values"],["Describe","row metadata"],["Execute","portal"],["Sync","ReadyForQuery"]]}}),

    slide("10 · PARSER","query","Parser 会直接决定用哪个索引吗？","Parser 只把 SQL 文本变成语法树，并解析名字与类型；物理路径还没决定。","plan",
      ["Scanner/Parser 检查语法，得到 raw parse tree。","Analysis 解析 orders、列名、函数与操作符，完成类型推断，得到 Query tree。","权限、RLS 与规则重写也会影响最终查询树；此时还没有 Seq Scan 或 Index Scan。"],
      "语法正确只代表查询可被理解；选择索引属于 Planner，真正读页属于 Executor。",
      [["INPUT","SQL text"],["OUTPUT","Query tree"],["NAMES","catalog lookup"],["RLS","rewrite stage"]],["声明式 SQL 与物理算法解耦。","复杂搜索路径、隐式类型转换会改变解析结果。"],
      "raw = parser(sql)\nquery = analyze(raw, catalogs, types)\nquery = rewrite(query, rules, RLS)",DOC.query,{visual:{sql:"INSERT orders …",nodes:[["Query Tree","typed target list"],["Rewrite","rules/RLS"],["Planner","next page"]]}}),

    slide("11 · REWRITE","query","View、Rule 与 RLS 在计划前做了什么？","Rewrite System 可以把一个逻辑查询扩展或改写成真正要规划的 Query tree。","flow",
      ["查询 View 会展开成底层关系；Rule 可增加替代查询。","Row Level Security 把策略谓词加入查询树，使不同角色看到不同 Row。","Planner 接收的是改写后的树，因此 EXPLAIN 才能反映最终访问路径。"],
      "不要把 View/RLS 当作客户端过滤；它们在服务端计划前进入真实查询语义。",
      [["VIEW","expand"],["RULE","rewrite"],["RLS","security quals"],["NEXT","Planner"]],["统一封装访问与安全策略。","复杂改写会让计划难读，也可能重复访问底层表。"],
      "query = analyze(sql)\nrewritten = QueryRewrite(query)\nfor q in rewritten: plan(q)",DOC.query,{visual:{nodes:[["Query Tree","SELECT orders_view"],["View Expand","base tables"],["RLS Predicate","tenant_id=$tenant"],["Planner Input","rewritten tree"]]}}),

    slide("12 · PLANNER","query","Planner 怎样在 Seq Scan 与 Index Scan 之间选？","它用统计信息估算行数，再用成本模型比较候选路径。","plan",
      ["pg_statistic 的 null fraction、n_distinct、MCV、histogram 等帮助估算过滤选择率。","Planner 枚举可行 scan/join/order 路径，累加 CPU 与 I/O 成本；cost 不是毫秒。","最低估算成本的路径成为 Plan Tree；统计陈旧或列相关性缺失会导致 rows 估错。"],
      "执行计划好坏首先取决于 cardinality estimate；只调 random_page_cost 不能补救错误数据模型。",
      [["STATS","ANALYZE samples"],["ESTIMATE","rows/selectivity"],["COST","abstract units"],["OUTPUT","Plan Tree"]],["自动适配数据量和谓词。","估算是模型，不是预知；偏斜与相关列会误导。"],
      "paths = enumerate(query)\nfor path: rows = estimate(stats)\n             cost = cpu + io\nreturn min(cost)",DOC.explain,{visual:{sql:"WHERE id='A1024'",nodes:[["Index Scan","cost 0.29..8.31"],["Estimate","rows=1"],["Result","orders_pkey"]]}}),

    slide("13 · CUSTOM / GENERIC PLAN","query","Prepared Statement 为什么有时突然选错计划？","Bind 时可根据参数生成 Custom Plan，也可能复用 Generic Plan。","plan",
      ["Custom Plan 看见本次参数值，能针对热点 tenant 或稀有值估算。","重复执行后，系统可能比较平均 custom cost 与 generic cost，决定复用参数无关计划。","数据偏斜大时，同一 SQL 对不同参数的最佳路径可能完全不同。"],
      "Prepared Statement 省的是重复规划成本，但通用计划可能牺牲某些参数的执行效率。",
      [["CUSTOM","parameter-aware"],["GENERIC","reusable"],["CONTROL","plan_cache_mode"],["CHECK","EXPLAIN EXECUTE"]],["高频短 SQL 可减少规划 CPU。","参数偏斜时 generic plan 会制造尾延迟。"],
      "on Bind(params):\n  compare custom vs generic history\n  plan = choosePlan(prepared, params)\n  portal = instantiate(plan)",DOC.flow,{visual:{sql:"WHERE tenant_id=$1",nodes:[["Custom Plan","tenant=17"],["Generic Plan","all tenants"],["Portal","bound params"]]}}),

    slide("14 · EXECUTOR","query","Executor 是一次性跑完整棵树吗？","Plan Node 使用 Volcano 风格按需拉取 tuple：父节点不断向子节点要下一行。","plan",
      ["Executor 初始化 PlanState 和快照，打开所需 relation 与索引。","上层 Result/Join/Sort 调用子节点的 next；Scan Node 从 buffer/page 产生可见 tuple。","INSERT 节点消费输入 tuple，检查约束并调用 table/index access method。"],
      "Plan 是算法蓝图；Executor 才真正 pin buffer、读 Heap、持锁、生成 WAL 和返回结果。",
      [["INIT","ExecutorStart"],["PULL","next tuple"],["MODIFY","ModifyTable"],["END","ExecutorFinish"]],["流水化节点可避免一次物化全部结果。","Sort/Hash/Aggregate 可能因 work_mem 不足落盘。"],
      "state = ExecutorStart(plan, snapshot)\nwhile tuple = ExecProcNode(root): emit(tuple)\nExecutorFinish(state)",DOC.query,{visual:{sql:"INSERT … RETURNING",nodes:[["ModifyTable","INSERT"],["Result","VALUES row"],["Heap/Index AM","physical write"]]}}),

    slide("15 · INSERT OVERVIEW","insert","执行 INSERT 后，A1024 依次落到哪里？","先看写入主线，再逐页放大 Heap、索引与 WAL。","flow",
      ["Executor 计算默认值、约束和目标分区，构造一条 Heap Tuple。","Buffer Manager 找到可用 Heap Page，在 Shared Buffers 插入 tuple，再更新相关索引页。","生成 Heap/Index WAL；COMMIT 记录按策略刷盘后返回成功，数据页可以仍是 dirty。"],
      "INSERT 不是把 SQL 文本写入文件；它是一次受事务保护的 Heap、Index 与 WAL 协同修改。",
      [["TXID","501"],["HEAP","orders"],["INDEX","orders_pkey"],["WAL","commit record"]],["WAL 让随机数据页可延迟批量写回。","每个索引都会增加写放大、锁和 WAL。"],
      "tuple = formTuple(values)\ntid = heap_insert(tuple)\nfor index: index_insert(key, tid)\ncommit(T501)",DOC.wal,{layer:"WRITE PATH",visual:{nodes:[["ModifyTable","validated row"],["Heap Page","TID (42,7)"],["B-Tree","A1024→TID"],["WAL","heap+index+commit"]],arrows:["insert","index","durable"]}}),

    slide("16 · DEFAULTS & CONSTRAINTS","insert","Sequence、Default、Constraint 谁先发生？","写 Heap 前，Executor 先计算目标值并执行能即时验证的约束。","flow",
      ["Default/identity/nextval 在表达式求值阶段产生值；Sequence 不是随事务回滚的无缝编号器。","NOT NULL 与 CHECK 可对候选 row 校验；BEFORE trigger 还可能改值或跳过。","UNIQUE/PRIMARY KEY 依赖唯一索引并发检查；FOREIGN KEY 通过内部 trigger 与锁维护引用一致性。"],
      "约束不是表单校验，它们在数据库并发语义下保护最终数据；Sequence gap 是正常现象。",
      [["SEQUENCE","non-transactional gaps"],["CHECK","candidate row"],["UNIQUE","unique index"],["FK","triggers + locks"]],["把关键不变量放在数据库可抗并发竞态。","过多 trigger/FK 会增加写路径和锁等待。"],
      "values = evalDefaults(input)\nrunBeforeTriggers(values)\ncheckNotNullAndCheck(values)\nheap+index insert; queue deferred constraints",DOC.query,{visual:{nodes:[["Input Row","A1024"],["Defaults","created_at/seq"],["Constraints","NOT NULL/CHECK"],["Unique Index","orders_pkey"]]}}),

    slide("17 · RELATION & FORKS","insert","逻辑表 orders，在磁盘上是一份文件吗？","一个 Relation 有 main、FSM、VM 等 fork，索引和 TOAST 又是独立 relation。","files",
      ["pg_class/relfilenode 把逻辑对象映射到 PGDATA 下的物理文件；OID 与 filenode 不保证相同。","主数据在 main fork；_fsm 记录可用空间，_vm 记录 all-visible/all-frozen。","orders_pkey 是自己的 relation；超大字段可能落到关联 TOAST 表。文件超过 1 GB 会分段。"],
      "一张表不是单文件对象；Heap、辅助映射、索引、TOAST 与 WAL 各自有物理边界。",
      [["MAIN","relfilenode"],["FSM","_fsm"],["VM","_vm"],["SEGMENT","1 GB default"]],["分离结构让每种访问模式更高效。","直接操作 PGDATA 文件会绕过 WAL、锁与 catalog，极其危险。"],
      "rel = catalog.lookup('orders')\nmain = base/dbOid/relfilenode\nfsm = main+'_fsm'; vm = main+'_vm'",DOC.files,{layer:"PGDATA · RELATION FILES"}),

    slide("18 · SHARED BUFFERS","insert","写一行数据，为什么先找 Shared Buffers？","PostgreSQL 以页为 I/O 单位；Backend 修改的是共享缓冲中的 8 kB block。","buffer",
      ["BufferTag=(tablespace,database,relation,fork,block) 查共享哈希表；命中后 pin 防止被替换。","未命中则选择 victim，必要时写回脏页，再从 relation file 读入目标 block。","Backend 对页加适当 buffer content lock，修改 tuple 后标记 dirty 并更新 page LSN。"],
      "Shared Buffers 缓存的是数据库页，不是 SQL 结果；pin、lock、dirty 是不同状态。",
      [["UNIT","8 kB block"],["IDENTITY","BufferTag"],["PIN","replacement guard"],["DIRTY","needs writeback"]],["共享热点页避免每个进程重复读盘。","过大并不总更快；仍要给 OS cache 和并发工作内存留空间。"],
      "buf = ReadBuffer(rel, block)\nPin(buf); LockBuffer(buf, EXCLUSIVE)\nmodify(page); MarkBufferDirty(buf)\nUnlock; Unpin",DOC.page,{layer:"SHARED MEMORY",visual:{slot:6}}),

    slide("19 · HEAP PAGE","insert","一个 8 kB Heap Page 里面到底怎么摆 Row？","PageHeader、ItemId、Free Space 与 Tuple 从两端相向生长。","page",
      ["前 24 bytes 是 PageHeaderData，包含 pd_lsn、checksum 与 free-space 边界。","ItemId 数组从前向后增长；每个 4-byte line pointer 保存 tuple 的 offset/length。","Tuple 从页尾向前分配；CTID=(block number,line pointer index)，即使页内 tuple 移动，ItemId 可保持引用。"],
      "索引通常指向稳定的 ItemId，而不是 tuple 在页内的裸字节地址。",
      [["PAGE","usually 8192 B"],["HEADER","24 B"],["ITEMID","4 B"],["TID","(block,offset)"]],["固定页便于缓存、WAL 与校验。","小 Row 仍有页头、line pointer、tuple header 和对齐开销。"],
      "page = buffer.page\noffnum = PageAddItem(tupleBytes)\ntid = (blockNo, offnum)\npage.pd_lsn = walLSN",DOC.page,{layer:"HEAP BLOCK 42"}),

    slide("20 · TUPLE HEADER","insert","A1024 的 Row Header 为什么有 xmin、xmax、ctid？","Heap Tuple 头把事务可见性和版本链直接带到物理 Row 上。","tuple",
      ["t_xmin 记录创建该版本的事务 XID；t_xmax 初始通常无删除事务，后续删除/更新/行锁会改变相关字段与 bits。","t_ctid 初始指向自己；UPDATE 后旧版本的 ctid 指向新版本。","infomask 缓存事务/锁状态提示；null bitmap 与 t_hoff 决定用户列从哪里开始。"],
      "PostgreSQL 不靠一张全局 version table 保存每行历史；关键可见性元数据就在每个 tuple header。",
      [["XMIN","creator XID"],["XMAX","deleter/locker"],["CTID","self/new version"],["HEADER","23 B typical"]],["读者可独立判断版本，减少读写互斥。","每个版本都付出 tuple header 和旧版本空间成本。"],
      "tuple.xmin = T501\ntuple.xmax = Invalid\ntuple.ctid = self\ntuple.infomask = visibility/lock hints",DOC.page,{layer:"HEAP TUPLE",visual:{hot:0}}),

    slide("21 · FREE SPACE MAP","insert","Executor 怎么知道哪一页塞得下新 Row？","FSM 用树状摘要记录各 Heap Page 可用空间，避免每次从头扫表。","flow",
      ["根据 tuple 长度向 FSM 请求至少有 N bytes 的 block。","FSM 返回候选 block 后仍要读取并检查真实 free space，因为摘要允许不精确或并发变化。","找不到合适页就扩展 relation；插入后更新该页的 FSM 估计。"],
      "FSM 是找候选页的导航，不是事务正确性的来源；最终空间判断仍发生在锁住的真实 Page。",
      [["FILE","relfilenode_fsm"],["LEAF","free bytes category"],["TREE","max child"],["FALLBACK","extend relation"]],["避免线性寻找空页。","摘要维护和并发会产生重试，且 FSM 自身占少量空间。"],
      "block = GetPageWithFreeSpace(rel, tupleLen)\nif !fits(read(block)): recordFSM(); retry\nif none: block = ExtendRelation()",DOC.fsm,{visual:{nodes:[["Tuple Size","176 B"],["FSM Tree","find ≥176"],["Heap Block 42","candidate"],["Page Lock","verify space"]]}}),

    slide("22 · HEAP INSERT","insert","Row 真正插入 Page 时，哪些状态同时改变？","锁住 Buffer 后分配 ItemId 与 tuple bytes，并让 VM、WAL 和统计知道这次修改。","page",
      ["在持有页面内容锁时，把 HeapTupleHeader 与列数据写入 free space，得到 TID=(42,7)。","数据修改会清除该页 all-visible VM bit，因为出现了尚未对所有事务可见的新版本。","形成 WAL 记录并把返回的 LSN 写入 page header；Buffer 保持 dirty，事务还未提交。"],
      "Heap Insert 完成不等于事务提交：新 Row 已在内存页中，但可见性和崩溃耐久性仍由事务/WAL 决定。",
      [["TID","(42,7)"],["VM","clear all-visible"],["BUFFER","dirty"],["TX","still in progress"]],["内存路径短，随机页写可延后。","崩溃前必须依靠 WAL 重做；未提交版本也会物理存在。"],
      "LockBuffer(page)\ntid = PageAddItem(tuple{xmin=T501})\nvisibilityMapClear(block)\nlsn = XLogInsert(HEAP_INSERT); page.lsn=lsn",DOC.page,{layer:"HEAP ACCESS METHOD"}),

    slide("23 · B-TREE INSERT","insert","Primary Key 索引里保存整行订单吗？","普通 B-Tree leaf entry 保存索引 key 与 Heap TID；完整 Row 仍在 Heap。","btree",
      ["从 root/internal page 按比较函数向下找到目标 leaf page。","唯一索引并发检查确认没有冲突的可见/进行中 key，再插入 A1024→(42,7)。","Leaf 满时可能 page split，更新 sibling links、父节点与 WAL；这比单个 heap insert 更昂贵。"],
      "Primary Key 的 B-Tree 是有序导航，不是第二份完整表；普通 Index Scan 最终仍需回 Heap 检查 MVCC。",
      [["KEY","A1024"],["VALUE","TID (42,7)"],["ROOT","metapage→root"],["SPLIT","write amplification"]],["等值、范围和排序定位快。","每个额外索引放大 INSERT/UPDATE/WAL 与缓存占用。"],
      "leaf = descend(root, 'A1024')\ncheckUniqueConflict(leaf,key,snapshot)\ninsertIndexTuple(key, tid)\nif full: splitAndPropagate()",DOC.indexes,{layer:"INDEX RELATION"}),

    slide("24 · WAL RECORD","insert","先写 Heap Page，还是先写 WAL？","内存中可以先改 Buffer；真正写持久介质时必须 WAL 先于对应数据页。","wal",
      ["Backend 修改共享数据页并生成描述该变化的 WAL record，追加到 WAL Buffers。","PageHeader.pd_lsn 标记该页最后变化对应的 LSN。","任何进程准备把 dirty page 写到数据文件前，必须确保 WAL 已刷到至少 page LSN；这就是 Write-Ahead。"],
      "“WAL 先写”指持久化顺序，不要求 CPU 在内存里先构造 WAL bytes 再改 page bytes。",
      [["PAGE","dirty in RAM"],["WAL","redo record"],["ORDER","flush WAL ≤ page write"],["LSN","page dependency"]],["顺序 WAL 把随机数据页写从提交关键路径移开。","产生额外写放大并需要管理 WAL 容量。"],
      "modify page in shared memory\nlsn = XLogInsert(change)\npage.pd_lsn = lsn\nbefore write(page): XLogFlush(page.pd_lsn)",DOC.wal,{layer:"WRITE-AHEAD RULE"}),

    slide("25 · COMMIT & GROUP COMMIT","insert","COMMIT 到底等待了哪一次 fsync？","默认本地同步提交等待包含 commit record 的 WAL 到 durable storage，不等待数据页落盘。","wal",
      ["Backend 追加 T501 的 COMMIT WAL record，获得 commit LSN。","多个并发提交可由一个 leader 一起 write/fsync WAL，其他 Backend 等待同一次 flush，即 Group Commit。","WAL durable 后更新事务状态并向客户端发送 CommandComplete/ReadyForQuery；Heap Page 可以仍在 Shared Buffers。"],
      "默认提交成功的核心承诺是：崩溃后可从 durable WAL 重做已提交事务，而不是订单 Page 已经写到 orders 文件。",
      [["DEFAULT","synchronous_commit=on"],["WAIT","local WAL flush"],["GROUP","shared fsync"],["DATA PAGE","may remain dirty"]],["一次顺序 fsync 可保护多个事务。","持久介质延迟直接进入 commit p99。"],
      "commitLSN = XLogInsert(COMMIT T501)\nXLogFlush(commitLSN)  // groupable\nmark transaction committed\nreply COMMIT",DOC.walcfg,{layer:"COMMIT POINT"}),

    slide("26 · SUCCESS SEMANTICS","insert","客户端收到 COMMIT，究竟成功了什么？","必须把业务提交、本地耐久、远端复制和读取可见性拆开。","flow",
      ["在默认 synchronous_commit=on 下，本地 WAL 已 durable，crash recovery 应能恢复 T501。","如果未配置同步 Standby，COMMIT 不等待 Replica；Primary 灾难损坏仍可能丢最新 WAL。","同一 Primary 上后续新快照能看到订单；既有 Repeatable Read 事务仍可能按旧 snapshot 看不见。"],
      "成功不是单一布尔值：本地崩溃安全、跨节点 RPO 与快照可见性是三份契约。",
      [["LOCAL","WAL durable"],["REPLICA","config dependent"],["VISIBILITY","snapshot dependent"],["IDEMPOTENCY","application concern"]],["默认提供强本地事务耐久性。","客户端断线可能造成“提交成功但回复丢失”的未知结果。"],
      "if COMMIT reply lost:\n  do not blindly repeat charge\n  query by business id A1024\n  use UNIQUE + idempotency key",DOC.walcfg,{layer:"APPLICATION GUARANTEE",visual:{nodes:[["COMMIT Record","durable local WAL"],["Client Reply","may be lost"],["New Snapshot","row visible"],["Standby","async by default"]]}}),

    slide("27 · SELECT OVERVIEW","read","一次 SELECT，完整读取路径是什么？","从快照与计划出发，经索引/顺序扫描、Shared Buffers、MVCC，再编码结果。","flow",
      ["Read Committed 为当前 statement 取得 snapshot；Executor 按 Plan Node 请求下一条 tuple。","Index Scan 先找 TID 再回 Heap，Seq Scan 则遍历 Heap blocks；两者都通过 Buffer Manager。","Heap Tuple 通过 MVCC visibility check 后解码列值，经 PostgreSQL 协议发送 DataRow。"],
      "索引只减少候选位置；Snapshot 和 Heap 可见性才决定当前事务能不能看见哪个版本。",
      [["SNAPSHOT","statement/transaction"],["SCAN","index or seq"],["CACHE","shared_buffers"],["RESULT","DataRow"]],["读者通常不阻塞写者。","旧快照会保留旧版本并造成膨胀。"],
      "snapshot = GetActiveSnapshot()\nfor tid in plan.scan():\n  tuple = ReadBuffer(heap, tid.block)\n  if HeapTupleVisible(tuple,snapshot): emit(tuple)",DOC.mvcc,{layer:"READ PATH",visual:{nodes:[["Snapshot","Read Committed"],["Index/Seq Scan","candidate TID"],["Heap Buffer","block 42"],["MVCC Check","visible?"],["DataRow","A1024"]]}}),

    slide("28 · SNAPSHOT","read","Read Committed 的 Snapshot 在什么时候拍？","默认隔离级别通常每条 statement 获取新快照，而不是整个事务固定一张。","mvcc",
      ["Snapshot 记录可见性边界：已完成范围与拍摄时仍 active 的事务集合。","同一事务内第二条 SELECT 会获取更新的 snapshot，因此可能看见别人刚提交的变化。","Repeatable Read/Serializable 通常在事务首次需要 snapshot 时固定事务级视图。"],
      "Snapshot 不是复制数据；它是一组判断 tuple xmin/xmax 是否可见的事务边界。",
      [["READ COMMITTED","per statement"],["REPEATABLE READ","per transaction"],["ACTIVE","xip set"],["COST","oldest xmin retention"]],["高并发读写不用给每行读锁。","长快照阻碍旧版本回收，可能造成 bloat 和 standby conflict。"],
      "snapshot = {xmin, xmax, activeXids[]}\nvisible(xid): committedBeforeBoundary\n            && xid not in activeXids",DOC.isolation,{layer:"TRANSACTION SNAPSHOT",visual:{snapshot:"xmin=500 · xmax=620",nodes:[["v1 · NEW","xmin=501 xmax=612"],["v2 · PAID","xmin=612 xmax=0"]]}}),

    slide("29 · VISIBILITY CHECK","read","xmin/xmax 怎样决定当前版本可见？","先判断创建事务是否对 snapshot 可见，再判断删除/更新事务是否已经生效。","tuple",
      ["xmin 未提交或在 snapshot 的未来，版本不可见；xmin 已提交且足够早，进入下一步。","xmax 无效通常表示未被删除；若 xmax 对 snapshot 可见，则旧版本已结束。","事务状态来自 commit log/缓存与 hint bits；infomask 可缓存已知结果减少重复查状态。"],
      "MVCC 可见性是“创建生效且结束尚未生效”，不是简单比较一个 version 数字。",
      [["XMIN","creator"],["XMAX","deleter/updater"],["STATUS","commit/abort/in-progress"],["HINT","infomask"]],["读者无需锁住已提交版本。","判断路径复杂，旧版本和事务状态都要维护。"],
      "if !creatorVisible(tuple.xmin,snapshot): skip\nif tuple.xmax invalid: visible\nelse visible = !deleterVisible(tuple.xmax,snapshot)",DOC.mvcc,{layer:"HEAP VISIBILITY",visual:{hot:1}}),

    slide("30 · B-TREE DESCENT","read","按主键查询，B-Tree 是怎样走到 A1024 的？","从 root 比较 separator key，经 internal pages 到 leaf，再拿到 Heap TID。","btree",
      ["Planner 选择 orders_pkey Index Scan，Executor pin root page。","在每层做二分/比较，沿 child block 下行；leaf pages 通过 sibling links 支持范围扫描。","找到 A1024 的 index tuple，得到 TID=(42,7)，但还不能直接宣布 Row 可见。"],
      "B-Tree 回答“候选 Row 在哪里”；Heap 与 Snapshot 回答“哪个版本现在可见”。",
      [["HEIGHT","usually small"],["LEAF","key + TID"],["TID","(42,7)"],["RANGE","sibling links"]],["对数级定位与有序扫描。","随机 Heap fetch 可能比 Seq Scan 更贵，低选择性时尤其明显。"],
      "page = root\nwhile !leaf: page = childFor(key)\nentry = lowerBound(page,key)\nreturn entry.heapTid",DOC.indexes,{layer:"INDEX SCAN"}),

    slide("31 · HEAP FETCH","read","索引命中后，为什么还要回表？","普通 B-Tree entry 没有完整 Row，也不知道 Heap version 是否符合当前 snapshot。","page",
      ["用 TID 的 block number 通过 Buffer Manager 获取 Heap Page 42。","Line Pointer 7 找到 tuple bytes；HOT 时可能沿 ctid/redirect chain 找到当前可见版本。","做 MVCC visibility 与谓词 recheck，再按 pg_attribute 解码需要的列。"],
      "Index Scan 的成本由索引遍历和 Heap 随机访问共同组成；索引命中很多行时并不一定快。",
      [["INDEX","candidate"],["HEAP","source of truth"],["VISIBILITY","snapshot"],["BUFFER","hit or read"]],["索引保持紧凑，不复制整行。","大量离散 TID 会产生随机 I/O 和 cache miss。"],
      "tid = indexNext()\nbuf = ReadBuffer(heap, tid.block)\ntuple = page[tid.offset]\nif visible && quals: project(tuple)",DOC.explain,{layer:"HEAP FETCH"}),

    slide("32 · INDEX-ONLY SCAN","read","什么时候索引能不回 Heap？","查询列被索引覆盖且 Visibility Map 证明页面 all-visible 时，才能安全跳过 Heap。","btree",
      ["Index tuple 必须包含查询需要的 key/include columns。","每个候选 TID 先查 VM；对应 Heap Page 的 all-visible bit 为真，说明页中 tuple 对所有当前事务可见。","bit 未设置时仍要回 Heap 做可见性检查，即使实际 tuple 可能已经全部可见。"],
      "Index-Only Scan 的关键不只是 covering index，还依赖 VACUUM 维护的 VM。",
      [["COVER","key/INCLUDE"],["VM","all-visible bit"],["HEAP FETCHES","aim near 0"],["VACUUM","sets VM"]],["减少 Heap I/O，适合读多写少表。","频繁写会清 VM bit；宽 INCLUDE 增大索引与写放大。"],
      "for indexTuple:\n  if VM.allVisible(tid.block): return indexColumns\n  else: heapFetchAndVisibilityCheck(tid)",DOC.vm,{layer:"INDEX-ONLY PATH"}),

    slide("33 · SEQ SCAN","read","有索引，Planner 为什么仍可能选择 Seq Scan？","当预计命中比例高时，顺序读所有 Heap Page 可能比大量随机回表更便宜。","buffer",
      ["Seq Scan 按 block 顺序读取 relation，每页逐 tuple 做 visibility 与 filter。","预读、OS cache 和顺序 I/O 可提供高吞吐；并行查询还可由多个 worker 分担 block。","如果统计把 rows 估得过多/过少，就可能错选 Seq Scan 或 Index Scan。"],
      "索引不是总更快；路径选择取决于需要访问多少页、物理相关性、缓存和 CPU。",
      [["PATTERN","sequential blocks"],["FILTER","per visible tuple"],["PARALLEL","possible"],["CHECK","actual vs estimated rows"]],["扫描大比例数据吞吐高。","小查询误走 Seq Scan 会读很多无关页。"],
      "for block in relation:\n  buf = ReadBuffer(block)\n  for tuple in page:\n    if visible && predicate: emit",DOC.explain,{layer:"SEQUENTIAL ACCESS",visual:{slot:4}}),

    slide("34 · TWO CACHE LAYERS","read","Shared Buffers 命中和 OS Page Cache 命中，是一回事吗？","PostgreSQL 缓冲池与操作系统文件缓存是两层不同的页缓存。","flow",
      ["Shared Buffers 命中时，Backend 直接在共享内存读取数据库页。","未命中时发起 read；底层文件数据可能仍在 OS Page Cache，因此不一定触发 NVMe。","EXPLAIN BUFFERS 的 shared hit/read 描述 PostgreSQL 层；真正物理 I/O 还要结合 pg_stat_io、系统指标与 timing。"],
      "shared read 不等于物理磁盘读；生产诊断必须区分数据库缓存、OS cache 与存储设备。",
      [["L1","shared_buffers"],["L2","OS page cache"],["L3","NVMe"],["OBSERVE","BUFFERS + pg_stat_io"]],["双层缓存利用成熟 OS I/O 能力。","内存规划和指标解释更复杂，缓存重复也有成本。"],
      "if sharedHash.hit(tag): return buffer\nread(relationFile, block)\n// OS may satisfy from page cache\nelse device I/O",DOC.monitor,{visual:{nodes:[["Backend","ReadBuffer"],["Shared Buffers","hit/read"],["OS Page Cache","cached file block"],["NVMe","physical read"]],arrows:["lookup","read()","miss"]}}),

    slide("35 · EXPLAIN ANALYZE","read","怎样确认慢在估算、I/O，还是节点本身？","用 actual rows/time/loops 对照 estimate，并同时看 BUFFERS、WAL 与 timing。","diagnostic",
      ["先看最上层总耗时，再沿实际执行次数与 loops 找放大器；不要只盯最高 cost。","estimated rows 与 actual rows 相差数量级，优先查统计、数据偏斜、相关列与谓词类型。","shared read/hit、temp read/write、WAL records 和 wait events 帮助区分 I/O、落盘、锁与 CPU。"],
      "计划阅读的核心是“估算行数 × 执行次数 × 单次成本”，而不是看到 Seq Scan 就立刻建索引。",
      [["ESTIMATE","rows/cost"],["ACTUAL","time/rows/loops"],["BUFFERS","hit/read/temp"],["CAUTION","ANALYZE executes"]],["证据驱动优化，能定位放大点。","EXPLAIN ANALYZE 会真实执行 DML；生产需用事务回滚或只读查询。"],
      "EXPLAIN (ANALYZE, BUFFERS, WAL, SETTINGS)\ncompare estimatedRows vs actualRows\nfind node: loops × rows × time",DOC.explain,{layer:"QUERY DIAGNOSIS",visual:{symptom:"SELECT p99 = 820 ms"}}),

    slide("36 · UPDATE VERSIONS","mvcc","UPDATE 是在原 Row 上改几个字节吗？","通常不是；PostgreSQL 把 UPDATE 实现为“旧版本结束 + 新版本插入”。","mvcc",
      ["找到旧 tuple v1 后，对目标行建立并发保护，在旧版本写入更新事务的 xmax。","构造包含修改后整行逻辑值的新 tuple v2，xmin=更新事务 XID，插入 Heap。","旧 v1 的 ctid 指向 v2；不同 snapshot 可以同时看见各自正确版本。"],
      "UPDATE 后物理上通常同时存在旧、新两个版本；旧版本要等所有可能看见它的 snapshot 结束后才能回收。",
      [["OLD","xmax=T612"],["NEW","xmin=T612"],["LINK","old.ctid→new"],["SPACE","two versions"]],["读写并发无需覆盖读者正在看的版本。","更新频繁会产生 dead tuples、WAL、索引膨胀。"],
      "old = findVisibleRow(id)\nlock(old); old.xmax = T612\nnew = copyAndModify(old)\nnew.xmin=T612; old.ctid=insert(new)",DOC.mvcc,{layer:"MVCC VERSION CHAIN",visual:{nodes:[["v1 · NEW","xmin=501 xmax=612"],["v2 · PAID","xmin=612 xmax=0"]],hot:1}}),

    slide("37 · HOT UPDATE","mvcc","什么时候 UPDATE 不需要插入新索引项？","HOT 要求未修改索引引用列，并且旧 Row 所在 Page 有空间容纳新版本。","mvcc",
      ["所有普通索引仍指向原始 ItemId；Heap Page 内通过 redirect/HOT chain 找到新版本。","中间不可见版本可在页内 pruning 时提前移除，减少等待全表 VACUUM。","降低 fillfactor 可给页面预留空间，提高 HOT 概率，但会增大表初始占用。"],
      "HOT 没有取消 MVCC 新版本，只是让新版本留在同一页并避免大部分索引写。",
      [["COND 1","no indexed column change"],["COND 2","same-page free space"],["TUNE","fillfactor"],["CHECK","n_tup_hot_upd"]],["显著减少索引写、WAL 与 bloat。","留白换更新效率，且跨页或改索引列时无法 HOT。"],
      "if !changesIndexedColumns && page.hasSpace:\n  new = heapOnlyTuple(old)\n  link HOT chain; skip normal index inserts\nelse normal update",DOC.hot,{layer:"HEAP-ONLY TUPLE",visual:{nodes:[["v1 · NEW","LP7 · indexed"],["v2 · PAID","HOT · same page"],["v3 · SHIPPED","HOT · newest"]],hot:2}}),

    slide("38 · DELETE MARKER","mvcc","DELETE 的“删除标记”到底写在哪里？","DELETE 不立刻挖掉 tuple；它在旧 Heap Tuple header 的 xmax/infomask 中记录删除事务。","tuple",
      ["Executor 找到可见 Row 并取得行级并发保护。","Heap delete 把 tuple.t_xmax 设置为删除事务 XID，更新 infomask/ctid 状态并生成 WAL。","删除事务提交后，新 snapshot 不再看见该版本；旧 snapshot 仍可能需要它，因此 bytes 暂时保留。"],
      "删除标记在 Heap Tuple Header，不是一个独立 delete 文件，也不是立即从 B-Tree 和 Page 中擦除。",
      [["MARK","t_xmax"],["STATUS","transaction commit"],["INDEX","entry may remain"],["PHYSICAL DELETE","later VACUUM"]],["DELETE 很快且兼容并发旧读者。","空间与索引项延迟回收，长期会 bloat。"],
      "tuple = lockVisibleRow(id)\ntuple.xmax = deleteXid\nset delete infomask\nWAL(heap_delete); COMMIT",DOC.page,{layer:"HEAP TUPLE DELETE",visual:{hot:1}}),

    slide("39 · ROW LOCKS","mvcc","两个事务同时 UPDATE A1024，谁等谁？","第一个更新者的事务状态/tuple lock 让冲突更新者等待，普通 SELECT 仍按 MVCC 读旧版本。","lock",
      ["UPDATE 同时取得目标表 RowExclusiveLock，并在 tuple/transaction 层建立行更新冲突。","第二个 UPDATE 发现目标版本被进行中事务修改，等待其 transaction ID 结束，再重新检查可见版本与 WHERE。","普通不带锁 SELECT 不与行写锁冲突；SELECT FOR UPDATE 才主动加入写冲突序列。"],
      "MVCC 解决读写并发，不会让两个写者同时改同一逻辑 Row；写写冲突仍需等待或失败。",
      [["TABLE","RowExclusiveLock"],["ROW","tuple/xid wait"],["READ","usually nonblocking"],["CHECK","pg_blocking_pids"]],["热点行仍能保持一致更新顺序。","长事务会让等待队列扩散到连接池。"],
      "if tuple modified by active xid:\n  wait for xid\n  refetch latest visible tuple\n  apply update or detect serialization failure",DOC.locks,{layer:"LOCK MANAGER",visual:{nodes:[["PID 101","UPDATE A1024","GRANTED"],["PID 202","UPDATE A1024","WAIT"],["PID 303","SELECT A1024","RUN"]]}}),

    slide("40 · ISOLATION LEVELS","mvcc","Read Committed、Repeatable Read、Serializable 差在哪里？","区别不只是“锁更多”，而是 snapshot 生命周期与允许的并发历史不同。","mvcc",
      ["Read Committed 每条 statement 新 snapshot，可能出现不可重复读。","Repeatable Read 固定事务 snapshot，并阻止 PostgreSQL 意义上的 serialization anomaly，但并发更新可能抛错。","Serializable 用 SSI 追踪读写依赖与 predicate locks，不能证明可串行化时中止事务，应用必须重试整个事务。"],
      "更高隔离级别不是自动排队执行；它用更严格检测和事务重试换取更强结果。",
      [["RC","statement snapshot"],["RR","transaction snapshot"],["SER","SSI"],["RETRY","40001 whole tx"]],["可按业务不变量选择正确一致性。","更强隔离带来依赖跟踪、冲突失败与重试成本。"],
      "BEGIN ISOLATION LEVEL SERIALIZABLE\ntry business transaction\nif SQLSTATE 40001: retry entire transaction",DOC.isolation,{layer:"CONCURRENCY CONTRACT",visual:{snapshot:"TX SNAPSHOT",nodes:[["v1","committed before"],["v2","concurrent"],["v3","future"]],hot:0}}),

    slide("41 · DEADLOCK","mvcc","PostgreSQL 如何发现两个事务互相等锁？","等待图形成环时，不可能靠继续等待解决；检测器选择一个事务中止。","lock",
      ["T1 先锁订单再等库存；T2 先锁库存再等订单，形成 T1→T2→T1。","等待超过 deadlock_timeout 后运行 deadlock detection，构建 wait-for graph 查环。","系统取消其中一个事务并返回 40P01；另一个继续，应用需要重试被取消的完整事务。"],
      "死锁不是数据库随机故障，而是跨事务锁顺序形成的环；统一资源访问顺序是首选修复。",
      [["DETECT","deadlock_timeout"],["ERROR","40P01"],["VICTIM","one transaction"],["FIX","consistent lock order"]],["自动打破永久等待。","检测前仍会等一段时间；盲重试会重复死锁。"],
      "waitGraph.add(T1→T2, T2→T1)\nif cycle after timeout:\n  abort one victim\n  release locks",DOC.locks,{layer:"WAIT-FOR GRAPH",visual:{nodes:[["T1 / PID101","holds order; waits stock","WAIT"],["T2 / PID202","holds stock; waits order","WAIT"],["Detector","cycle → abort T2","RUN"]]}}),

    slide("42 · UPSERT","mvcc","`INSERT … ON CONFLICT` 如何避免先查再写的竞态？","唯一索引把“是否冲突”和插入/更新决策放进同一数据库命令。","flow",
      ["先在唯一索引上做 speculative insertion/冲突检测，与并发同 key 插入协调。","DO NOTHING 发现冲突后不产生目标 Row；DO UPDATE 锁定冲突 Row 并执行更新表达式。","它保证唯一键决策原子，但不自动保证任意业务副作用幂等。"],
      "先 SELECT 不存在再 INSERT 存在时间窗口；ON CONFLICT 让唯一索引成为并发仲裁点。",
      [["ARBITER","unique index"],["NOTHING","skip"],["UPDATE","lock conflict row"],["RETURNING","actual row"]],["原子解决 create-or-update 竞态。","热点唯一键仍会形成写等待，复杂副作用需额外设计。"],
      "try speculative index+heap insert\nif unique conflict:\n  DO NOTHING or lock conflict row\n  evaluate DO UPDATE",DOC.locks,{visual:{nodes:[["INSERT A1024","candidate"],["Unique Index","arbiter"],["Conflict?","existing A1024"],["DO UPDATE","locked row"]]}}),

    slide("43 · DEAD TUPLES","maintenance","旧版本什么时候才算真的“死”？","只有不再可能被任何 snapshot 看见，版本才可被 pruning/VACUUM 回收。","mvcc",
      ["UPDATE/DELETE 提交后，旧版本对新 snapshot 不可见，但长事务的旧 snapshot 仍可能需要它。","系统用全局最老可见边界判断 removable；replication slot、prepared transaction 和长查询都可能拉低 horizon。","Dead tuple 占 Heap 空间，旧 index entry 也可能继续存在，形成 table/index bloat。"],
      "逻辑删除发生在事务提交，物理可回收发生在所有旧观察者消失之后。",
      [["LOGICAL DEAD","new snapshots"],["REMOVABLE","past horizon"],["BLOCKER","long xact/slot"],["SYMPTOM","bloat"]],["旧读者保持一致视图。","一个遗忘的长事务可能阻挡全库回收。"],
      "deadFor(snapshot) != removableGlobally\nremove only if tuple.xmax precedes global horizon\nmonitor backend_xmin and slots",DOC.vacuum,{layer:"GARBAGE HORIZON",visual:{nodes:[["v1 · NEW","xmin=501 xmax=612","dead"],["v2 · PAID","xmin=612 xmax=0"]],hot:1}}),

    slide("44 · PAGE PRUNING","maintenance","必须等 Autovacuum 才能清理 HOT 链吗？","访问页面时可做 opportunistic pruning，移除确认无用的页内版本。","vacuum",
      ["PageHeader.pd_prune_xid 提示本页是否值得尝试 pruning。","持有合适页锁且 horizon 允许时，移除 HOT chain 中间版本或把 ItemId 变 redirect/dead。","Pruning 主要整理单个 Heap Page；完整索引清理、冻结和 VM 维护仍需要 VACUUM。"],
      "Pruning 是前台按页的小清理，VACUUM 是跨 relation 的系统维护；两者不是同义词。",
      [["SCOPE","one heap page"],["TRIGGER","page access"],["HOT","chain cleanup"],["NOT ENOUGH","index/freeze"]],["热点页可及时复用空间。","前台查询可能承担少量清理成本，且无法解决全表问题。"],
      "if page.pd_prune_xid < horizon:\n  pruneHOTChains(page)\n  compact tuples\n  update line pointers",DOC.hot,{layer:"HEAP PAGE PRUNING"}),

    slide("45 · AUTOVACUUM TRIGGER","maintenance","Autovacuum 什么时候会来清 orders？","Launcher/Workers 根据修改计数、表大小、阈值与 freeze 风险调度 VACUUM/ANALYZE。","flow",
      ["常规 vacuum 触发近似为 threshold + scale_factor × reltuples，Insert/Update/Delete 计数进入判断。","Launcher 周期唤醒并分配 worker；worker 受 max_autovacuum_workers、cost limit 与 I/O 预算约束。","即使关闭常规 autovacuum，防 XID wraparound 的强制 vacuum 仍可能运行。"],
      "Autovacuum 是 MVCC 系统的组成部分，不是可有可无的清理脚本；大表常需按表调小 scale factor。",
      [["TRIGGER","threshold + scale"],["LAUNCHER","scheduler"],["WORKER","per database/table"],["FREEZE","anti-wraparound"]],["自动回收、统计和防 wraparound。","默认按比例对超大高写表可能启动太晚。"],
      "if deadTuples > base + scale*reltuples:\n  launch vacuum worker\nif changes > analyze threshold: ANALYZE",DOC.vacuum,{layer:"BACKGROUND PROCESSES",visual:{nodes:[["Stats Counters","dead/changed"],["Autovac Launcher","schedule"],["Worker","VACUUM orders"],["Heap/Indexes","reclaim"]]}}),

    slide("46 · VACUUM WORK","maintenance","VACUUM 真正删除了什么，又不会做什么？","它找出 globally dead tuples，清理索引引用，并把 Heap 空间标记为可复用。","vacuum",
      ["扫描 Heap 找 dead item identifiers，收集 TID；按策略清理各索引中的 dead entries。","回到 Heap 标记 line pointer unused/dead、更新 FSM，并在安全页设置 VM all-visible/all-frozen。","普通 VACUUM 通常不把中间空洞还给 OS；VACUUM FULL 重写整表并需要 ACCESS EXCLUSIVE。"],
      "真正物理回收发生在 Heap Page/Index Page 中；普通 VACUUM 主要让空间可复用，不等于文件立刻缩小。",
      [["HEAP","dead tuple space"],["INDEX","dead TIDs"],["FSM/VM","update"],["FULL","rewrite + exclusive lock"]],["可与普通读写并发，维护长期健康。","会产生 I/O；FULL 虽缩文件但锁重、写放大大。"],
      "scan heap → collect dead TIDs\nvacuum indexes(deadTIDs)\nmark heap items reusable\nupdate FSM and VM",DOC.vacuum,{layer:"GARBAGE COLLECTION"}),

    slide("47 · VISIBILITY MAP","maintenance","VM 两个 bit 为什么能加速查询和防止 XID 灾难？","每个 Heap Page 有 all-visible 与 all-frozen 两个保守 bit。","flow",
      ["all-visible 表示页内 tuple 对所有当前事务可见且无需 vacuum；Index-Only Scan 可据此跳过 Heap。","all-frozen 表示页内事务 ID 已安全冻结，anti-wraparound vacuum 可跳过。","只有 VACUUM 设置这些 bit；任何数据修改会清除相关 bit，所以 false 不代表页一定不满足条件。"],
      "Visibility Map 是保守证明缓存：true 必须可靠，false 只是“未知”。",
      [["FILE","relfilenode_vm"],["BITS","2 per heap page"],["SET BY","VACUUM"],["CLEARED BY","DML"]],["极少空间换大量 Heap skip。","高更新表 bit 频繁清除，Index-Only 收益有限。"],
      "if all tuples visible: VM.setAllVisible(block)\nif all frozen: VM.setAllFrozen(block)\non DML: clear relevant bits",DOC.vm,{visual:{nodes:[["Heap Block 42","vacuumed"],["VM all-visible","bit=1"],["Index-Only Scan","skip heap"],["New UPDATE","clear bit"]]}}),

    slide("48 · ANALYZE","maintenance","VACUUM 回收空间，ANALYZE 又在做什么？","ANALYZE 采样列值生成 Planner 统计，不负责删除 dead tuple。","plan",
      ["对表做随机采样，计算 null fraction、n_distinct、most common values 与 histogram。","default_statistics_target/列级统计目标影响样本和 bucket 数；更高更准但维护与规划更贵。","扩展统计可描述列之间 dependencies、MCV 或 ndistinct，修复独立性假设导致的估算错误。"],
      "VACUUM 服务物理健康，ANALYZE 服务计划估算；`VACUUM ANALYZE` 只是一次方便组合。",
      [["INPUT","sample rows"],["OUTPUT","pg_statistic"],["TARGET","statistics target"],["EXTENDED","column correlation"]],["让 Planner 随数据变化调整路径。","采样仍可能漏掉极端偏斜，超高目标增加成本。"],
      "sample = acquireRows(table)\nfor column: build MCV/histogram/ndistinct\nstore stats; invalidate dependent plans",DOC.explain,{layer:"PLANNER STATISTICS",visual:{sql:"ANALYZE orders",nodes:[["Sample","heap rows"],["Statistics","MCV/histogram"],["Planner","new estimates"]]}}),

    slide("49 · TOAST","maintenance","一行太宽超过 Page，PostgreSQL 怎么办？","Tuple 不能跨 8 kB Heap Page；可 TOAST 的 varlena 字段会压缩或移到关联表。","files",
      ["当 Row 超过目标阈值，优先按列 storage strategy 压缩/移出大字段。","Out-of-line 值在 TOAST 表分成约 2 kB chunks，主 tuple 只保留固定大小 pointer。","读取所需列时 detoast；SELECT 不需要大字段时可能避免搬运全部 chunk。"],
      "TOAST 让逻辑大字段透明存在，但它仍产生独立 relation、索引、WAL 和随机读取成本。",
      [["PAGE","tuple cannot span"],["TRIGGER","~2 kB target typical"],["CHUNK","~2 kB typical"],["POINTER","18 B on disk"]],["支持大 text/jsonb/bytea 且小 Row 保持紧凑。","频繁更新/读取大字段会带来额外压缩、WAL 与 TOAST bloat。"],
      "if tuple too wide:\n  compress toastable attributes\n  move chunks to pg_toast table\n  store TOAST pointer in main tuple",DOC.toast,{layer:"OVERSIZED ATTRIBUTE",visual:{nodes:[["Wide Row","JSONB 80 kB"],["Compress","pglz/lz4"],["TOAST Chunks","~2 kB rows"],["Main Tuple","18 B pointer"]]}}),

    slide("50 · CHECKPOINT","durability","数据页既然没随 COMMIT 落盘，什么时候写回？","Checkpointer 周期性推进恢复起点，并把 checkpoint 前相关脏页平滑写回。","wal",
      ["Checkpoint 由时间或 WAL 量等触发；记录 redo 起点并安排 dirty buffers 写数据文件。","checkpoint_completion_target 尝试把写入摊开，避免最后突刺；Background Writer/Backend 也可能提前写页。","完成后保证 checkpoint 之前所需数据页已落盘；崩溃恢复从 checkpoint redo LSN 向后重放。"],
      "Checkpoint 不是每次提交，也不是简单清空缓存；它限制恢复需要重放的 WAL 范围。",
      [["TRIGGER","time/WAL volume"],["WRITE","dirty pages"],["RECORD","checkpoint WAL"],["RECOVERY","redo from LSN"]],["提交保持低随机 I/O，恢复时间有边界。","太频繁增加写放大；太稀疏增加 WAL 与恢复时间。"],
      "write checkpoint-start record\nflush dirty pages gradually\nfsync relation files\nwrite checkpoint-complete record",DOC.walcfg,{layer:"CHECKPOINTER"}),

    slide("51 · FULL PAGE WRITES","durability","为什么 Checkpoint 后第一次改 Page，WAL 可能突然变大？","为防 torn page，默认记录该页首次修改时的完整 Page Image。","page",
      ["存储可能在写 8 kB page 途中掉电，只落下一部分扇区，单靠逻辑增量 WAL 无法重建基线。","full_page_writes=on 时，每个 checkpoint 后某页第一次修改会在 WAL 带 Full Page Image。","后续同 checkpoint 周期内该页修改通常只记增量；压缩 WAL 可降低 FPI 体积但耗 CPU。"],
      "Full Page Write 保护的是数据页原子性，不是把每次 Row 都复制成完整页。",
      [["RISK","torn page"],["FPI","first change after checkpoint"],["CONFIG","full_page_writes"],["WAL","post-checkpoint spike"]],["崩溃恢复能覆盖撕裂页。","Checkpoint 太频繁会增加 FPI 与 WAL 写放大。"],
      "if firstDirtyAfterCheckpoint(page):\n  WAL.append(fullPageImage(page))\nelse WAL.append(deltaRecord(change))",DOC.walcfg,{layer:"WAL PAGE SAFETY"}),

    slide("52 · CRASH RECOVERY","durability","PostgreSQL 崩溃重启，怎样恢复 A1024？","从最近 checkpoint 的 redo point 开始按 LSN 重放 WAL，直到一致状态。","wal",
      ["启动进程读取 control/checkpoint 信息，定位最早需要重做的 WAL。","顺序扫描 WAL records；当 data page LSN 早于 record LSN 时应用 redo，FPI 可覆盖损坏基页。","只有带 COMMIT record 的事务最终可见；未提交事务产生的物理版本会保持不可见并由后续清理回收。"],
      "Recovery 是重做已记录的物理变化并恢复事务状态，不是重新执行原 SQL。",
      [["START","checkpoint redo LSN"],["ORDER","WAL sequence"],["IDEMPOTENT","page LSN check"],["UNCOMMITTED","not visible"]],["不需要每次提交同步所有随机数据页。","WAL 损坏/缺失会阻断恢复，必须监控和备份。"],
      "for record from redoLSN:\n  page = read(record.block)\n  if page.lsn < record.lsn: redo(record,page)\nfinish recovery; accept connections",DOC.wal,{layer:"STARTUP PROCESS"}),

    slide("53 · BASE BACKUP & PITR","durability","有 WAL，为什么还需要 Base Backup？","WAL 是变化序列；恢复到另一台机器需要一个一致基线，再重放后续 WAL。","files",
      ["pg_basebackup/备份工具取得数据目录基线与起止 WAL 位置；在线备份期间变化由 WAL 衔接。","持续归档 WAL segment，恢复时从 Base Backup 开始应用 archive/stream WAL。","设置 recovery target time/LSN/name 可做到 PITR；目标之后的数据不会自动保留。"],
      "高可用副本不是备份；误删会被快速复制，PITR 需要独立保留的 Base Backup 与 WAL archive。",
      [["BASE","full physical baseline"],["ARCHIVE","continuous WAL"],["TARGET","time/LSN/name"],["TEST","restore drills"]],["可恢复到灾难或误操作前。","归档缺口、未测试备份和过长 RPO 都会让方案失效。"],
      "restore base backup\nconfigure restore_command\nset recovery_target_time\nreplay archived WAL until target",DOC.walcfg,{layer:"DISASTER RECOVERY"}),

    slide("54 · PHYSICAL REPLICATION","replication","Standby 是主动拉 WAL，还是 Primary 主动推？","Standby 的 WAL Receiver 主动连接 Primary；Primary 为该连接运行 WAL Sender 持续发送。","replication",
      ["Standby 使用 primary_conninfo 建立 replication connection，请求从某 LSN 开始流。","Primary walsender 从 WAL buffers/files 读取连续 WAL bytes 发送；Standby walreceiver 写本地 pg_wal。","Startup process 在 Standby 重放 WAL 到 Heap/Index Page；物理复制传的是集群级 WAL，不是逐 Row SQL。"],
      "连接由 Standby 发起，数据由 Primary 的 WAL Sender 流出；接收与重放又是两个不同进度。",
      [["CONNECT","standby→primary"],["SEND","walsender"],["RECEIVE","walreceiver"],["APPLY","startup/replay"]],["字节级复制保留完整物理一致性。","版本/平台要求更严格，不能只复制选定表。"],
      "standby.connect(startLSN)\nprimary.walsender.streamWAL()\nstandby.walreceiver.write()\nstartup.replay()",DOC.repl,{layer:"STREAMING REPLICATION"}),

    slide("55 · SYNCHRONOUS REPLICATION","replication","同步复制的 COMMIT，究竟等到 Standby 哪一步？","synchronous_commit 可选择等待本地、远端写、远端刷盘或远端 apply。","replication",
      ["配置 synchronous_standby_names 选出同步候选；默认没有同步 Standby 时提交不等待复制。","remote_write/on/remote_apply 对应不同远端确认强度；越靠后 RPO 越小、延迟越高。","ANY N 提供 quorum，FIRST N 按优先级选择；同步节点不可用可能阻塞提交。"],
      "同步复制不是一个开关，而是“等几个 Standby、等到哪个阶段”的延迟/一致性契约。",
      [["LOCAL","local durable"],["ON","remote flush"],["REMOTE_APPLY","query visible"],["QUORUM","ANY N"]],["可把单节点故障的数据丢失窗口降到更小。","网络 RTT、慢盘和同步节点故障直接进入 commit latency。"],
      "commitLSN = flushLocalWAL()\nwait until syncStandby confirms\n  write / flush / apply per policy\nreply COMMIT",DOC.repl,{layer:"COMMIT REPLICATION",visual:{link:"WAIT FOR FLUSH",replayLsn:"0/16B6A2C0"}}),

    slide("56 · REPLICATION SLOT","replication","Replica 断线时，Primary 怎么知道哪些 WAL 不能删？","Replication Slot 保存 consumer 所需的 restart/confirmed LSN，阻止过早回收 WAL。","flow",
      ["Physical slot 的 restart_lsn 表示 Standby 仍可能需要的最老 WAL。","Logical slot 还维护 confirmed_flush_lsn 与 decoding 状态，支持从正确逻辑位置继续。","Slot 不会自动判断消费者已永久消失；长期停滞会让 pg_wal 膨胀，甚至填满磁盘。"],
      "Slot 用 Primary 磁盘换断线续传可靠性；每个 Slot 都必须有 owner、lag 告警和删除流程。",
      [["PHYSICAL","restart_lsn"],["LOGICAL","confirmed_flush_lsn"],["RISK","retained WAL"],["LIMIT","max_slot_wal_keep_size"]],["消费者断线后可从安全位置恢复。","遗忘 slot 会成为可用性事故。"],
      "slot.requiredLSN = consumerAck\nWAL recycle boundary = min(all slot LSNs)\nalert if retainedBytes exceeds budget",DOC.repl,{visual:{nodes:[["WAL Producer","Primary"],["Replication Slot","retain from LSN"],["Disconnected Replica","lag"],["pg_wal Disk","growing"]]}}),

    slide("57 · HOT STANDBY CONFLICT","replication","Standby 只读查询，为什么会被 Recovery 取消？","Recovery 必须及时应用 Primary 的 WAL；长查询可能需要已被 Primary 清理的旧版本。","replication",
      ["Primary VACUUM 删除旧版本并产生 WAL；Standby replay 需要执行同样清理。","Standby 长查询 snapshot 仍想读该版本，产生 recovery conflict；等待超过 max_standby_streaming_delay 后查询可被取消。","hot_standby_feedback 可把 Standby xmin 告诉 Primary，减少取消，但会在 Primary 保留更多 dead tuples。"],
      "读副本不是无限期历史快照：要在复制延迟、查询取消与 Primary bloat 之间取舍。",
      [["CONFLICT","replay vs query"],["DELAY","max_standby…"],["FEEDBACK","hot_standby_feedback"],["COST","primary bloat"]],["Standby 可分担只读查询。","长报表会增加 lag、取消或反向制造 Primary 膨胀。"],
      "if WAL cleanup conflicts with standby snapshot:\n  wait up to delay budget\n  cancel query OR retain rows via feedback",DOC.standby,{layer:"RECOVERY CONFLICT",visual:{link:"WAL CLEANUP",replayLsn:"blocked by query"}}),

    slide("58 · FAILOVER","replication","Primary 挂掉后，PostgreSQL 会自动选主吗？","Core 提供 promote 与复制机制，但完整探活、仲裁、fencing、流量切换通常由外部 HA 系统负责。","flow",
      ["HA 控制器确认故障并防止旧 Primary 继续写，即 fencing；否则可能出现双主分叉。","选择合适 Standby promote，恢复结束后进入读写；writer endpoint 指向新 Primary。","其他 Standby 重新跟随；旧 Primary 通常需要 rewind/rebuild，不能直接带旧时间线回来。"],
      "安全 Failover 先保证唯一写者，再追求恢复速度；只做 promote 不做 fencing 是危险的。",
      [["RTO","detect + promote + route"],["RPO","replication position"],["FENCING","mandatory"],["TIMELINE","changes on promotion"]],["可自动恢复写服务。","错误故障判断会导致不必要切换，缺少 fencing 会脑裂。"],
      "detect primary failure\nfence old primary\npromote best standby\nmove writer endpoint\nrejoin other nodes",DOC.standby,{layer:"HA ORCHESTRATION",visual:{nodes:[["Old Primary","unreachable"],["HA Controller","quorum + fence"],["Standby","promote"],["Writer Endpoint","reroute"]]}}),

    slide("59 · LOGICAL REPLICATION","replication","CDC/逻辑复制为什么不是复制 Heap Page？","Logical Decoding 从 WAL 重建表级 INSERT/UPDATE/DELETE，再按 Publication 发送给 Subscriber。","replication",
      ["WAL Sender 加载 pgoutput 等 output plugin，从 logical slot 解码已提交变化。","Publication 选择表/操作；协议传 relation metadata 与 row changes，而不是原始 8 kB page。","Subscriber apply worker 按事务顺序对本地表执行变化；DDL、Sequence 和冲突处理需要额外设计。"],
      "物理复制复制整个实例的存储变化；逻辑复制复制可选择的逻辑 Row 变化，适合迁移、CDC 与部分分发。",
      [["SOURCE","WAL + decoding"],["FILTER","publication"],["STATE","logical slot"],["APPLY","subscriber worker"]],["可跨大版本、选择表并接入事件系统。","解码/slot 占资源，DDL 和无主键更新需谨慎。"],
      "WAL → logical decoding\n→ pgoutput relation/row messages\n→ subscriber apply in transaction order",DOC.logical,{layer:"LOGICAL CHANGE STREAM",visual:{link:"ROW CHANGES"}}),

    slide("60 · PARTITIONING","ops","大表分区后，一条 Row 物理上去了哪里？","Partitioned Table 是路由壳；每个 Leaf Partition 是独立 relation 与索引。","files",
      ["INSERT 根据 partition key 计算目标 leaf，例如 orders_2026_09，再对该 relation 执行 Heap/Index 写。","查询规划/执行用 partition pruning 排除不可能分区；参数化查询可能在执行期继续 pruning。","Unique/PK 若要跨所有分区保证唯一，约束键通常必须包含 partition key；过多分区也会增加规划与 catalog 成本。"],
      "分区解决管理、裁剪和局部维护，不自动提升所有查询，也不等于跨机器分片。",
      [["PARENT","no heap rows"],["LEAF","real relation"],["PRUNING","plan/runtime"],["SHARDING","not automatic"]],["时间范围查询、归档和分区维护更高效。","分区键错误、分区过多或无法裁剪会更慢。"],
      "leaf = partitionDispatch(row.partitionKey)\ninsert into leaf heap/index\nquery: prune leaves by predicates",DOC.partition,{layer:"TABLE PARTITIONING",visual:{nodes:[["orders","partitioned parent"],["orders_2026_08","leaf relation"],["orders_2026_09","A1024 · target"],["orders_default","fallback"],["Local Indexes","per leaf"]]}}),

    slide("61 · CONNECTION EXHAUSTION","ops","数据库 CPU 不高，为什么新请求仍然全部超时？","连接池排队、max_connections、idle in transaction 与 Backend 内存可能先成为瓶颈。","diagnostic",
      ["区分应用等池、TCP/认证、数据库 active、idle 和 idle in transaction；它们需要不同修复。","每个 Backend 有私有内存与可能的 work_mem 使用；连接上限不应等于所有应用实例池上限之和。","长事务即使 idle 也持有 snapshot/locks，阻碍 VACUUM；池化前先设计全局连接预算。"],
      "连接是受限并发令牌，不是越多越快；排队应发生在可控池中，而不是数据库内部无限堆积。",
      [["CHECK","pg_stat_activity"],["POOL","wait metrics"],["STATE","idle in transaction"],["BUDGET","global max"]],["有限并发保护数据库吞吐稳定。","过小池限制吞吐，过大池制造抖动和内存风险。"],
      "budget = safeActiveBackends\nperInstancePool = budget / appInstances\nset acquisition timeout\nkill/fix idle-in-transaction owners",DOC.monitor,{visual:{symptom:"pool wait ↑ · CPU 28%",nodes:[["Pool","acquire wait"],["Activity","states"],["Memory","per backend"],["Transactions","old xact"]]}}),

    slide("62 · LOCK DIAGNOSIS","ops","线上“SQL 卡住”，怎样先找到真正阻塞链？","从 pg_stat_activity 的 wait_event 出发，用 pg_blocking_pids 和 pg_locks 还原 blocker。","lock",
      ["先找 active 且等待 Lock 的 PID，记录 query_start/xact_start/application_name。","pg_blocking_pids(pid) 找直接 blocker，再递归到根阻塞者；不要只杀最末端等待者。","确认 blocker 是合法长事务、idle in transaction、DDL 还是异常任务，再选择取消 query 或终止 session。"],
      "锁问题要画等待链，不要按“最慢 SQL”列表随机杀连接。",
      [["WAITER","wait_event_type=Lock"],["BLOCKER","pg_blocking_pids"],["ROOT","oldest holder"],["ACTION","cancel vs terminate"]],["能精准解除根因并保留证据。","直接终止连接会整事务回滚，也可能触发重试风暴。"],
      "waiters = activity where wait_event_type='Lock'\nfor pid: blockers = pg_blocking_pids(pid)\ntrace to root; inspect xact before action",DOC.locks,{layer:"BLOCKING TREE",visual:{nodes:[["PID 301","ALTER TABLE","GRANTED"],["PID 402","UPDATE orders","WAIT"],["PID 517","SELECT orders","WAIT"]]}}),

    slide("63 · PERFORMANCE FLOW","ops","PostgreSQL 慢了，应该沿哪条链排查？","先分类连接、锁、CPU、I/O、WAL、内存落盘与复制，再进入单条计划。","diagnostic",
      ["pg_stat_activity/wait_event 判断总体在等待什么；pg_stat_io、系统 I/O 与 pg_stat_wal 看资源路径。","pg_stat_statements 找总耗时/调用/均值异常的 queryid，再用 EXPLAIN ANALYZE 验证代表性参数。","检查估算偏差、buffer/temp/WAL、锁持有时间、autovacuum 与 replication lag，最后才改配置。"],
      "诊断顺序是“系统等待分类 → 语句排行 → 实际计划 → 数据/配置修复”，不是先重启或盲建索引。",
      [["SYSTEM","wait events"],["WORKLOAD","pg_stat_statements"],["PLAN","actual evidence"],["FIX","model/index/query/config"]],["避免局部优化掩盖系统瓶颈。","没有基线和参数样本时，平均值会隐藏尾延迟。"],
      "classify waits\nrank queryid by total_exec_time\nreproduce representative params\nEXPLAIN + BUFFERS + WAL → fix",DOC.monitor,{layer:"PRODUCTION METHOD",visual:{symptom:"database p99 ↑"}}),

    slide("64 · FINAL CHECK","ops","现在，你能解释 A1024 的一生了吗？","把 SQL、事务、内存页、物理文件与高可用重新连成一条可复述主线。","atlas",
      ["写：Protocol → Backend → Plan → Heap/Index Buffer → WAL → COMMIT；数据页稍后写回。","读：Snapshot → Plan → Index/Seq → Heap → MVCC；UPDATE/DELETE 产生版本，VACUUM 延迟回收。","恢复与复制：Checkpoint 限制 redo，Standby 接收/重放 WAL；同步级别和 HA 编排决定 RPO/RTO。"],
      "真正掌握 PostgreSQL，是能分别说明谁决定、谁执行、状态放在哪里、成功承诺到哪一步以及失败后如何恢复。",
      [["ROW","A1024"],["TID","(42,7)"],["TX","T501"],["RULE","WAL before data page"]],["同一物理模型可以解释性能、一致性和故障。","任何单一配置都不能替代正确事务边界、索引与运维证据。"],
      "SQL → Backend → Plan → Buffer/Page\n→ Heap + Index + WAL → COMMIT\n→ MVCC/VACUUM → Checkpoint/Replica/Recovery",DOC.home,{layer:"END TO END RECAP",quiz:"COMMIT 后最重要的三条独立时间线是什么？",answer:"本地 WAL 是否 durable、数据页何时写回、Standby 收到/刷盘/应用到哪里；它们分别决定本地恢复、写放大和跨节点 RPO/可见性。"})
  ];
})();
