(() => {
  "use strict";

  const DOC = {
    protocol:"https://redis.io/docs/latest/develop/reference/protocol-spec/",
    event:"https://redis.io/docs/latest/operate/oss_and_stack/reference/internals/internals-rediseventlib/",
    clients:"https://redis.io/docs/latest/develop/reference/clients/",
    types:"https://redis.io/docs/latest/develop/data-types/",
    memory:"https://redis.io/docs/latest/operate/oss_and_stack/management/optimization/memory-optimization/",
    expire:"https://redis.io/docs/latest/commands/expire/",
    eviction:"https://redis.io/docs/latest/develop/reference/eviction/",
    pipeline:"https://redis.io/docs/latest/develop/using-commands/pipelining/",
    tx:"https://redis.io/docs/latest/develop/using-commands/transactions/",
    lua:"https://redis.io/docs/latest/develop/programmability/eval-intro/",
    functions:"https://redis.io/docs/latest/develop/programmability/functions-intro/",
    persistence:"https://redis.io/docs/latest/operate/oss_and_stack/management/persistence/",
    replication:"https://redis.io/docs/latest/operate/oss_and_stack/management/replication/",
    sentinel:"https://redis.io/docs/latest/operate/oss_and_stack/management/sentinel/",
    cluster:"https://redis.io/docs/latest/operate/oss_and_stack/reference/cluster-spec/",
    latency:"https://redis.io/docs/latest/operate/oss_and_stack/management/optimization/latency/",
    scan:"https://redis.io/docs/latest/commands/scan/",
    wait:"https://redis.io/docs/latest/commands/wait/"
  };

  const STAGE_NAMES = {
    start:"先建立地图", network:"命令进入 Redis", memory:"写进内存", lifecycle:"读取与生命周期",
    structure:"数据结构", composition:"批处理与原子性", cache:"缓存工程", persistence:"持久化",
    replication:"复制与高可用", cluster:"Redis Cluster", ops:"生产诊断"
  };

  const INSPECT = {
    start:[["数据形态","TYPE / OBJECT ENCODING / MEMORY USAGE"],["请求","redis-cli --raw / client trace"],["版本","INFO server"]],
    network:[["连接","CLIENT LIST / INFO clients"],["命令耗时","SLOWLOG GET / LATENCY DOCTOR"],["网络","INFO stats / netstat / packet capture"]],
    memory:[["对象","TYPE key / OBJECT ENCODING key"],["占用","MEMORY USAGE key / INFO memory"],["采样","redis-cli --memkeys"]],
    lifecycle:[["TTL","PTTL key"],["淘汰","INFO stats | evicted_keys"],["过期","INFO stats | expired_keys"]],
    structure:[["编码","OBJECT ENCODING key"],["基数","HLEN / LLEN / SCARD / ZCARD / XLEN"],["大键","redis-cli --bigkeys --memkeys"]],
    composition:[["阻塞","SLOWLOG GET"],["客户端","CLIENT LIST"],["事务","WATCH / MULTI / EXEC 返回值"]],
    cache:[["命中率","keyspace_hits / (hits + misses)"],["热键","COMMANDLOG / application metrics"],["延迟","LATENCY DOCTOR / SLOWLOG GET"]],
    persistence:[["RDB","INFO persistence"],["AOF","aof_current_size / aof_rewrite_in_progress"],["COW","current_cow_peak / latest_fork_usec"]],
    replication:[["链路","INFO replication"],["偏移","master_repl_offset / slave_repl_offset"],["Sentinel","SENTINEL master / replicas / ckquorum"]],
    cluster:[["Slots","CLUSTER SHARDS / CLUSTER SLOTS"],["健康","CLUSTER INFO"],["重定向","客户端 MOVED/ASK 指标"]],
    ops:[["总览","INFO / LATENCY DOCTOR / MEMORY DOCTOR"],["慢命令","SLOWLOG GET"],["CPU","commandstats / hot threads / perf"]]
  };

  function slide(section, stage, question, lede, mode, story, takeaway, facts, tradeoff, pseudo, source, extra = {}) {
    return {
      section, stage, stageName:STAGE_NAMES[stage], layer:extra.layer || `${stage.toUpperCase()} LAYER`, question, lede, mode, story,
      shortTitle:extra.shortTitle || question.replace(/[？。]/g, ""), takeaway, facts, tradeoff, pseudo, source,
      deep:{
        boundary:extra.boundary || `本页只解释“${question.replace(/[？。]/g, "")}”这个边界；它完成后，主线才进入下一页。`,
        failures:extra.failures || ["把这里的等待误当成 Redis 执行慢，会调错方向。","重试若没有超时预算或幂等语义，会把局部故障放大。"],
        inspect:extra.inspect || INSPECT[stage],
        question:extra.quiz || `如果这里停住，前后两个物理边界分别是什么？`,
        answer:extra.answer || `${takeaway} 排障时先证明请求停在这里，再决定改客户端、配置还是数据模型。`
      }
    };
  }

  window.REDIS_COURSE = [
    slide("00 · OPENING", "start", "我是 Key `session:user:9527`，这次请跟紧我。", "从 Java Session 对象变成字节，穿过 TCP/RESP、事件循环、字典、过期表、AOF、复制，再到 Sentinel 与 Cluster。", "cover",
      ["业务里我是一个 Session 对象；Redis Core 最终只看见 key bytes、value bytes 和命令语义。","一次 SET 成功，不自动等于写盘、复制和故障后绝不丢。","这门课沿同一条 Key 逐层拆开速度、可靠性与内存成本。"],
      "Redis 不是“神奇 Map”，而是一台用事件循环串行改变内存状态、再异步处理持久化与复制的服务器。",
      [["KEY","session:user:9527"],["VALUE","JSON bytes"],["TTL","1800 s"],["COMMAND","SET … EX 1800 NX"]],
      ["一条主线把 API、内存与机器边界连起来。","真正的生产语义仍由持久化、复制和客户端策略共同决定。"],
      "SET session:user:9527 <json> EX 1800 NX\n→ RESP → event loop → dict + expires\n→ AOF/replication → +OK", DOC.types,
      {layer:"REDIS · END TO END", boundary:"封面只建立主角与问题，不在这里塞入所有答案。后面每页只放大一个真实边界。", quiz:"为什么说 Redis 存的不是 Java Session 对象？", answer:"应用先把对象编码成 JSON/MessagePack 等字节；Redis String 是二进制安全字节序列，不理解你的 Java 类。"}),

    slide("01 · WHOLE MAP", "start", "一条 SET，到底穿过哪些物理边界？", "先建立从业务进程到 Redis 内存、磁盘和副本的全景，后面逐层放大。", "whole-map",
      ["Client Pool 选择连接，把命令编码为 RESP，通过 TCP/TLS 发往 Redis。","事件循环读入命令；执行路径校验后，在主线程语义边界改变 DB dictionary 和 expires。","回复、AOF、复制、RDB 各有自己的完成时刻，不能用一个“成功”概括。"],
      "主数据路径是 Client → Socket/RESP → Event Loop → Command → DB Dict；AOF、RDB、Replica 是旁边的可靠性路径。",
      [["PORT","6379"],["DB","db0"],["DICT","keyspace"],["SIDECARS","AOF · RDB · Replica"]],
      ["主路径短，常用命令延迟低。","单个慢命令、fork、fsync 或大回复都能影响同一事件循环。"],
      "receive(fd) → parseRESP() → lookupCommand()\n→ expireIfNeeded(key) → setKey()\n→ propagate(AOF, replicas) → reply(+OK)", DOC.event,
      {layer:"PHYSICAL ATLAS", boundary:"控制面（Sentinel/Cluster 拓扑）与数据面（这条 SET 的字节）必须分开看；控制面不替每条 SET 搬数据。"}),

    slide("02 · COMMAND ANATOMY", "start", "`SET key value EX 1800 NX` 每一段到底控制什么？", "先把业务 API 还原成 Redis 真正接收的命令契约。", "command-anatomy",
      ["SET 选择 String 写路径；key 是二进制安全名字，不是目录。","value 是应用序列化后的字节；Redis Core 不知道它是 JSON 还是 Java 对象。","EX 1800 建立 TTL；NX 使“仅不存在才写”在同一条命令里原子判断。"],
      "一个看似简单的 SET 同时决定数据类型、身份、值字节、生命周期和条件写语义。",
      [["SET","String write"],["EX","seconds TTL"],["NX","only if absent"],["RETURN","OK or null"]],
      ["一个原子命令避免 SET 与 EXPIRE 之间的竞态。","NX 失败返回空，不代表网络或服务器错误；客户端必须区分业务未写与执行失败。"],
      "if NX && exists(key): return null\nset(key, valueBytes)\nsetExpire(key, now + 1800s)\nreturn OK", "https://redis.io/docs/latest/commands/set/",
      {layer:"API CONTRACT", quiz:"为什么不建议先 SET，再单独 EXPIRE？", answer:"两条命令之间客户端可能断线或被其他命令插入，留下无 TTL 的 key；SET EX 把值与 TTL 放进同一原子操作。"}),

    slide("03 · SERIALIZATION", "start", "Java Session 是怎么变成 Redis String 的？", "序列化发生在业务进程；Redis 收到的是一串二进制安全 bytes。", "serialization",
      ["JVM 堆上先存在 Session{uid,roles,issuedAt}。","Jackson/MessagePack/Protobuf 把对象变成 value bytes；key 通常用 UTF‑8 编码。","RESP 只包裹这些 bytes 的长度与边界，不解析 JSON 字段。"],
      "Redis Core 的 String 是字节序列；对象版本兼容、压缩和安全边界属于应用序列化契约。",
      [["KEY CODEC","UTF‑8"],["VALUE CODEC","JSON example"],["BINARY SAFE","yes"],["REDISJSON","separate data type/module"]],
      ["应用控制 schema，部署简单。","JSON 体积和解析成本较大；升级类结构时要维护向后兼容。"],
      "session = Session(...)\nvalueBytes = json.encode(session)\nredis.set(utf8(key), valueBytes, EX=1800, NX=true)", DOC.types,
      {layer:"APPLICATION → BYTES", boundary:"本页只讲应用序列化，不把 RESP 序列化和 Redis 内部 object encoding 混为一谈；它们是三个不同层次。"}),

    slide("04 · DEPLOYMENT CHOICE", "start", "Standalone、Sentinel、Cluster，数据路径哪里不同？", "三种部署不是同义词：它们解决的规模与故障问题不同。", "deployment",
      ["Standalone：一个可写实例；最短路径，但节点故障需要外部恢复。","Primary + Replicas + Sentinel：不分片，提供监控、服务发现和自动主从切换。","Redis Cluster：16384 slots 分布到多个 masters，每个 master 再配 replicas。"],
      "先问单实例容量是否够，再问是否需要自动故障转移，最后才决定是否用 Cluster 分片。",
      [["STANDALONE","1 writable node"],["SENTINEL","HA, no sharding"],["CLUSTER","sharding + HA"],["TRACK","先用单主线讲执行"]],
      ["从简单拓扑开始，心智与运维成本低。","过早上 Cluster 会引入跨 slot、多 key、重定向和 reshard 复杂度。"],
      "if dataset+qps fits one primary:\n  choose standalone or Sentinel\nelse:\n  choose Cluster and design hash tags", DOC.sentinel,
      {layer:"TOPOLOGY", boundary:"前半课程先放大单个 Primary 内部，因为无论 Sentinel 还是 Cluster，每个 shard 的命令执行、对象编码与持久化机制都从这里开始。"}),

    slide("05 · CLIENT POOL", "network", "业务客户端一般连接几个 Redis 地址？", "代码通常拿的是一个 Client/Pool；真正的可用地址由直连、Sentinel 或 Cluster 模式决定。", "client-pool",
      ["Standalone/Sentinel 常由客户端配置 2～3 个 Sentinel 地址，查询当前 Primary，再建立连接池。","Cluster 客户端配置少量 seed nodes，握手后缓存 slot→node 拓扑，不需要写满所有节点 IP。","连接池复用 TCP/TLS；每次命令从池中借连接或用 multiplexed connection。"],
      "“一个 RedisClient 对象”不等于“只配置一个脆弱 IP”；客户端模式必须与服务端拓扑匹配。",
      [["SENTINELS","usually 3 endpoints"],["CLUSTER SEEDS","2–3 reachable nodes"],["POOL","bounded"],["TIMEOUT","connect + command"]],
      ["多入口与拓扑刷新屏蔽节点搬迁。","无限连接、无限重试会在故障时耗尽客户端和 Redis 的文件描述符。"],
      "client = RedisClient(mode, seeds)\nconn = pool.borrow(deadline)\nnode = topology.route(key)\nconn.send(command)", DOC.clients,
      {layer:"APPLICATION HOST", failures:["只配置一个节点 IP，该节点重启后所有业务同时断流。","客户端连接池耗尽，业务在借连接阶段排队，却误判成 Redis 命令慢。"], quiz:"Cluster 客户端为什么只需要少量 seed nodes？", answer:"Seed 只用于首次进入集群；客户端随后通过 Cluster 拓扑获取并缓存 16384 slots 到节点的映射。"}),

    slide("06 · RESP BYTES", "network", "这条 SET 在 TCP 上长什么样？", "RESP 把命令编码成 Bulk String 数组，用长度前缀保住二进制边界。", "resp",
      ["数组头 `*7` 表示七个元素；每个 `$N` 后跟 N 个原始 bytes。","JSON 内部可以包含空格、换行甚至零字节，因为解析依靠长度而不是分隔符猜测。","TCP 是字节流：一次 read 可能只有半条命令，也可能包含多条 pipeline 命令。"],
      "RESP 简单、可读、二进制安全；解析器必须在连接输入缓冲区里处理半包与粘包。",
      [["PROTOCOL","RESP2/RESP3"],["REQUEST","array of bulk strings"],["TRANSPORT","TCP / Unix socket"],["CLUSTER BUS","different binary protocol"]],
      ["长度前缀使解析快速且实现简单。","文本化头部有少量字节开销；大 payload 仍会占网络与 client buffers。"],
      "*7\\r\\n $3 SET $17 session:user:9527\n$42 {json-bytes} $2 EX $4 1800 $2 NX", DOC.protocol,
      {layer:"WIRE PROTOCOL", boundary:"RESP 是客户端—服务器协议；Redis Cluster 节点间 gossip/故障检测使用另一套 cluster bus 二进制协议。"}),

    slide("07 · SOCKET BUFFER", "network", "TCP 字节先落在哪里？", "先进入内核 receive buffer，再由可读事件搬到 Redis client query buffer。", "socket",
      ["NIC 收包后，内核把 TCP 字节放入该连接的 receive buffer。","事件多路复用发现 fd readable，Redis 读取到 client query buffer。","若客户端持续发大 pipeline 而服务器来不及处理，输入缓冲与内存压力会增长。"],
      "网络不是透明管道：Kernel socket buffer 与 Redis client buffer 都是可观测、可耗尽的物理边界。",
      [["FD","one connection"],["KERNEL","recv buffer"],["PROCESS","query buffer"],["LIMIT","client-query-buffer-limit"]],
      ["非阻塞 I/O 让单线程管理大量连接。","大 pipeline、慢客户端或超大参数会把内存从数据集转移到连接缓冲。"],
      "onReadable(fd):\n  bytes = read(fd)\n  client.querybuf += bytes\n  while completeRESP(client.querybuf): processOne()", DOC.clients,
      {layer:"LINUX KERNEL → PROCESS", failures:["大请求让 client query buffer 触碰上限，连接被关闭。","网卡/内核已收到数据，但事件循环被慢命令占住，读取延迟增长。"]}),

    slide("08 · EVENT LOOP", "network", "一个线程，怎么同时服务成千连接？", "事件循环只处理“已经就绪”的 fd，避免为每个连接阻塞一个线程。", "event-loop",
      ["aeApiPoll 等待可读、可写与时间事件；就绪列表里只有现在能推进的连接。","文件事件读取/回复客户端；时间事件驱动 serverCron、过期采样等周期任务。","命令效果在主执行路径中依次发生，因此无需给每个 key 加用户可见锁。"],
      "高并发来自 I/O 多路复用与短命令，不是让同一实例同时并行修改所有 key。",
      [["FILE EVENTS","socket readable/writable"],["TIME EVENTS","serverCron"],["EXECUTION","mostly serialized"],["RISK","one long command blocks others"]],
      ["串行语义让原子命令实现直接、缓存局部性好。","单条 O(N) 命令、脚本或 fork 抖动会把延迟传给其他客户端。"],
      "while !stop:\n  ready = poll(fileEvents, nextTimer)\n  for fd in ready: handleFileEvent(fd)\n  processTimeEvents()", DOC.event,
      {layer:"REDIS PROCESS", boundary:"后台线程可以承担 fsync、lazy free 和某些网络 I/O，但从客户端观察，普通命令修改数据集的语义边界仍主要是串行执行。"}),

    slide("09 · I/O THREADS", "network", "Redis 说“单线程”，I/O Threads 又是什么？", "不要把网络读写并行与命令状态变更并行混为一谈。", "io-threads",
      ["现代 Redis 可用线程帮助网络读写或后台任务；这降低大量连接与 TLS 的 I/O CPU。","解析完成的命令仍进入拥有该数据集的主执行序列，避免多线程写共享结构的锁竞争。","所以慢 Lua、KEYS 或大集合运算仍可能阻塞同一实例上的其他客户端。"],
      "I/O Threads 优化“搬字节”，不自动把一条实例变成任意命令并行执行的多核数据库。",
      [["PARALLEL","network/background work"],["SERIAL","command effects"],["TLS","I/O thread support in Redis 8"],["SCALE CPU","shard / instances"]],
      ["在网络 CPU 成瓶颈时提高吞吐。","数据模型与慢命令问题不会被 I/O 线程治好。"],
      "ioThreads.readOrWrite(clientBuffers)\nmainThread:\n  parse → execute command atomically\nbackground: fsync / lazyfree / child process", DOC.latency,
      {layer:"THREAD BOUNDARIES", quiz:"开启 I/O Threads 后，为什么 KEYS 仍会卡住别的请求？", answer:"I/O 线程只帮助读写网络等工作；KEYS 的 keyspace 扫描与命令效果仍占用主执行路径。"}),

    slide("10 · COMMAND GATE", "network", "RESP 解析完，能直接改字典吗？", "命令表、参数数量、ACL、内存与集群状态会先形成一道执行闸门。", "command-gate",
      ["解析首个 Bulk String，查 command table 找到 SET 的处理函数、flags 和 key specs。","校验 arity、ACL 权限、认证、只读状态；Cluster 还要检查 key slot 是否属于本节点。","内存到达 maxmemory 时，写命令可能先触发 eviction；noeviction 则直接报 OOM。"],
      "到达 Redis 不等于一定执行；命令在改变数据集前必须通过协议、权限、拓扑与内存约束。",
      [["LOOKUP","SET command metadata"],["ACL","@write @string"],["MAXMEMORY","evict or OOM"],["CLUSTER","slot ownership"]],
      ["集中校验让命令行为可预测。","复杂 ACL/Cluster/模块环境增加每条命令的固定成本与故障类型。"],
      "cmd = commandTable[argv[0]]\nvalidateArity(cmd, argc); checkACL(client, cmd)\ncheckClusterSlot(keys); enforceMaxmemory(cmd)\ncmd.proc(client)", "https://redis.io/docs/latest/commands/command/",
      {layer:"COMMAND DISPATCH", failures:["ACL 拒绝返回 NOPERM，数据集未改变。","Cluster slot 不在本节点时返回 MOVED/ASK，客户端必须更新路由或临时重定向。"]}),

    slide("11 · KEYSPACE DICT", "memory", "`session:user:9527` 最终写到哪张表？", "一个 logical DB 的主 keyspace 本质上是哈希字典：key → value object。", "keyspace",
      ["先对 key bytes 计算 hash，在 bucket/table 中查找现有 entry。","NX 要求 key 不存在；若已存在（且未过期），本次写返回 null。","不存在时创建 entry，把 key 与 value 的内部对象挂到 db0 keyspace。"],
      "SET 的核心不是写文件，而是在 owning Redis 进程的内存字典中原子替换一个指针关系。",
      [["DATABASE","db0"],["INDEX","hash table"],["LOOKUP","average O(1)"],["REHASH","incremental"]],
      ["平均 O(1) 查找适合低延迟点读写。","每个 key 都有字典 entry、指针和 allocator 元数据，很多小 key 的开销不可忽略。"],
      "entry = db.dict.find(keyBytes)\nif NX && live(entry): return null\nnewValue = createStringObject(valueBytes)\ndb.dict.addOrReplace(keyBytes, newValue)", DOC.memory,
      {layer:"JVM/RAM · DB0", boundary:"逻辑 DB 不是独立进程或磁盘目录；它是同一 Redis 进程里的 keyspace。Cluster 模式通常只使用 DB 0。"}),

    slide("12 · REDIS OBJECT", "memory", "字典 entry 里挂的只是 JSON bytes 吗？", "值外面还有对象元数据，告诉 Redis 类型、编码和淘汰访问信息。", "redis-object",
      ["type 说明这是 String/List/Hash 等逻辑类型。","encoding 说明当前物理布局，例如 int、embstr、raw、listpack、hashtable。","ptr/内嵌区域指向真实内容；LRU/LFU bits 参与近似淘汰，引用/元数据支持生命周期管理。"],
      "同一个 Redis API 类型可以有多种物理编码；Redis 会按大小与内容选择省内存或省 CPU 的布局。",
      [["TYPE","string"],["ENCODING","raw/embstr/int"],["ACCESS META","LRU or LFU"],["PAYLOAD","SDS / aggregate"]],
      ["自适应编码减少小对象内存。","跨阈值转换会消耗 CPU，并可能突然增大占用。"],
      "obj.type = STRING\nobj.encoding = chooseEncoding(valueBytes)\nobj.access = lruClock or lfuCounter\nobj.payload = SDS(valueBytes)", "https://github.com/redis/redis/blob/unstable/src/object.c",
      {layer:"HEAP OBJECT", boundary:"课程用经典 redisObject 心智模型解释 type/encoding/access/payload；新版本源码会继续压缩 key/value 元数据布局，但这些设计职责仍成立。"}),

    slide("13 · STRING ENCODING", "memory", "同是 String，为什么可能是 int、embstr 或 raw？", "逻辑类型不变，Redis 根据内容与长度选择物理表示。", "string-encoding",
      ["纯整数可用整数表示，INCR/DECR 不必反复解析长字符串。","较短字符串可把对象头与 SDS 放在相邻内存块，减少分配和 cache miss。","较长或可修改字符串用 raw/SDS；APPEND 等操作可能触发重新分配或编码变化。"],
      "编码是内存/CPU 的实现细节，业务只依赖 String 命令语义；诊断大 key 时再观察 encoding。",
      [["INT","integer content"],["EMBSTR","short string"],["RAW","long/mutable SDS"],["CHECK","OBJECT ENCODING"]],
      ["紧凑编码节省指针与 allocator 开销。","不要把具体字节阈值写进业务逻辑；它会随版本实现变化。"],
      "if parseInteger(value): encoding=INT\nelse if smallEnoughToEmbed(value): encoding=EMBSTR\nelse: encoding=RAW_SDS", "https://github.com/redis/redis/blob/unstable/src/object.c",
      {layer:"MEMORY LAYOUT", quiz:"为什么课程不让业务依赖 embstr 的固定长度阈值？", answer:"encoding 是版本相关的内部优化，不是 Redis API 契约；业务只应依赖类型和命令语义。"}),

    slide("14 · EXPIRES", "memory", "TTL 是塞进 value object 里的吗？", "Key 的绝对过期时间由专门的 expires 索引管理，value 本身不需要知道 TTL。", "expires-dict",
      ["SET EX 1800 把 now+1800s 计算成绝对毫秒时间。","keyspace 保存 key→value；expires 结构保存同一 key→expireAt。","覆盖、DEL、PERSIST 等操作必须同步维护 value 与过期元数据。"],
      "TTL 是 key 级生命周期元数据；业务读取 value bytes 时不会在 payload 里看到它。",
      [["TTL STORE","expires index"],["VALUE","absolute timestamp"],["ACCURACY","millisecond-scale"],["PERSIST","remove expiry"]],
      ["独立索引让主动过期只采样有 TTL 的 keys。","TTL 需要额外内存；系统时钟跳变会改变绝对到期判断。"],
      "expireAt = wallClockMillis() + 1800_000\ndb.keyspace[key] = valueObject\ndb.expires[key] = expireAt", DOC.expire,
      {layer:"DB0 · LIFECYCLE INDEX", boundary:"本页只讲 TTL 存在哪里；“何时删除”分为访问时惰性过期与后台主动采样，后面单独讲。"}),

    slide("15 · PROPAGATION", "memory", "内存改完后，AOF 与 Replica 谁先谁后？", "命令在主执行路径形成确定结果，再按配置传播到 AOF/复制流；磁盘 fsync 与副本应用有各自时钟。", "propagation",
      ["SET 先在 Primary 的内存数据集形成结果；失败或 NX 未命中不会传播一次成功写。","成功写被编码进 AOF buffer（若开启）和 replication stream（若有 replica）。","后台 fsync、内核写盘、副本接收/应用可能在 +OK 之后才完成。"],
      "默认 +OK 主要证明 Primary 已执行；它不天然证明数据已 fsync 或已被 N 个副本接收。",
      [["MEMORY","command applied"],["AOF","buffer → write/fsync"],["REPLICATION","async stream"],["STRONGER ACK","WAIT / WAITAOF"]],
      ["异步传播保住低延迟。","Primary 突然故障时存在尚未持久化或复制的丢失窗口。"],
      "applyToMemory(command)\nif AOF: append(aofBuffer, canonicalCommand)\nif replicas: append(replicationStream, command)\nreplyAccordingToDurabilityPolicy()", DOC.persistence,
      {layer:"RELIABILITY FAN-OUT", boundary:"具体源码调用顺序随版本演进；教学重点是四个完成点不能合并：内存应用、AOF write、AOF fsync、副本 ACK。"}),

    slide("16 · SUCCESS", "memory", "客户端收到 `+OK`，到底算成功了什么？", "成功语义取决于 appendonly、appendfsync、复制等待和故障切换配置。", "success",
      ["默认 SET：Primary 已完成命令并排队/传播相关副作用，返回 +OK。","appendfsync always 会把每次写的确认与 fsync 更紧地绑定，延迟更高。","WAIT 关注副本已接收；WAITAOF 进一步关注本地/副本 AOF fsync，但仍不是通用强一致事务系统。"],
      "写成功必须用分层语言描述：内存成功、操作系统写入、fsync、Replica ACK、故障转移后保留。",
      [["+OK","primary applied"],["EVERYSEC","≤ about 1s AOF window"],["WAIT","replica received"],["WAITAOF","AOF fsync acknowledgments"]],
      ["可按业务价值选择延迟与数据安全。","更强确认增加 RTT/排队，仍需理解异步故障转移的边界。"],
      "SET key value EX 1800 NX\nif critical: WAIT 1 100\nif durabilityCritical: WAITAOF 1 1 100\nvalidate returned acknowledgements", DOC.wait,
      {layer:"CLIENT ACK", quiz:"WAIT 1 100 返回 0 是命令失败了吗？", answer:"前面的 SET 可能已在 Primary 成功；WAIT 返回实际在超时内确认的副本数。客户端要按业务策略决定告警、重试或降级。"}),

    slide("17 · GET PATH", "lifecycle", "一次 GET，会按什么顺序找到 value？", "读取不是直接拿指针：先路由/校验，再判断 TTL，最后返回 payload bytes。", "get-path",
      ["查 DB keyspace 得到 entry；若 key 有 TTL，先比较 expireAt 与当前时间。","已逻辑过期就删除并当作 miss；未过期则更新访问元数据，用于 LRU/LFU 近似淘汰。","从 String object 取出 bytes，编码成 RESP Bulk String，经输出缓冲发回客户端。"],
      "GET 的命中条件是“key 存在且此刻未过期”；返回后应用再把 bytes 反序列化成 Session。",
      [["LOOKUP","average O(1)"],["TTL CHECK","expireIfNeeded"],["ACCESS","LRU/LFU metadata"],["RETURN","bulk string or null"]],
      ["点查路径短，适合高 QPS。","大 value 会把成本转移到内存带宽、网络与客户端反序列化。"],
      "entry = find(key)\nif expired(entry): delete(key); return null\ntouchAccessMetadata(entry)\nreturn RESP.bulk(entry.value.bytes)", DOC.expire,
      {layer:"READ DATA PATH", boundary:"Replica 读可能返回稍旧数据；本页先讲单个实例的 GET，复制一致性后面再讲。"}),

    slide("18 · PASSIVE EXPIRE", "lifecycle", "TTL 到点，Redis 会立刻给每个 Key 设置闹钟吗？", "不会。访问到已过期 key 时，惰性检查负责立即把它视为不存在。", "passive-expire",
      ["每次相关读写先看 expires 中的绝对时间。","到期就从 keyspace/expires 删除，产生 keyspace 变更。","Primary 会把过期转换成明确的删除传播到 AOF 与 replicas，避免各节点凭本地时钟独立决定。"],
      "逻辑过期发生在时间点；物理回收可能在下一次访问或主动过期周期。",
      [["TRIGGER","key access"],["RESULT","miss + delete"],["PROPAGATE","synthesized delete"],["REPLICA","follows primary deletion"]],
      ["不为百万 TTL key 维护百万定时器。","从不再访问的过期 key 仅靠惰性策略会长期占内存。"],
      "if expires[key] <= now:\n  deleteFromKeyspace(key)\n  propagateDeleteToAOFAndReplicas(key)\n  return EXPIRED", DOC.expire,
      {layer:"ON-ACCESS GC", quiz:"Replica 为什么不自行按本地时间删除复制来的 key？", answer:"Primary 统一产生删除操作并传播，减少时钟偏差造成的副本数据分歧；Replica 被提升后才独立承担过期职责。"}),

    slide("19 · ACTIVE EXPIRE", "lifecycle", "那些永远不再访问的过期 Key，谁来清？", "serverCron 驱动主动过期周期，从有 TTL 的集合采样并在时间预算内清理。", "active-expire",
      ["只从 expires 结构扫描/采样，不遍历全部 keyspace。","若样本中过期比例仍高，周期继续加大工作；达到 CPU 时间预算就让出事件循环。","active-expire-effort 提高清理积极性，也会占更多 CPU。"],
      "主动过期是“内存回收速度 vs 主线程延迟”的受预算垃圾回收，不是整表瞬时清扫。",
      [["DRIVER","serverCron"],["INPUT","keys with TTL"],["BUDGET","time limited"],["TUNE","active-expire-effort"]],
      ["增量采样避免一次全表暂停。","大量 key 同时到期仍会制造 CPU 峰值与删除传播流量。"],
      "do within timeBudget:\n  sample keys from expires\n  delete every expireAt <= now\n  continue while staleRatio remains high", "https://github.com/redis/redis/blob/unstable/src/expire.c",
      {layer:"BACKGROUND GC", failures:["大量相同 TTL 同时到点，expire cycle、AOF 与复制流同时升高。","CPU 紧张时清理追不上，used_memory 暂时包含大量已逻辑过期对象。"]}),

    slide("20 · MEMORY ACCOUNTING", "lifecycle", "为什么 42 字节 JSON，可能占几百字节内存？", "Key、字典 entry、对象头、SDS、allocator 对齐和 TTL 元数据都要付费。", "memory-accounting",
      ["业务 payload 只是其中一层；长 key 名会为每条记录重复付费。","jemalloc size class/碎片让已分配内存不等于数据集逻辑大小。","复制/AOF/client buffers 等某些缓冲还会占用 maxmemory 之外或单独统计的内存。"],
      "容量规划要看每 key 全成本和峰值缓冲，而不是只相加 JSON 字节数。",
      [["PAYLOAD","value bytes"],["OVERHEAD","dict + object + SDS"],["ALLOCATOR","rounding/fragmentation"],["BUFFERS","clients/AOF/replication"]],
      ["元数据换来 O(1) 查找、类型与 TTL。","大量 tiny keys 的内存效率可能远差于聚合到 Hash。"],
      "perKey ≈ keySDS + dictEntry + valueObject\n       + valuePayload + expireMeta + allocatorSlack\npeakRAM += COW + client + repl + AOF buffers", DOC.memory,
      {layer:"PROCESS HEAP", quiz:"为什么把 100 个小字段做成 100 个 keys 常比一个 Hash 贵？", answer:"每个 key 都重复承担 key SDS、字典 entry、对象与 allocator 开销；小 Hash 还能使用 listpack 紧凑编码。"}),

    slide("21 · EVICTION TRIGGER", "lifecycle", "内存超过 maxmemory，Redis 先拒绝还是先删 Key？", "写命令进入执行前后会检查内存；策略决定淘汰候选或返回 OOM。", "eviction-trigger",
      ["新写让 used memory 越过 maxmemory，Redis 进入 eviction cycle。","按 policy 反复选择并删除候选，直到回到目标或找不到可淘汰 key。","noeviction 不删数据，可能增长内存的写命令报 OOM；读命令仍可继续。"],
      "过期是业务生命周期，淘汰是内存压力下的缓存策略；两者触发条件完全不同。",
      [["LIMIT","maxmemory"],["POLICY","maxmemory-policy"],["SAMPLES","maxmemory-samples"],["METRIC","evicted_keys"]],
      ["缓存场景可自动回收冷数据。","把 Redis 当主存储却配置 allkeys 淘汰，可能静默丢业务数据。"],
      "while memory > maxmemory:\n  victim = policy.sampleAndChoose()\n  if victim == none: return OOM\n  deleteAndPropagate(victim)", DOC.eviction,
      {layer:"MEMORY PRESSURE", boundary:"maxmemory 通常要给复制、AOF、客户端缓冲与 fork COW 留余量；不能简单设成机器总 RAM。"}),

    slide("22 · LRU / LFU", "lifecycle", "Redis 的 LRU/LFU，是精确排序全量 Key 吗？", "不是。Redis 采样少量候选，用每对象访问元数据做近似选择。", "lru-lfu",
      ["LRU 近似选择最久未访问的候选；LFU 用衰减频率近似保留长期热点。","allkeys-* 从所有 key 选；volatile-* 只从有 TTL 的 keys 选。","样本数越大越接近理想策略，但每次淘汰的 CPU 成本也更高。"],
      "近似算法用少量元数据与采样换取接近理想缓存的效果。",
      [["ALLKEYS-LRU","recency"],["ALLKEYS-LFU","frequency"],["VOLATILE-*","TTL keys only"],["NOEVICTION","reject writes"]],
      ["低成本、无需全局链表。","策略与业务访问分布不匹配时，命中率会明显下降。"],
      "candidates = randomSample(keyspace, N)\nscore = policy == LRU ? idleTime : lowFrequency\nevict(argmax(score))", DOC.eviction,
      {layer:"APPROXIMATE CACHE", quiz:"为什么 volatile-lru 在没有 TTL key 时可能无法释放内存？", answer:"它只允许从带过期时间的 key 集合选候选；若集合为空或太小，写入可能收到 OOM。"}),

    slide("23 · DEL / UNLINK", "lifecycle", "删除一个大 Key，为什么 `UNLINK` 往往更平滑？", "从 keyspace 摘除指针与真正递归释放对象，是两个不同成本。", "lazyfree",
      ["DEL 通常在命令路径移除并释放对象；大集合释放可能长时间占主线程。","UNLINK 先让 key 对新请求不可见，再把满足条件的对象释放工作交给 lazy-free 后台线程。","lazyfree-lazy-* 配置可让过期、淘汰、用户删除等路径异步回收。"],
      "逻辑删除可以很快，物理 free 仍需要 CPU；UNLINK 把这笔成本移出关键延迟路径。",
      [["DEL","synchronous free"],["UNLINK","asynchronous free"],["VISIBLE","immediate removal"],["METRIC","lazyfree_pending_objects"]],
      ["降低删除 big key 的主线程卡顿。","后台释放仍消耗 CPU/内存带宽，且内存不会在同一瞬间全部归还。"],
      "value = keyspace.unlink(key)\nif shouldLazyFree(value): queue(backgroundFree, value)\nelse: free(value)\nreturn removedCount", "https://redis.io/docs/latest/commands/unlink/",
      {layer:"LOGICAL VS PHYSICAL DELETE", quiz:"UNLINK 返回后，为什么 RSS 可能暂时没降？", answer:"Key 已从逻辑 keyspace 消失，但后台线程还在释放成员；allocator 也可能保留 arena 页面而不立刻归还 OS。"}),

    slide("24 · HASH", "structure", "一个 Hash，在内存里到底是 listpack 还是 hashtable？", "小 Hash 优先连续紧凑布局，跨过条目/值阈值后转成字典。", "hash",
      ["小 field/value 对按 listpack 连续存放，指针少、cache locality 好。","元素数量或单值超过阈值后，自动转换为真正的 hashtable。","转换后 HGET/HSET 平均 O(1)，但每 field 的内存开销增加。"],
      "Redis 用“小时省内存、大时保性能”的编码切换实现同一种 Hash API。",
      [["SMALL","listpack"],["LARGE","hashtable"],["TUNE","hash-max-listpack-*"],["TTL","key-level; field expiry version-dependent"]],
      ["小对象可节省数倍内存并利用 CPU cache。","阈值设太大，线性查找和一次性转换会造成抖动。"],
      "if entries <= maxEntries && eachValue <= maxValue:\n  encode = LISTPACK\nelse:\n  convertToHashtable()", DOC.memory,
      {layer:"TYPE → ENCODING", boundary:"新版本支持更细粒度的 Hash field expiration，但普通 key TTL 与 field TTL 仍是不同生命周期机制。"}),

    slide("25 · LIST", "structure", "List 为什么不是一条巨大的双向链表？", "Quicklist 把多个紧凑 listpack 作为节点，平衡局部连续性与两端操作。", "list",
      ["每个 quicklist node 包含一段 listpack；节点之间双向链接。","LPUSH/RPUSH 在端部 listpack 操作；过大时分裂为更多节点。","压缩深度等配置可让中间节点压缩，端部保留便于快速修改。"],
      "Quicklist 在纯链表的指针开销与单一大数组的搬移成本之间折中。",
      [["LOGICAL","ordered sequence"],["PHYSICAL","quicklist + listpack"],["ENDS","O(1) style operations"],["RISK","large LRANGE/LREM"]],
      ["端部快，小元素内存紧凑。","大范围遍历、删除和返回大量成员仍是 O(N) 并阻塞网络。"],
      "node = chooseHeadOrTailNode()\nif node.hasRoom: listpack.push(value)\nelse: quicklist.link(newListpack(value))", "https://redis.io/docs/latest/develop/data-types/lists/",
      {layer:"COMPOSITE STRUCTURE"}),

    slide("26 · SET", "structure", "Set 为什么有 intset、listpack 和 hashtable 多种形态？", "Redis 根据成员是否为整数、集合大小与版本能力选择紧凑或通用编码。", "set",
      ["纯整数小集合可用排序 intset；新版本也可对小普通成员使用 listpack。","成员变复杂或超过阈值时转为 hashtable，SISMEMBER 平均 O(1)。","SINTER/SUNION 等集合运算的成本取决于参与集合的基数，不是命令名字短就快。"],
      "Set 的点查很快，但跨大集合运算仍会占用主执行路径。",
      [["INT ONLY","intset"],["SMALL","listpack (newer Redis)"],["GENERAL","hashtable"],["CHECK","OBJECT ENCODING"]],
      ["自动紧凑编码节省小集合内存。","编码转换与大集合运算可能形成延迟尖峰。"],
      "if allIntegers && small: INTSET\nelse if smallAndShort: LISTPACK\nelse: HASHTABLE\nSADD(currentEncoding, member)", DOC.memory,
      {layer:"ADAPTIVE ENCODING"}),

    slide("27 · SORTED SET", "structure", "ZSet 如何同时支持按 member 查分数、又按 score 排序？", "大 ZSet 同时维护 dictionary 与 skiplist，两份索引服务两类访问。", "zset",
      ["dictionary 提供 member→score 的平均 O(1) 查找。","skiplist 按 score/member 排序，支持 rank 与区间遍历。","小 ZSet 可用 listpack 省内存；变大后转成 dict+skiplist。"],
      "ZSet 用额外空间维护两种访问路径，换来点查与有序范围都高效。",
      [["POINT","dict member→score"],["ORDER","skiplist"],["SMALL","listpack"],["UPDATE","touch both indexes"]],
      ["排行榜、延迟队列的核心操作高效。","每个 member 同时出现在两套结构中，内存成本高于普通 Set。"],
      "old = dict[member]\nif old: skiplist.remove(old, member)\ndict[member] = score\nskiplist.insert(score, member)", "https://redis.io/docs/latest/develop/data-types/sorted-sets/",
      {layer:"DUAL INDEX"}),

    slide("28 · STREAM", "structure", "Stream 的消息、ID 与 Consumer Group 存在哪里？", "消息序列与消费组状态是两套结构：一套保存 entries，一套保存 group/PEL。", "stream",
      ["XADD 生成单调 ID，把 field/value entries 压进 radix tree 组织的 listpacks。","Consumer Group 保存 last-delivered-id；每个消费者的 Pending Entries List 记录已投递未 ACK 的消息。","XACK 只清 PEL，不删除 Stream entry；XDEL/XTRIM 才改变消息保留。"],
      "Redis Stream 同时维护不可混淆的“消息日志位置”和“消费确认状态”。",
      [["ENTRIES","radix tree + listpacks"],["ID","ms-seq"],["GROUP","last delivered"],["PEL","pending acknowledgements"]],
      ["提供消费组、重试和 claim 能力。","PEL 与消息保留需独立治理；大量 pending 会占内存并增加恢复成本。"],
      "id = XADD(stream, fields)\nentry = XREADGROUP(group, consumer)\nPEL[group][id] = consumer\nXACK(group, id) removes PEL only", "https://redis.io/docs/latest/develop/data-types/streams/",
      {layer:"LOG + DELIVERY STATE", quiz:"XACK 后消息为什么还在 XRANGE 里？", answer:"XACK 只表示该 Group 的 pending 已确认；Stream entry 的保留由 XDEL/XTRIM/MAXLEN 等策略决定。"}),

    slide("29 · SPECIAL TYPES", "structure", "Bitmap、HyperLogLog、Geo、Vector Set，各自省掉了什么？", "它们不是万能容器，而是为特定查询压缩状态或建立专用索引。", "special-types",
      ["Bitmap/Bitfield 把布尔或小整数压进 String bits；HyperLogLog 用固定量级内存估算基数。","Geo 底层利用 Sorted Set 的 geospatial score 做半径/距离查询。","Redis 8 的 Vector Set 为向量相似度维护专用结构；它与普通 String 存 embedding 不是一回事。"],
      "选数据类型就是选成本模型：精确性、内存、更新和查询能力不能同时免费。",
      [["BITMAP","dense flags"],["HLL","approx cardinality"],["GEO","spatial lookup"],["VECTOR SET","similarity search"]],
      ["专用结构把常见问题压缩成高效命令。","误用会牺牲精度、可解释性或增加重建/维护成本。"],
      "choose by question:\nflags → bitmap; unique estimate → HLL\nnearby → GEO; semantic neighbors → vector set", DOC.types,
      {layer:"PURPOSE-BUILT INDEXES"}),

    slide("30 · PIPELINE", "composition", "Pipeline 为什么快，它保证原子吗？", "Pipeline 把多个命令连续写入连接，减少 RTT；它默认不等于服务端事务。", "pipeline",
      ["客户端先把多条 RESP 命令缓存或连续发送，不逐条等回复。","Redis 仍按顺序执行并把回复排进 output buffer。","客户端最终按相同顺序读取 replies；pipeline 过大时双方缓冲都会膨胀。"],
      "Pipeline 优化往返与系统调用，不自动提供全有或全无、隔离或回滚。",
      [["SAVES","RTT + syscalls"],["ORDER","replies ordered"],["ATOMIC","no"],["BATCH","bounded"]],
      ["小命令批量吞吐显著提升。","巨型 pipeline 增加内存、尾延迟和断线后的不确定重试范围。"],
      "for cmd in batch: socket.write(RESP(cmd))\nfor cmd in batch: replies.append(socket.readReply())\n// other clients may run between commands", DOC.pipeline,
      {layer:"CLIENT BATCHING", quiz:"Pipeline 中第 3 条失败，第 4 条会自动回滚吗？", answer:"不会。每条命令有自己的回复；Pipeline 只是批量通信。需要原子组合时用单命令、MULTI/EXEC 或 Function/Lua。"}),

    slide("31 · MULTI / EXEC", "composition", "Redis Transaction 为什么没有数据库式回滚？", "MULTI 后命令先排队，EXEC 时连续执行；运行期错误按命令返回，不回滚已执行结果。", "transaction",
      ["MULTI 打开队列；普通命令返回 QUEUED，不立即改数据。","EXEC 让已排队命令不被其他客户端命令插入地依次执行。","WATCH 提供乐观锁：被观察 key 在 EXEC 前变化，整个 EXEC 返回空，客户端重试。"],
      "Redis Transaction 的核心是“连续执行 + 可选 CAS”，不是 undo log 与任意回滚。",
      [["QUEUE","MULTI"],["COMMIT","EXEC"],["CAS","WATCH"],["ROLLBACK","no runtime rollback"]],
      ["简单、低锁开销，适合短小原子批次。","事务中某条类型错误不撤销之前成功命令；客户端必须检查每个 reply。"],
      "WATCH balance\ncurrent = GET balance\nMULTI; SET balance current-10; INCR audit\nif EXEC == null: retryWithBackoff()", DOC.tx,
      {layer:"OPTIMISTIC ATOMICITY"}),

    slide("32 · LUA / FUNCTIONS", "composition", "什么时候该把逻辑搬进 Redis？", "多步读改写需要少 RTT 且必须原子时，Function/Lua 可在数据旁执行。", "lua-functions",
      ["脚本/Function 在服务端读取多个 keys、计算并写回，期间命令效果原子可见。","所有 keys 必须显式声明；Cluster 中多 key 还必须落同一 slot。","脚本运行时会阻塞其他活动，长循环或大返回值会把低延迟实例变成队头阻塞。"],
      "服务端代码用数据局部性与原子性换取主线程执行时间；逻辑必须短、可界定、可观测。",
      [["EVAL","send/run script"],["FUNCTION","stored library"],["ATOMIC","yes"],["RISK","blocks while running"]],
      ["省 RTT，避免客户端读改写竞态。","调试、版本管理和长脚本阻塞成本更高。"],
      "function reserve(keys, args):\n  stock = GET(keys[0])\n  if stock < qty: return 0\n  DECRBY(keys[0], qty); return 1", DOC.functions,
      {layer:"SERVER-SIDE LOGIC", quiz:"为什么长 Lua 即使只操作一个 key，也会影响其他 clients？", answer:"脚本在 Redis 执行路径上原子运行，期间其他命令无法插入；长 CPU 循环会占住同一事件循环。"}),

    slide("33 · CACHE-ASIDE", "cache", "业务最常用的 Cache-Aside，完整 flow 是什么？", "Redis miss 后回源数据库、写回 TTL；正确性取决于数据库更新与缓存失效顺序。", "cache-aside",
      ["读：GET → hit 直接返回；miss → 查 DB → SET EX 回填。","写：先提交 DB，再 DEL/UNLINK cache；下一次读重新回填。","并发读写仍可能把旧值回填，需版本、延迟双删、CDC 或更明确的一致性方案。"],
      "Cache-Aside 让缓存成为可丢的派生副本；源数据库才是权威。",
      [["READ","hit or DB fallback"],["WRITE","DB then invalidate"],["TTL","safety net"],["SOURCE","database"]],
      ["实现简单、按需缓存热点。","短暂不一致、回源压力和删除失败必须被显式治理。"],
      "v = GET(k)\nif v == null: v = DB.read(k); SET(k,v,EX,jitter)\nDB.update(k,newV); DEL(k)", "https://redis.io/docs/latest/develop/clients/patterns/",
      {layer:"APPLICATION CONSISTENCY", boundary:"不要把 Redis 的单命令原子性误当成 Redis 与 MySQL 之间的分布式事务。"}),

    slide("34 · PENETRATION", "cache", "不存在的数据被反复请求，为什么能打穿缓存？", "每次 miss 都回源数据库；攻击或异常参数会把缓存绕开。", "penetration",
      ["请求一个永不存在的 id，GET miss。","数据库也 miss；若不缓存“空”，下一次完全重复同一路径。","可用短 TTL 的 negative cache、Bloom Filter、参数校验和限流组合防护。"],
      "缓存穿透的根因不是 Redis 慢，而是“不可命中的请求没有便宜的终止状态”。",
      [["SYMPTOM","Redis miss + DB miss"],["FIX 1","negative cache"],["FIX 2","Bloom filter"],["FIX 3","validation/rate limit"]],
      ["负缓存快速止损。","空值 TTL 太长会遮挡刚创建的数据；Bloom Filter 有假阳性与维护成本。"],
      "if !bloom.mightContain(id): return NOT_FOUND\nv = cache.get(id)\nif miss: v=DB.get(id); cache.set(id,v??NULL,shortTTL)", "https://redis.io/docs/latest/develop/clients/patterns/",
      {layer:"MISS CONTROL"}),

    slide("35 · STAMPEDE", "cache", "一个热点 Key 过期，为什么会拖垮数据库？", "大量并发在同一瞬间 miss，并同时回源做相同昂贵工作。", "stampede",
      ["热点 key TTL 到点，数千请求同时 GET miss。","若所有请求都查 DB/远端 API，后端瞬时放大；回填还会相互覆盖。","single-flight/互斥锁让一个请求重建；其他等待、返回 stale 或使用逻辑过期。"],
      "缓存击穿要控制“谁有资格重建”，而不仅是把 TTL 调长。",
      [["SINGLE FLIGHT","one loader"],["STALE-WHILE-REVALIDATE","serve old"],["TTL JITTER","spread expiry"],["LOCK","must expire"]],
      ["合并回源保护数据库。","分布式锁超时、持有者故障和慢重建会引入新的边界。"],
      "v = GET(k)\nif miss && SET(lock:k,token,NX,PX,3000): rebuild()\nelse: waitBrieflyOrServeStale()\nreleaseOnlyIfTokenMatches()", "https://redis.io/docs/latest/develop/clients/patterns/distributed-locks/",
      {layer:"LOAD COLLAPSE", quiz:"为什么锁一定要有 TTL 且释放要校验 token？", answer:"TTL 防持有者崩溃后死锁；token 防止旧持有者在锁过期并被别人获得后误删新锁。"}),

    slide("36 · AVALANCHE", "cache", "很多 Key 同时过期，和单个热点击穿有何不同？", "雪崩是大面积 miss 同时发生，通常由同 TTL、节点故障或冷启动触发。", "avalanche",
      ["批量导入时给大量 key 相同 TTL，于同一秒集中到期。","Redis 故障/切换或大范围 eviction 也会让原本命中的流量突然回源。","TTL 加随机抖动、分级缓存、预热、回源限流/熔断共同削峰。"],
      "击穿关注一个热点 key；雪崩关注一大片 key 或整个缓存层同时失效。",
      [["JITTER","base ± random"],["PREWARM","known hot set"],["BACKPRESSURE","limit DB concurrency"],["FALLBACK","degrade"]],
      ["随机 TTL 把回源摊到时间轴。","抖动不是高可用；整节点故障仍需要副本与业务降级。"],
      "ttl = baseTTL + random(-jitter,+jitter)\ncache.set(k,v,EX,ttl)\nloaderPool.limitConcurrency(); circuitBreaker.protectDB()", "https://redis.io/docs/latest/develop/clients/patterns/",
      {layer:"SYSTEMIC MISS"}),

    slide("37 · HOT KEY", "cache", "总 QPS 不高，为什么一个 Redis Core 仍然打满？", "流量可能集中到一个 key、一个 slot 或一条超大回复。", "hot-key",
      ["单 key 的高频 GET/INCR 全落同一 owning shard，Cluster 不能把一条 key 自动拆到多 cores。","本地缓存、读副本、请求合并、拆分计数器等方案改变热点的物理落点。","拆 key 会牺牲强原子语义，需要异步聚合或近似结果。"],
      "扩容节点不自动解决 hot key；必须让请求或状态真正分散。",
      [["SYMPTOM","one shard/core saturated"],["READ","local cache / replicas"],["WRITE","sharded counters"],["OBSERVE","per-key/app metrics"]],
      ["分散热点可线性利用更多资源。","聚合延迟、一致性与实现复杂度上升。"],
      "bucket = hash(requestId) % 64\nINCR counter:{campaign}:bucket\nread = SUM(all buckets) // async or periodic", "https://redis.io/docs/latest/operate/rs/monitoring/observability/",
      {layer:"SKEWED LOAD", boundary:"Redis Open Source 不建议用 MONITOR 长时间找热点；优先应用侧 key 标签、采样或受控工具，避免观测本身放大负载。"}),

    slide("38 · BIG KEY / SCAN", "cache", "Big Key 与 `KEYS *` 为什么能卡住所有人？", "单线程执行意味着 O(N) 扫描、巨大集合运算和大回复会形成队头阻塞。", "big-key",
      ["Big Key 不只占内存：删除、复制、持久化、网络回复和恢复都更贵。","KEYS 遍历整个 keyspace 并一次返回；SCAN 用 cursor 分批推进，但不是免费快照。","HGETALL/SMEMBERS/LRANGE 也可能在一个集合内部制造大回复。"],
      "危险不是命令名字，而是 N、元素大小、回复字节数和主线程连续占用时间。",
      [["AVOID","KEYS in production"],["USE","SCAN + bounded COUNT"],["MEASURE","MEMORY USAGE"],["LIMIT","response cardinality"]],
      ["增量扫描把工作切片，降低单次阻塞。","SCAN 可能重复返回，且遍历期间 keyspace 变化；调用方要幂等去重。"],
      "cursor=0\ndo:\n  cursor,keys = SCAN(cursor,COUNT=bounded)\n  processIdempotently(keys)\nwhile cursor != 0", DOC.scan,
      {layer:"CARDINALITY COST", quiz:"SCAN COUNT 1000 保证每次正好返回 1000 个 key 吗？", answer:"不保证。COUNT 是工作量提示；返回数量可多可少，终止条件是 cursor 回到 0。"}),

    slide("39 · RDB SNAPSHOT", "persistence", "RDB 快照时，Redis 会暂停所有写吗？", "通常 fork 子进程生成快照；父进程继续服务，修改的内存页触发 Copy-on-Write。", "rdb",
      ["父进程 fork；页表复制与内核调度会产生短暂停顿，数据集越大越敏感。","子进程遍历 fork 时刻的内存视图，写临时 RDB 文件。","父进程继续写；被修改页面复制成新物理页，COW 造成额外峰值 RAM；完成后临时文件原子 rename。"],
      "RDB 把“长时间序列化”移到子进程，但 fork 与 COW 的内存/延迟成本仍由机器承担。",
      [["SNAPSHOT","point in time"],["WORKER","child process"],["PEAK RAM","COW dirty pages"],["INSTALL","atomic rename"]],
      ["文件紧凑，备份与冷启动通常快。","两次快照之间的写可能丢；高写入率下 COW 会显著抬高内存。"],
      "child = fork()\nif child: serialize(snapshotView) → temp.rdb; rename()\nelse: keepServing(); changedPage → COW copy", DOC.persistence,
      {layer:"PROCESS + VM + DISK", failures:["内存过满导致 fork 失败或 COW 峰值触发 OOM。","存储慢让 child 存活更久，期间更多页面被写脏并复制。"]}),

    slide("40 · AOF", "persistence", "AOF 是先写文件再改内存，还是反过来？", "命令先形成内存结果，再把可重放的写追加到 AOF buffer；write/fsync 按策略推进。", "aof",
      ["成功写被转成 canonical command，追加到进程内 AOF buffer。","事件循环把 buffer write 到内核 page cache；write 成功不等于磁盘已持久。","appendfsync always/everysec/no 决定 fsync 频率与延迟/丢失窗口。"],
      "Indexing path 的正确心智是 Memory → AOF Buffer → OS Page Cache → Durable Media。",
      [["ALWAYS","fsync each write group"],["EVERYSEC","fsync about once/sec"],["NO","OS decides"],["FORMAT","RESP-style commands"]],
      ["AOF 丢失窗口通常小且可审计重放。","文件更大、写放大与 fsync 抖动会影响尾延迟。"],
      "apply(command)\naofBuffer += encodeCanonical(command)\nwrite(fd,aofBuffer)\nfsync according to appendfsync", DOC.persistence,
      {layer:"AOF WRITE PATH", quiz:"write(2) 成功为什么还不能叫落盘？", answer:"write 通常只把 bytes 交给内核 page cache；只有 fsync/fdatasync 等持久化边界才要求把脏页推向稳定介质。"}),

    slide("41 · AOF REWRITE", "persistence", "AOF 一直追加，怎么避免无限变大？", "Rewrite 根据当前数据集生成更短 BASE，同时把期间新写收进 INCR AOF。", "aof-rewrite",
      ["子进程/后台重写当前内存状态：同一个 key 的千次修改可压缩成恢复所需的最终状态。","Rewrite 期间父进程继续把新命令写入当前 incremental AOF。","完成后用 manifest 原子切换 BASE + INCR 文件集合，旧历史文件再清理。"],
      "AOF Rewrite 不是在线编辑旧文件，而是旁路构建新基线，再原子替换清单。",
      [["BASE","snapshot representation"],["INCR","new commands"],["MANIFEST","ordered file set"],["TRIGGER","auto-aof-rewrite-* / BGREWRITEAOF"]],
      ["压缩历史，缩短恢复时间。","重写期间有 fork/COW、磁盘 I/O 与 rewrite buffer 成本。"],
      "fork rewrite child → write new BASE\nparent continues appending INCR\non complete: persist new manifest atomically\nbackground unlink old history", "https://github.com/redis/redis/blob/unstable/src/aof.c",
      {layer:"MULTI-PART AOF", boundary:"现代 Redis 使用 multi-part AOF：BASE、一个或多个 INCR 以及 manifest；不要再用“永远只有一个 appendonly.aof”理解生产目录。"}),

    slide("42 · RESTART RECOVERY", "persistence", "Redis 重启后，从 RDB 还是 AOF 恢复？", "开启 AOF 时通常优先用 AOF 表示更完整的写历史；具体由配置与文件完整性决定。", "recovery",
      ["读取配置与 AOF manifest；按 BASE→INCR 顺序重放，重建内存 keyspace 与 TTL。","只启 RDB 时加载最近 snapshot；绝对过期时间意味着停机期间时间仍流逝。","损坏/截断文件要通过启动日志与 redis-check-aof/rdb 判断，不能静默猜测。"],
      "持久化的终点不是文件生成，而是可验证地在目标 RTO 内重建一致的内存状态。",
      [["AOF ENABLED","load AOF set"],["RDB ONLY","load latest snapshot"],["TTL","absolute time"],["TEST","restore drill"]],
      ["AOF+RDB 可平衡恢复速度与丢失窗口。","配置错误、磁盘损坏和恢复时间仍需演练；有文件不等于满足 RPO/RTO。"],
      "if appendonly:\n  load(BASE); replay(each INCR in manifest)\nelse: load(latestRDB)\ndrop keys whose expireAt <= now", DOC.persistence,
      {layer:"BOOT PATH", quiz:"把 RDB 从时钟快 10 分钟的机器搬来有什么风险？", answer:"TTL 保存为绝对时间；目标机时钟差异可能让一批 keys 立即过期或多活一段时间。"}),

    slide("43 · REPLICATION FLOW", "replication", "Replica 是拉数据，还是 Primary 主动写过去？", "初次握手由 Replica 发起 PSYNC；建立流后，Primary 持续把写命令流发送给 Replica。", "replication",
      ["Replica 连接 Primary，发送 PSYNC 携带已知 replication ID 与 offset。","同步完成后，Primary 把产生的数据集变更写进 replication stream 并发送；Replica 顺序读取并应用。","Replica 定期 ACK 已处理 offset，Primary 用它观测延迟并支持 WAIT。"],
      "连接由 Replica 发起；稳定期的数据流是 Primary → Replica 的命令字节流，ACK 反向回来。",
      [["HANDSHAKE","Replica → PSYNC"],["DATA","Primary → command stream"],["ACK","Replica → offset"],["DEFAULT","asynchronous"]],
      ["异步复制让 Primary 写延迟低。","Replica 落后或网络分区时，Primary 已确认的最新写可能尚未到达可提升副本。"],
      "replica: PSYNC(replid, offset)\nprimary: stream commands after offset\nreplica: apply in order; REPLCONF ACK processedOffset", DOC.replication,
      {layer:"PRIMARY ↔ REPLICA", quiz:"说 Replica 是“拉模式”还是“推模式”哪个更准确？", answer:"会话由 Replica 连接并请求同步；稳定复制流由 Primary 连续发送，Replica 消费并 ACK。用完整时序比单个标签更准确。"}),

    slide("44 · FULL / PARTIAL SYNC", "replication", "短暂断线后，为什么有时只补增量，有时全量同步？", "Replication ID + offset 标识历史位置；backlog 是否覆盖缺口决定能否部分同步。", "psync",
      ["Primary 为复制历史维护 replid 与单调 byte offset，并用 backlog 保留最近一段流。","Replica 重连带上旧 replid/offset；仍在 backlog 窗口内则从断点续传。","历史不匹配或缺口已被覆盖时进行 full resync：生成/发送 RDB，再追赶缓冲中的增量。"],
      "replication backlog 是网络抖动的恢复窗口；它太小会把短断线升级成昂贵全量复制。",
      [["IDENTITY","replid"],["POSITION","offset"],["WINDOW","repl-backlog-size"],["FALLBACK","full resync"]],
      ["Partial resync 快且省网络/CPU。","更大 backlog 占 RAM；full sync 会引入 fork、RDB 传输与加载压力。"],
      "if replidMatches && requestedOffset in backlog:\n  send backlog[requestedOffset:]\nelse:\n  fullSync(RDB); then send buffered delta", DOC.replication,
      {layer:"RECOVERY WINDOW"}),

    slide("45 · WAIT / WAITAOF", "replication", "怎样让关键写多等一会，换更小丢失窗口？", "写后在同一连接执行 WAIT/WAITAOF，按返回 ACK 数判断可靠性目标。", "wait",
      ["WAIT N timeout 等待之前写命令被 N 个 replicas 接收/确认处理 offset。","WAITAOF 可等待本地与副本 AOF fsync 数量，提供更明确的持久化 ACK。","超时返回实际 ACK 数；它不撤销前面的写，也不把 Redis 变成共识型强一致数据库。"],
      "可靠性增强是每条关键写的显式协议，不是看到 WAIT 返回就假设线性一致。",
      [["WAIT","replication ACK"],["WAITAOF","AOF fsync ACK"],["TIMEOUT","returns actual count"],["SCOPE","previous writes on connection"]],
      ["显著降低常见故障下的数据丢失概率。","增加请求延迟并依赖副本/磁盘健康；故障切换规则仍可能丢最新历史。"],
      "SET critical:key value\nacks = WAIT 1 100\nif acks < 1: mark durabilityDegraded\n// write may already exist on primary", DOC.wait,
      {layer:"CLIENT-CONTROLLED ACK"}),

    slide("46 · SENTINEL", "replication", "Sentinel 怎么判断 Primary 挂了，并选出新 Primary？", "多个 Sentinel 独立监控；从主观下线到客观下线，再由获选 leader 执行 failover。", "sentinel",
      ["单个 Sentinel 超过 down-after-milliseconds 未获有效回复，标记 SDOWN。","足够 Sentinels 同意达到 quorum，形成 ODOWN；随后通过 epoch/投票选 leader Sentinel。","Leader 选择合适 Replica 提升，重配置其余 Replicas，并让支持 Sentinel 的 clients 发现新地址。"],
      "quorum 用于客观故障判断；授权 failover 还需要多数 Sentinel 的投票，两个概念不要混。",
      [["RECOMMEND","at least 3 Sentinels"],["SDOWN","local opinion"],["ODOWN","quorum agreement"],["FAILOVER","leader + epoch"]],
      ["不分片也能自动发现与切换 Primary。","异步复制意味着已 ACK 写仍可能在切换中丢失；网络/NAT/时钟配置很关键。"],
      "if localTimeout: SDOWN\nif peerVotes >= quorum: ODOWN\nleader = electSentinel(epoch)\nleader.promote(bestReplica); reconfigureOthers()", DOC.sentinel,
      {layer:"CONTROL PLANE", quiz:"配置 quorum=2，为什么仍建议 3 个 Sentinel？", answer:"quorum 决定 ODOWN；真正授权 failover 还需多数 Sentinel 可达。3 个分散故障域的实例才能容忍一个 Sentinel 故障。"}),

    slide("47 · CLUSTER SLOTS", "cluster", "Redis Cluster 为什么不是直接 `hash(key) % nodeCount`？", "Key 先映射到固定 16384 slots，slot 再归属某个 master，节点变化只迁 slots。", "cluster-slots",
      ["slot = CRC16(key) mod 16384；每个 master 负责一段或若干 slots。","每个节点缓存完整 slot→master 拓扑，并通过 cluster bus 的 heartbeat/UPDATE 传播。","扩缩容迁移 slots 及其 keys，不要求所有 key 因 nodeCount 改变而重新取模。"],
      "固定中间层 Slot 把 key 分布与节点数量解耦，是 Cluster 可在线 reshard 的关键。",
      [["SLOTS","16384"],["HASH","CRC16 mod 16384"],["OWNER","one master per stable slot"],["REPLICA","per master"]],
      ["水平分片并支持逐 slot 迁移。","跨 slot 多 key 操作受限；客户端必须理解拓扑与重定向。"],
      "slot = CRC16(keyBytes) % 16384\nmaster = localSlotTable[slot]\nsend command to master", DOC.cluster,
      {layer:"DISTRIBUTION LAYER"}),

    slide("48 · HASH TAGS", "cluster", "`{user:9527}` 为什么能让多个 Key 落到同一 Slot？", "Cluster 只 hash 第一对有效花括号中的子串，给相关多 key 操作一个共址工具。", "hash-tags",
      ["`cart:{user:9527}` 与 `coupon:{user:9527}` 都只 hash `user:9527`。","Lua/MULTI/MGET 等涉及多个 keys 时，共 slot 才能在一个 owning master 原子执行。","Tag 粒度过粗会把一个大租户/业务全部压到单 slot，制造热点。"],
      "Hash Tag 是共址与原子性的设计工具，也可能破坏负载均衡。",
      [["KEY A","cart:{user:9527}"],["KEY B","lock:{user:9527}"],["SLOT","same"],["RISK","hot tag"]],
      ["保留相关 keys 的单节点原子操作。","不均匀 tag 会造成 hot slot，扩节点也无法拆开。"],
      "hashInput = firstValidSubstringInsideBraces(key) ?? key\nslot = CRC16(hashInput) % 16384", DOC.cluster,
      {layer:"CO-LOCATION CONTRACT", quiz:"把所有 key 都写成 `{app}:...` 会怎样？", answer:"所有 keys 只 hash app，全部落一个 slot/master，Cluster 的分片能力几乎被废掉。"}),

    slide("49 · MOVED / ASK", "cluster", "客户端发错节点，MOVED 与 ASK 有什么区别？", "MOVED 表示稳定归属已改变；ASK 表示 slot 正在迁移，本次临时去目标节点。", "redirects",
      ["客户端 slot cache 过期或随机连到错误节点，收到 `MOVED slot host:port`，更新长期拓扑并重试。","Reshard 期间，源节点对已迁移/缺失 key 返回 ASK；客户端先向目标发 ASKING，再只重试本次命令。","Cluster-aware client 自动处理；普通客户端会把重定向当错误暴露给业务。"],
      "MOVED 更新“以后去哪”；ASK 只说明“迁移中的这一次去哪”。",
      [["MOVED","permanent mapping"],["ASK","temporary during migration"],["ASKING","next command only"],["CLIENT","slot cache"]],
      ["客户端直连 owning master，数据路径短。","拓扑抖动或大规模迁移会增加重试、连接与尾延迟。"],
      "reply = send(slotOwnerCache[slot])\nif MOVED: updateCache(slot,newNode); retry\nif ASK: send(newNode,ASKING); retryOnce", DOC.cluster,
      {layer:"CLIENT ROUTING", failures:["客户端无限重定向重试，拓扑不稳定时形成流量放大。","NAT/announce 地址错误，MOVED 给出业务不可达地址。"]}),

    slide("50 · CLUSTER FAILOVER", "cluster", "一个 Master 挂掉后，Replica 如何接管它的 Slots？", "Cluster gossip 形成故障判断；Replica 竞选并用更高 configEpoch 宣告新的 slot 归属。", "cluster-failover",
      ["节点间 PING/PONG gossip 传播可达性与 slot/epoch 信息，多数 master 形成 FAIL 判断。","故障 master 的 Replica 等待/竞选，获得授权后提升为 master，接管原 slots。","其他节点通过 heartbeat/UPDATE 学到更高 configEpoch 的归属，客户端再经 MOVED 刷新。"],
      "Cluster 能自动恢复 slot 服务，但异步复制与网络分区决定了可用性和最新写保留窗口。",
      [["FAILURE","majority masters view"],["ELECTION","replica authorization"],["OWNERSHIP","configEpoch"],["CLIENT","refresh via MOVED"]],
      ["分片与副本故障转移一体化。","少数侧为避免 split-brain 会停止服务；最新未复制写可能丢失。"],
      "if mastersMajorityMarksFail(oldMaster):\n  replica.requestVotes(newEpoch)\n  if authorized: promote(); claimSlots(newEpoch)\n  gossip new ownership", DOC.cluster,
      {layer:"DISTRIBUTED CONTROL PLANE"}),

    slide("51 · CONSISTENCY", "cluster", "Redis 的高可用，为什么不等于零丢失强一致？", "Primary 默认先在本地执行并异步复制；故障与分区可能让新 Primary 少一段最新历史。", "consistency",
      ["客户端收到 +OK 时，Replica 可能尚未接收；旧 Primary 随即永久故障，提升 Replica 会缺这条写。","WAIT/WAITAOF、min-replicas-to-write 与合理 timeout 能缩小窗口，但不能把异步系统变成共识提交。","读 Replica、故障重试和超时后的未知结果还会引入 stale read 与重复执行。"],
      "高可用回答“尽快恢复服务”；一致性回答“恢复后保留哪段历史”，两者必须分别设计。",
      [["DEFAULT","async replication"],["GUARD","min-replicas-*"],["ACK","WAIT/WAITAOF"],["APP","idempotency/version"]],
      ["Redis 优先低延迟和可操作的 HA。","关键账务若要求线性一致/共识提交，应评估更合适的系统或额外协议。"],
      "writeId = uniqueId()\nSETNX dedupe:{writeId} result EX ttl\napply idempotent change\nWAIT/WAITAOF according to loss budget", DOC.replication,
      {layer:"FAILURE SEMANTICS", quiz:"客户端超时后能否直接断定 SET 没执行？", answer:"不能。回复可能在网络中丢失而命令已执行。重试需要 NX、幂等 token、版本或业务去重。"}),

    slide("52 · PERFORMANCE", "ops", "Redis 为什么快，又为什么会突然卡顿？", "快来自内存、短路径、专用结构和批处理；卡顿来自任何长时间占住执行路径或机器资源的工作。", "performance",
      ["常用 O(1)/O(log N) 命令在 RAM 完成，事件循环避免线程切换与共享锁。","Pipeline/批量命令摊薄 RTT；紧凑编码提高 cache locality。","慢命令、大 key、fork/COW、AOF fsync、active expire、eviction、网络大回复都能制造 P99。"],
      "Redis 的性能不是“全在内存所以永远快”，而是每条命令都必须保持短小且可预测。",
      [["CPU","one busy execution path"],["MEMORY","fragmentation/COW"],["DISK","fsync/rewrite"],["NETWORK","RTT + bytes"]],
      ["设计简单，正常路径极短。","所有昂贵边界都会在单线程语义或共享机器资源上汇合。"],
      "latency = poolWait + RTT + queue + commandCPU\n        + replyBytes/network + clientDecode\nP99 spikes += fork + fsync + expire + eviction + bigKey", DOC.latency,
      {layer:"COST MODEL"}),

    slide("53 · DIAGNOSIS", "ops", "线上 Redis 慢了，应该沿哪条链排查？", "先区分客户端等待、网络、Redis 排队/执行、后台事件与下游回源，再找最窄边界。", "diagnosis",
      ["客户端记录 pool wait、connect、command RTT、重试与 payload bytes；不要只看服务端 `instantaneous_ops_per_sec`。","Redis 看 SLOWLOG、LATENCY DOCTOR、commandstats、INFO memory/persistence/replication。","再对齐 fork、fsync、AOF rewrite、expire/eviction、failover、部署与流量变化的时间线。"],
      "排障从一条请求的阶段证据开始，不从随意复制 redis.conf 参数开始。",
      [["CLIENT","pool + RTT + retry"],["COMMAND","slowlog/commandstats"],["EVENT","latency doctor"],["SYSTEM","CPU/RAM/disk/net"]],
      ["阶段化证据快速缩小搜索空间。","单次 INFO 或一次截图没有时间关系，不能证明因果。"],
      "if poolWait↑: fix client limits\nelse if slowlog hit: inspect N/big key/script\nelse correlate latency events with fork/fsync/expire\nthen verify CPU, memory, disk, network", DOC.latency,
      {layer:"PRODUCTION RUNBOOK", boundary:"SLOWLOG 只记录 Redis 命令执行时间，不含客户端连接池等待、网络 RTT 和客户端反序列化。"}),

    slide("54 · FINAL CHECK", "ops", "现在，你能解释这条 Key 的一生了吗？", "用因果问题验收，而不是背命令列表。", "final",
      ["对象如何变 bytes？RESP 如何进 event loop？SET 如何改 dict/object/expires？","过期与淘汰为何不同？Hash/List/ZSet/Stream 的物理编码为何不同？","RDB/AOF/Replica/Sentinel/Cluster 各保证什么，又留下什么窗口？"],
      "真正掌握 Redis，是能从一条命令推导出它占用的 CPU、内存、网络、磁盘和故障边界。",
      [["KEY","session:user:9527"],["MAIN PATH","RESP → event → dict"],["LIFECYCLE","TTL / eviction"],["RELIABILITY","AOF/RDB/repl/HA"]],
      ["形成可迁移的 Redis 成本与故障模型。","生产参数仍需用真实 key 分布、QPS、RPO/RTO 和故障演练验证。"],
      "object → bytes → RESP → socket → event loop\n→ command gate → dict/object + expires\n→ AOF + replication → reply\n→ expire/evict/delete → recover/failover", DOC.types,
      {layer:"FINAL · CHECK", quiz:"如果只能记住一句话，应该是什么？", answer:"Redis 用串行、短小的命令快速改变内存结构；TTL、持久化、复制和 Cluster 分别在不同时间与故障边界上补充生命周期、耐久性、可用性和规模。"})
  ];
})();
