(() => {
  "use strict";
  const h = (name, detail, body, cls="") => `<button type="button" class="unit hotspot ${cls}" data-deep-open data-component-name="${name}" data-component-detail="${detail}">${body}</button>`;
  const arrow = (label="") => `<div class="arrow">${label ? `<span>${label}</span>` : ""}</div>`;
  const step = (label, title, detail, cls="") => h(title, detail, `<span>${label}</span><strong>${title}</strong><small>${detail}</small>`, cls);
  const lane = (items, cls="") => `<div class="physical-scene process-lane ${cls}">${items.map((it,i)=>`${step(it[0],it[1],it[2],it[3]||"")}${i<items.length-1?arrow(it[4]||""):""}`).join("")}</div>`;
  const key = `<span class="key-token"><i></i><b>session:user:9527</b></span>`;

  const visuals = {
    "cover": () => `<div class="physical-scene cover-scene"><section class="cover-copy"><span>REDIS · KEY JOURNEY</span><h2>一条 Key，<br>穿过内存与机器。</h2><p><code>SET session:user:9527 &lt;json&gt; EX 1800 NX</code></p></section><section class="memory-orbit"><div class="orbit o1"></div><div class="orbit o2"></div><div class="key-core"><small>REDIS KEY</small><strong>user:9527</strong><em>JSON BYTES · TTL 1800</em></div><span class="ol l1">RESP</span><span class="ol l2">DICT</span><span class="ol l3">AOF</span><span class="ol l4">REPLICA</span></section></div>`,
    "whole-map": () => `<div class="physical-scene atlas-scene"><section class="atlas-client"><header>APPLICATION HOST</header><div>Session object</div><div>Serializer</div><div class="focus">Redis Client Pool ${key}</div></section><div class="atlas-wire"><span>RESP / TCP</span><i></i></div><section class="atlas-server"><header>REDIS PRIMARY · PROCESS</header><div class="atlas-loop">EVENT LOOP</div><div class="atlas-command">SET COMMAND</div><div class="atlas-db"><span>DB0 KEYSPACE</span><b>hash bucket → redis object</b><em>EXPIRES → 1800s</em></div></section><section class="atlas-side"><header>RELIABILITY PATHS</header><div>AOF<br><small>buffer → page cache → fsync</small></div><div>RDB<br><small>fork → COW → snapshot</small></div><div>REPLICA<br><small>command stream → ACK</small></div></section><div class="atlas-reply">+OK ← output buffer</div></div>`,
    "command-anatomy": () => `<div class="physical-scene command-scene"><div class="command-ribbon"><button data-deep-open data-component-name="SET" data-component-detail="选择 String 类型写入命令。"><b>SET</b><small>COMMAND</small></button><button data-deep-open data-component-name="Key" data-component-detail="二进制安全的身份；冒号只是命名习惯。"><b>session:user:9527</b><small>KEY</small></button><button data-deep-open data-component-name="Value" data-component-detail="应用序列化后的 bytes；Redis Core 不理解 JSON 字段。"><b>{ uid:9527, … }</b><small>VALUE BYTES</small></button><button data-deep-open data-component-name="EX 1800" data-component-detail="建立 1800 秒 key TTL。"><b>EX 1800</b><small>LIFECYCLE</small></button><button data-deep-open data-component-name="NX" data-component-detail="只在 key 不存在时写入。"><b>NX</b><small>CONDITION</small></button></div><div class="command-result"><span>ONE ATOMIC COMMAND</span><strong>OK</strong><small>或 null：key 已存在</small></div></div>`,
    "serialization": () => `<div class="physical-scene serialization-scene"><section class="jvm-object"><header>JVM HEAP</header><strong>Session</strong><dl><div><dt>uid</dt><dd>9527</dd></div><div><dt>roles</dt><dd>[buyer]</dd></div><div><dt>issuedAt</dt><dd>…</dd></div></dl></section>${arrow("Jackson / codec")}<section class="byte-tape"><header>VALUE BYTE[]</header><div><i>7B</i><i>22</i><i>75</i><i>69</i><i>64</i><i>22</i><i>3A</i><i>39</i><i>35</i><i>32</i><i>37</i><i>…</i></div><code>{"uid":9527,"roles":["buyer"]}</code></section>${arrow("RESP only frames")}<section class="redis-blind"><header>REDIS CORE</header><strong>BINARY-SAFE STRING</strong><small>不知道 Java 类，也不解析 JSON 字段</small></section></div>`,
    "deployment": () => `<div class="physical-scene deployment-scene"><section><header>01 · STANDALONE</header><div class="server-cube primary">PRIMARY</div><p>最短路径 · 单可写实例</p></section><section><header>02 · SENTINEL</header><div class="ha-row"><b>P</b><i></i><b>R</b><i></i><b>R</b></div><div class="sentinel-row"><span>S1</span><span>S2</span><span>S3</span></div><p>不分片 · 自动故障转移</p></section><section><header>03 · CLUSTER</header><div class="slot-grid"><b>M1<br><small>0–5460</small></b><b>M2<br><small>5461–10922</small></b><b>M3<br><small>10923–16383</small></b></div><p>16384 slots · 分片 + HA</p></section></div>`,
    "client-pool": () => `<div class="physical-scene client-pool-scene"><section class="app-rack"><header>ORDER-SERVICE · JVM</header><div class="threads"><span>T1</span><span>T2</span><span>T3</span><span>T4</span></div><div class="pool"><b>RedisClient / Pool</b><span>conn-1</span><span>conn-2</span><span>conn-3</span><small>bounded · timeout</small></div></section>${arrow("borrow")}<section class="discovery"><header>SERVICE DISCOVERY</header><div><b>Sentinel</b><small>3 endpoints → current Primary</small></div><div><b>Cluster</b><small>2–3 seeds → slot topology</small></div></section>${arrow("TCP/TLS")}<section class="target-node"><header>OWNING NODE</header><strong>redis-primary-a</strong><small>:6379 · healthy</small></section></div>`,
    "resp": () => `<div class="physical-scene resp-scene"><section class="resp-terminal"><header>CLIENT WRITE BUFFER</header><pre>*7\r\n
$3\r\nSET\r\n
$17\r\nsession:user:9527\r\n
$42\r\n{json-bytes}\r\n
$2\r\nEX\r\n $4\r\n1800\r\n $2\r\nNX\r\n</pre></section><section class="resp-legend"><div><b>*7</b><span>array length</span></div><div><b>$17</b><span>bulk byte length</span></div><div><b>\r\n</b><span>frame boundary</span></div><div><b>payload</b><span>not parsed as JSON</span></div></section><div class="packet-stream"><i></i><i></i><i></i><b>TCP BYTE STREAM</b></div></div>`,
    "socket": () => `<div class="physical-scene socket-scene"><section class="nic"><header>NIC · eth0</header><span>TCP segments</span></section>${arrow()}<section class="kernel-stack"><header>LINUX KERNEL</header><div>socket fd 42</div><div class="ring"><b>RECV BUFFER</b><i></i><i></i><i></i><small>partial RESP bytes</small></div></section>${arrow("read()")}<section class="redis-client-struct"><header>REDIS PROCESS · client</header><div><b>querybuf</b><span>*7 $3 SET $17 ses…</span></div><div><b>argv</b><span>not complete yet</span></div></section></div>`,
    "event-loop": () => `<div class="physical-scene event-loop-scene"><section class="fd-rack"><header>FILE DESCRIPTORS</header><span>fd 11 · idle</span><span class="ready">fd 42 · READABLE</span><span>fd 76 · writable</span><span>fd 90 · idle</span></section><section class="loop-wheel"><div><small>aeApiPoll</small><strong>EVENT<br>LOOP</strong><em>one turn</em></div><i class="needle"></i></section><section class="event-queues"><div><header>FILE EVENT</header><b>readQueryFromClient(fd42)</b></div><div><header>TIME EVENT</header><b>serverCron / expire cycle</b></div><div><header>NEXT TURN</header><b>write replies</b></div></section></div>`,
    "io-threads": () => `<div class="physical-scene thread-scene"><section class="io-threads"><header>OPTIONAL I/O THREADS</header><div><span>IO-1</span><span>IO-2</span><span>IO-3</span></div><p>read/write network buffers · TLS work</p></section><div class="join-arrow">BYTES READY ↓</div><section class="main-thread"><header>MAIN EXECUTION PATH</header><div class="cpu-core"><b>CORE 7</b><span>parse → SET → dict mutation</span></div><p>command effects remain serialized</p></section><section class="background-threads"><header>BACKGROUND</header><span>bio_fsync</span><span>lazyfree</span><span>child RDB/AOF rewrite</span></section></div>`,
    "command-gate": () => `<div class="physical-scene gate-scene"><div class="request-card">${key}<strong>SET … EX 1800 NX</strong></div><section class="security-gate"><header>COMMAND DISPATCH GATE</header><div><b>1</b><span>lookup command table</span></div><div><b>2</b><span>arity + syntax</span></div><div><b>3</b><span>AUTH + ACL</span></div><div><b>4</b><span>cluster slot + write state</span></div><div><b>5</b><span>maxmemory policy</span></div></section><div class="gate-outcomes"><span class="ok">PASS → setCommand()</span><span>NOAUTH / NOPERM</span><span>OOM</span><span>MOVED / ASK</span></div></div>`,
    "keyspace": () => `<div class="physical-scene keyspace-scene"><section class="db-shell"><header>REDIS PROCESS · DB 0</header><div class="hash-function"><b>hash(key bytes)</b><span>→ bucket 07</span></div><div class="bucket-table"><span>00</span><span>01</span><span>…</span><span class="active">07 <i></i></span><span>08</span><span>…</span></div><div class="dict-entry"><small>DICT ENTRY</small><b>key ptr</b><i>→</i><strong>value object ptr</strong>${key}</div></section><aside class="nx-check"><span>NX CHECK</span><b>entry absent?</b><strong>YES → insert</strong><small>NO → return null</small></aside></div>`,
    "redis-object": () => `<div class="physical-scene object-scene"><section class="dict-pointer"><header>DICT ENTRY · bucket 07</header><b>value*</b><i></i></section><section class="object-cutaway"><header>REDIS VALUE OBJECT</header><div class="object-meta"><span><small>TYPE</small><b>STRING</b></span><span><small>ENCODING</small><b>RAW</b></span><span><small>ACCESS</small><b>LRU/LFU bits</b></span></div><div class="object-pointer"><b>payload ptr</b><i></i><strong>SDS</strong></div></section><section class="sds-block"><header>ALLOCATOR BLOCK</header><div><small>len</small><b>42</b></div><div><small>alloc</small><b>48</b></div><pre>{"uid":9527,…}\0</pre></section></div>`,
    "string-encoding": () => `<div class="physical-scene encoding-scene"><section><header>INT</header><div class="encoding-block"><b>9527</b></div><p>integer content · compact arithmetic</p></section><section class="selected"><header>EMBSTR</header><div class="encoding-block joined"><b>OBJ</b><i>SDS + bytes</i></div><p>short string · one allocation</p></section><section><header>RAW</header><div class="encoding-block split"><b>OBJ</b><i></i><em>SDS + long bytes</em></div><p>long / mutable string</p></section><div class="encoding-rule">LOGICAL TYPE: STRING · PHYSICAL ENCODING MAY CHANGE</div></div>`,
    "expires-dict": () => `<div class="physical-scene expires-scene"><section class="parallel-index"><header>DB0 · TWO RELATED INDEXES</header><div class="index-row"><span>KEYSPACE</span><b>session:user:9527</b><i>→</i><strong>StringObject*</strong></div><div class="index-row expiry"><span>EXPIRES</span><b>session:user:9527</b><i>→</i><strong>1798765432123 ms</strong></div></section><section class="clock-face"><div><b>NOW</b><span>+ 1800s</span><strong>EXPIRE AT</strong></div><small>absolute wall-clock time</small></section></div>`,
    "propagation": () => `<div class="physical-scene propagation-scene"><section class="applied-memory"><header>① PRIMARY MEMORY</header><b>DICT UPDATED</b><span>Key becomes visible</span></section><div class="fanout"><i></i><i></i><i></i></div><section class="fanout-targets"><div><header>② AOF BUFFER</header><b>SET … PXAT …</b><small>write / fsync later</small></div><div><header>③ REPLICATION STREAM</header><b>offset + command</b><small>replica applies later</small></div><div><header>④ CLIENT OUTPUT</header><b>+OK</b><small>policy determines timing</small></div></section></div>`,
    "success": () => `<div class="physical-scene success-scene"><section class="success-timeline"><div class="point done"><b>1</b><span>Primary memory applied</span></div><i></i><div class="point"><b>2</b><span>AOF write → OS cache</span></div><i></i><div class="point"><b>3</b><span>fsync durable media</span></div><i></i><div class="point"><b>4</b><span>Replica ACK</span></div></section><section class="ack-policies"><div><b>DEFAULT +OK</b><span>usually after point 1</span></div><div><b>appendfsync always</b><span>bind closer to point 3</span></div><div><b>WAIT / WAITAOF</b><span>explicitly wait for 4 / durability</span></div></section></div>`,
    "get-path": () => lane([["01","hash key","find dict entry","tracked"],["02","expireIfNeeded","compare absolute TTL"],["03","touch metadata","LRU/LFU access"],["04","read SDS","value bytes"],["05","RESP reply","$42 …"]],"get-lane"),
    "passive-expire": () => `<div class="physical-scene passive-scene"><section class="read-clock"><header>GET session:user:9527</header><div><span>expireAt</span><b>10:30:00.000</b></div><div><span>now</span><b>10:30:00.127</b></div><strong>EXPIRED</strong></section>${arrow()}<section class="delete-path"><div>remove from keyspace</div><div>remove from expires</div><div>propagate DEL to AOF/replicas</div></section><div class="miss-reply">CLIENT ← <b>NULL</b></div></div>`,
    "active-expire": () => `<div class="physical-scene active-expire-scene"><section class="expire-wheel"><header>serverCron</header><div class="sample-dots"><i class="dead"></i><i></i><i class="dead"></i><i class="dead"></i><i></i><i></i><i class="dead"></i><i></i></div><strong>SAMPLE EXPIRES</strong></section><section class="budget-meter"><header>TIME BUDGET</header><div><i style="width:68%"></i></div><b>stale ratio high → continue</b><small>budget reached → yield to event loop</small></section><section class="reclaimed"><b>4</b><span>expired keys reclaimed</span><small>not a full keyspace scan</small></section></div>`,
    "memory-accounting": () => `<div class="physical-scene accounting-scene"><section class="payload-core"><small>BUSINESS PAYLOAD</small><strong>42 B</strong><span>JSON bytes</span></section><div class="memory-layers"><div>Key SDS</div><div>Dict entry + pointers</div><div>Value object + SDS</div><div>Expires metadata</div><div>Allocator rounding</div><div>Fragmentation / buffers</div></div><section class="memory-total"><small>MEMORY USAGE</small><strong>≫ 42 B</strong><span>measure, don't guess</span></section></div>`,
    "eviction-trigger": () => `<div class="physical-scene eviction-scene"><section class="ram-tank"><header>DATASET MEMORY</header><div class="fill" style="height:91%"></div><span class="limit">maxmemory 8 GB</span><b>8.3 GB</b></section>${arrow("WRITE")}<section class="policy-engine"><header>MAXMEMORY POLICY</header><div>allkeys-lfu</div><div>sample candidates</div><div>evict until below limit</div></section><section class="victim-pool"><span>hot A · 223</span><span>hot B · 91</span><span class="victim">cold C · 1 ×</span><span>warm D · 18</span></section></div>`,
    "lru-lfu": () => `<div class="physical-scene lru-scene"><section class="sample-box"><header>RANDOM SAMPLE · N=5</header><div><span>A<small>idle 2s</small></span><span>B<small>idle 81s</small></span><span>C<small>idle 9s</small></span><span>D<small>idle 44s</small></span><span>E<small>idle 12s</small></span></div></section>${arrow()}<section class="candidate-pool"><header>APPROXIMATE LRU</header><strong>B</strong><span>longest idle in sample</span><small>not global exact oldest</small></section><section class="lfu-note"><b>LFU</b><span>uses decaying frequency counter instead of idle clock</span></section></div>`,
    "lazyfree": () => `<div class="physical-scene lazyfree-scene"><section class="big-object"><header>BIG HASH · 2M FIELDS</header><div class="blocks"><i></i><i></i><i></i><i></i><i></i><i></i></div></section><div class="delete-split"><span>UNLINK</span><i></i></div><section class="main-unlink"><header>MAIN THREAD</header><b>detach key pointer</b><small>immediately invisible</small></section><section class="bg-free"><header>LAZY-FREE THREAD</header><b>walk + free allocations</b><div class="progress"><i></i></div><small>physical RSS may lag</small></section></div>`,
    "hash": () => `<div class="physical-scene hash-scene"><section class="small-hash"><header>SMALL HASH · LISTPACK</header><div class="listpack"><span>name</span><b>Li</b><span>role</span><b>buyer</b><span>age</span><b>28</b></div><small>contiguous · cache friendly</small></section><div class="threshold"><b>entries/value threshold crossed</b><i></i></div><section class="large-hash"><header>HASHTABLE</header><div class="mini-buckets"><span>0</span><span class="p">name → Li</span><span>2</span><span class="p">role → buyer</span><span class="p">age → 28</span></div><small>more pointers · average O(1)</small></section></div>`,
    "list": () => `<div class="physical-scene list-scene"><section class="quicklist"><header>QUICKLIST</header><div class="ql-node"><span>LISTPACK A</span><b>a</b><b>b</b><b>c</b></div><i></i><div class="ql-node compressed"><span>COMPRESSED MIDDLE</span><b>…</b></div><i></i><div class="ql-node"><span>LISTPACK Z</span><b>x</b><b>y</b><b>z</b></div></section><div class="list-ops"><span>LPUSH →</span><span>← RPUSH</span><small>range work grows with elements returned</small></div></div>`,
    "set": () => `<div class="physical-scene set-scene"><section><header>INTSET</header><div class="intset"><b>3</b><b>8</b><b>21</b><b>55</b></div><small>sorted integers</small></section><div class="conversion">member="alice"<br>or threshold →</div><section><header>HASHTABLE / LISTPACK</header><div class="set-buckets"><span>alice</span><span>55</span><span>21</span><span>bob</span></div><small>generic members</small></section></div>`,
    "zset": () => `<div class="physical-scene zset-scene"><section class="zset-dict"><header>DICT · MEMBER LOOKUP</header><span>alice → 98</span><span>bob → 87</span><span>cora → 92</span></section><section class="skiplist"><header>SKIPLIST · SCORE ORDER</header><div class="level l3"><i></i><b>87</b><i></i><b>98</b></div><div class="level l2"><i></i><b>87</b><i></i><b>92</b><i></i><b>98</b></div><div class="level l1"><b>bob 87</b><b>cora 92</b><b>alice 98</b></div></section><div class="dual-update">ZADD updates both indexes</div></div>`,
    "stream": () => `<div class="physical-scene stream-scene"><section class="stream-log"><header>STREAM ENTRIES · RADIX TREE + LISTPACKS</header><div><b>1710-0</b><span>sku=A qty=1</span></div><div class="focus"><b>1710-1</b><span>sku=B qty=2</span></div><div><b>1711-0</b><span>sku=C qty=1</span></div></section><section class="consumer-state"><header>GROUP · fulfillment</header><div><span>last delivered</span><b>1710-1</b></div><div class="pel"><span>PEL</span><b>1710-1 → consumer-2</b></div><small>XACK removes PEL entry, not stream entry</small></section></div>`,
    "special-types": () => `<div class="physical-scene special-scene"><section><header>BITMAP</header><div class="bits">101100101001</div><small>dense flags</small></section><section><header>HYPERLOGLOG</header><div class="registers"><i></i><i></i><i></i><i></i><i></i></div><small>approx cardinality</small></section><section><header>GEO</header><div class="geo-grid"><i></i><i></i><i></i></div><small>spatial score</small></section><section><header>VECTOR SET</header><div class="vector-points"><i></i><i></i><i></i><i></i><i></i></div><small>similarity neighbors</small></section></div>`,
    "pipeline": () => `<div class="physical-scene pipeline-scene"><section class="roundtrips"><header>WITHOUT PIPELINE</header><div>SET → ← OK</div><div>INCR → ← 1</div><div>GET → ← value</div><b>3 × RTT</b></section><section class="batched-wire"><header>WITH PIPELINE</header><div class="out">SET · INCR · GET →</div><div class="back">← OK · 1 · value</div><b>1 × RTT · 3 independent replies</b></section></div>`,
    "transaction": () => `<div class="physical-scene tx-scene"><section class="tx-queue"><header>CLIENT CONNECTION</header><div><b>MULTI</b><span>OK</span></div><div><b>SET balance 90</b><span>QUEUED</span></div><div><b>INCR audit</b><span>QUEUED</span></div><div class="exec"><b>EXEC</b><span>[OK, 42]</span></div></section><section class="watch-sensor"><header>WATCH balance</header><div class="version-line"><i></i><span>changed by other client?</span></div><strong>YES → EXEC returns null</strong><small>client retries · no automatic rollback</small></section></div>`,
    "lua-functions": () => `<div class="physical-scene lua-scene"><section class="lua-client"><header>CLIENT</header><code>FCALL reserve 1 stock 2</code><small>one RTT</small></section>${arrow()}<section class="script-box"><header>REDIS FUNCTION · ATOMIC</header><pre>stock = GET(key)\nif stock &gt;= 2:\n  DECRBY(key, 2)\n  return 1</pre><div class="blocked-clients">other commands wait</div></section><section class="script-rule"><b>SHORT + BOUNDED</b><span>same-slot keys in Cluster</span></section></div>`,
    "cache-aside": () => `<div class="physical-scene cache-aside-scene"><section class="service-box"><header>PRODUCT SERVICE</header><b>GET product:8821</b></section><div class="cache-branch"><i></i><i></i></div><section class="redis-cache"><header>REDIS CACHE</header><strong>HIT</strong><span>return bytes</span><em>MISS ↓</em></section><section class="database-box"><header>SOURCE DATABASE</header><b>SELECT product</b><span>SET EX + TTL jitter ↑</span></section><div class="write-rule"><b>WRITE</b><span>DB commit → invalidate cache</span></div></div>`,
    "penetration": () => `<div class="physical-scene penetration-scene"><section class="bad-requests"><header>REPEATED INVALID IDS</header><span>product:-1</span><span>product:999999999</span><span>product:attack-…</span></section>${arrow()}<section class="miss-tunnel"><div>Redis MISS</div><div>DB MISS</div><div>repeat forever</div></section><section class="filters"><header>CHEAPER TERMINATION</header><b>validate</b><b>Bloom Filter</b><b>negative cache · short TTL</b><b>rate limit</b></section></div>`,
    "stampede": () => `<div class="physical-scene stampede-scene"><section class="crowd"><header>10,000 CONCURRENT REQUESTS</header><div>${Array.from({length:18},(_,i)=>`<i style="--d:${i}"></i>`).join("")}</div></section><section class="expired-hot"><span>hot:key</span><strong>TTL = 0</strong><b>MISS</b></section><section class="single-flight"><header>SINGLE FLIGHT</header><div class="winner">1 loader → DB</div><div>others wait / stale</div><small>lock has TTL + token</small></section></div>`,
    "avalanche": () => `<div class="physical-scene avalanche-scene"><section class="ttl-timeline"><header>SAME TTL</header><div><span>k1</span><span>k2</span><span>k3</span><span>k4</span><span>k5</span></div><i></i><b>12:00:00 · all expire</b></section><section class="db-wave"><div class="wave"></div><strong>DATABASE LOAD SPIKE</strong></section><section class="jitter-box"><header>TTL JITTER</header><span>11:57</span><span>12:03</span><span>12:07</span><small>plus backpressure / fallback</small></section></div>`,
    "hot-key": () => `<div class="physical-scene hotkey-scene"><section class="traffic-fan"><header>ALL REQUESTS</header><div>${Array.from({length:12},()=>"<i></i>").join("")}</div></section><section class="slot-fire"><span>SLOT 8129</span><strong>hot:key</strong><div class="cpu-gauge"><i></i></div><b>ONE CORE · 100%</b></section><section class="spread-options"><header>CHANGE PHYSICAL PLACEMENT</header><span>local read cache</span><span>replica reads</span><span>request coalescing</span><span>sharded counters</span></section></div>`,
    "big-key": () => `<div class="physical-scene bigkey-scene"><section class="keyspace-wall"><header>10,000,000 KEYS</header><div class="tiny-keys"></div><strong>KEYS * → full scan + huge reply</strong></section><section class="scan-cursor"><header>SCAN CURSOR</header><div><b>0</b><i></i><b>734</b><i></i><b>1281</b><i></i><b>0</b></div><small>bounded slices · may repeat · not a snapshot</small></section><section class="big-value"><header>BIG HASH</header><b>2M fields</b><span>HGETALL / DEL cost</span></section></div>`,
    "rdb": () => `<div class="physical-scene rdb-scene"><section class="parent-memory"><header>PARENT REDIS</header><div class="pages"><i>A</i><i>B</i><i>C</i><i>D</i></div><b>continues serving writes</b></section><div class="fork-split"><span>fork()</span><i></i></div><section class="child-memory"><header>RDB CHILD · SNAPSHOT VIEW</header><div class="pages"><i>A</i><i>B</i><i>C</i><i>D</i></div><b>serialize → temp.rdb</b></section><section class="cow-page"><header>PARENT WRITES PAGE C</header><i>C′</i><b>COPY-ON-WRITE</b><small>extra peak RAM</small></section><section class="rdb-file"><span>dump.rdb</span><b>atomic rename</b></section></div>`,
    "aof": () => `<div class="physical-scene aof-scene"><section class="memory-state"><header>PRIMARY MEMORY</header><b>SET applied</b></section>${arrow()}<section class="aof-buffer"><header>PROCESS AOF BUFFER</header><code>*3 … SET …</code></section>${arrow("write(2)")}<section class="page-cache"><header>OS PAGE CACHE</header><div class="dirty-pages"><i></i><i></i><i></i></div></section>${arrow("fsync")}<section class="nvme"><header>NVMe / SSD</header><div class="disk-platter"></div><b>durable boundary</b></section></div>`,
    "aof-rewrite": () => `<div class="physical-scene rewrite-scene"><section class="old-aof"><header>OLD HISTORY</header><span>SET k 1</span><span>INCR k</span><span>INCR k</span><span>EXPIRE k 10</span><span>… 2.4 GB</span></section><section class="rewrite-child"><header>REWRITE CHILD</header><b>current dataset</b><span>→ minimal BASE</span></section><section class="multipart-aof"><header>APPENDONLYDIR</header><div class="base">appendonly.aof.2.base.rdb</div><div class="incr">appendonly.aof.2.incr.aof</div><div class="manifest">appendonly.aof.manifest</div><small>atomic manifest switch</small></section></div>`,
    "recovery": () => `<div class="physical-scene recovery-scene"><section class="boot-files"><header>DISK</header><div><b>MANIFEST</b><span>BASE 2 → INCR 2</span></div><div><b>RDB BASE</b><span>compact dataset</span></div><div><b>INCR AOF</b><span>newer commands</span></div></section>${arrow("load in order")}<section class="rebuild-memory"><header>REDIS STARTUP</header><div class="boot-progress"><i></i></div><b>reconstruct DB0 keyspace</b><span>drop already expired keys</span></section><section class="ready-state"><strong>READY</strong><small>only after recovery completes</small></section></div>`,
    "replication": () => `<div class="physical-scene repl-scene"><section class="primary-node"><header>PRIMARY</header><div class="repl-stream"><b>replid A</b><span>offset 9,821,004</span></div><strong>SET …</strong></section><div class="repl-links"><div><span>command stream →</span><i></i></div><div><i></i><span>← ACK offset</span></div></div><section class="replica-node"><header>REPLICA</header><div>connect + PSYNC</div><div>read stream</div><div>apply in order</div><strong>offset 9,821,004</strong></section></div>`,
    "psync": () => `<div class="physical-scene psync-scene"><section class="backlog-ring"><header>PRIMARY REPLICATION BACKLOG</header><div class="offsets"><span>9800</span><span>9900</span><span>10000</span><span>10100</span><span>10200</span></div><b>circular history window</b></section><section class="reconnect-request"><header>REPLICA RECONNECTS</header><code>PSYNC replid-A 10042</code><strong class="yes">IN WINDOW → PARTIAL</strong><strong class="no">OUTSIDE → FULL RDB SYNC</strong></section></div>`,
    "wait": () => `<div class="physical-scene wait-scene"><section class="write-connection"><header>SAME CLIENT CONNECTION</header><div>1 · SET critical:key value → OK</div><div>2 · WAIT 1 100</div></section><section class="wait-fan"><header>PRIMARY OFFSET 4210</header><i></i><span>Replica A · ACK 4210 ✓</span><i></i><span>Replica B · ACK 4188</span></section><section class="wait-result"><strong>1</strong><span>replica acknowledged</span><small>timeout returns actual count; SET is not rolled back</small></section></div>`,
    "sentinel": () => `<div class="physical-scene sentinel-scene"><section class="sentinel-quorum"><header>SENTINEL CONTROL PLANE</header><div><span>S1 · SDOWN</span><span>S2 · SDOWN</span><span>S3 · reachable</span></div><strong>quorum 2 → ODOWN</strong><small>leader election by epoch/votes</small></section><section class="redis-ha"><header>REDIS DATA PLANE</header><div class="old-primary"><b>P</b><span>FAIL</span></div><i></i><div class="promoted"><b>R1 → NEW P</b><span>promote</span></div><i></i><div><b>R2</b><span>follow new P</span></div></section><div class="sentinel-client">CLIENT asks Sentinels → discovers new Primary</div></div>`,
    "cluster-slots": () => `<div class="physical-scene slots-scene"><section class="slot-hash"><header>KEY</header><b>session:user:9527</b><code>CRC16(key) % 16384</code><strong>slot 8129</strong></section>${arrow()}<section class="slot-ring"><div class="arc a"></div><div class="arc b"></div><div class="arc c"></div><span class="slot-dot">8129</span><b>16384 SLOTS</b></section>${arrow()}<section class="slot-masters"><div>M1<br><small>0–5460</small></div><div class="focus">M2<br><small>5461–10922</small></div><div>M3<br><small>10923–16383</small></div></section></div>`,
    "hash-tags": () => `<div class="physical-scene tags-scene"><section class="tag-keys"><div>cart:<b>{user:9527}</b></div><div>lock:<b>{user:9527}</b></div><div>coupon:<b>{user:9527}</b></div></section>${arrow("hash only tag")}<section class="same-slot"><span>CRC16(user:9527)</span><strong>SLOT 8129</strong><b>ONE MASTER</b></section><section class="multi-key-op"><header>ATOMIC MULTI-KEY</header><code>FCALL checkout 3 cart lock coupon</code><small>all keys co-located</small></section></div>`,
    "redirects": () => `<div class="physical-scene redirect-scene"><section class="cluster-client"><header>CLIENT SLOT CACHE</header><b>8129 → M1 (stale)</b></section><div class="wrong-route">command → M1</div><section class="source-master"><header>M1</header><div><b>MOVED</b><span>8129 M2:6379</span></div><div><b>ASK</b><span>during migration</span></div></section><section class="target-master"><header>M2</header><strong>SLOT 8129</strong><span>MOVED: cache mapping</span><span>ASK: ASKING + retry once</span></section></div>`,
    "cluster-failover": () => `<div class="physical-scene cluster-fail-scene"><section class="gossip-plane"><header>CLUSTER BUS · GOSSIP</header><div><span>M1 sees M2 fail</span><span>M3 sees M2 fail</span><span>majority → FAIL</span></div></section><section class="failed-shard"><header>M2</header><b>slots 5461–10922</b><strong>FAILED</strong></section><section class="election"><header>REPLICA R2</header><div>request votes</div><div>new configEpoch 93</div><strong>PROMOTE</strong></section><section class="new-owner"><header>NEW M2</header><b>claims slots with epoch 93</b><span>gossip UPDATE → all nodes</span></section></div>`,
    "consistency": () => `<div class="physical-scene consistency-scene"><section class="ack-window"><header>TIMELINE</header><div><b>T0</b><span>Primary applies SET</span></div><div><b>T1</b><span>client receives +OK</span></div><div class="danger"><b>T2</b><span>Primary dies before Replica receives</span></div><div><b>T3</b><span>Replica promoted without latest write</span></div></section><section class="guards"><header>SHRINK THE WINDOW</header><span>WAIT / WAITAOF</span><span>min-replicas-to-write</span><span>idempotency + version</span><small>not a consensus commit protocol</small></section></div>`,
    "performance": () => `<div class="physical-scene performance-scene"><section class="fast-path"><header>FAST PATH</header><span>RAM lookup</span><span>O(1)/O(log N)</span><span>event loop</span><span>compact encoding</span><span>pipeline</span></section><div class="latency-heart"><strong>P99</strong><div class="pulse"></div></div><section class="spikes"><header>SPIKE SOURCES</header><span>O(N) / big reply</span><span>fork + COW</span><span>AOF fsync/rewrite</span><span>expire/eviction cycle</span><span>hot key / failover</span></section></div>`,
    "diagnosis": () => `<div class="physical-scene diagnosis-scene"><section class="trace-waterfall"><header>ONE COMMAND WALL TIME</header><div><span>POOL WAIT</span><i style="width:18%"></i></div><div><span>NETWORK RTT</span><i style="width:11%"></i></div><div><span>REDIS QUEUE + EXEC</span><i class="hot" style="width:58%"></i></div><div><span>REPLY + DECODE</span><i style="width:13%"></i></div></section><section class="evidence-stack"><header>CORRELATE SAME TIMELINE</header><b>SLOWLOG / commandstats</b><b>LATENCY DOCTOR</b><b>INFO memory/persistence/repl</b><b>CPU · disk · network</b></section></div>`,
    "final": () => `<div class="physical-scene final-scene"><section class="final-key"><small>REDIS KEY</small><strong>session:user:9527</strong><span>bytes · type · encoding · TTL</span></section><div class="final-rings"><span>RESP</span><span>EVENT LOOP</span><span>DICT / OBJECT</span><span>EXPIRE / EVICT</span><span>AOF / RDB</span><span>REPLICA / HA</span><span>CLUSTER SLOT</span></div><section class="final-question"><b>你能从一条命令推导：</b><span>CPU · RAM · NET · DISK · FAILURE</span></section></div>`
  };

  window.renderRedisVisual = item => (visuals[item.mode] || (() => lane([
    ["01","INPUT",item.question],["02","PROCESS",item.takeaway],["03","OUTPUT",item.story[2] || item.story[1]]
  ])))();
})();
